///////////////////////////////////////////////////////////
//  MeterReadSchedule.cs
//  Implementation of the Class MeterReadSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:16 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// The meter read schedule class
	/// </summary>
	/// <seealso cref="Document"/>
	public class MeterReadSchedule : Document {

		/// <summary>
		/// All usage points for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Metering.UsagePoint UsagePoint;
		/// <summary>
		/// All end device groups for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Metering.EndDeviceGroup EndDeviceGroup;
		/// <summary>
		/// All reading types for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Metering.ReadingType ReadingType;
		/// <summary>
		/// All usage point groups for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Metering.UsagePointGroup UsagePointGroup;
		/// <summary>
		/// All time schedules for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Common.TimeSchedule TimeSchedule;
		/// <summary>
		/// All customer agreements for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Customers.CustomerAgreement CustomerAgreement;
		/// <summary>
		/// All end devices for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Metering.EndDevice EndDevice;
		/// <summary>
		/// All customer accounts for the meter read schedule.
		/// </summary>
		public TC57CIM.IEC61968.Customers.CustomerAccount CustomerAccount;

		/// <summary>
		/// Initializes a new instance of the <see cref="MeterReadSchedule"/> class
		/// </summary>
		public MeterReadSchedule(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end MeterReadSchedule

}//end namespace Metering