///////////////////////////////////////////////////////////
//  PanPricing.cs
//  Implementation of the Class PanPricing
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:19 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// PAN action/command used to issue pricing information to a PAN device.
	/// </summary>
	public class PanPricing : EndDeviceAction {

		/// <summary>
		/// Unique identifier for the commodity provider.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer providerID;
		/// <summary>
		/// All pricing details issued by this PAN pricing command/action.
		/// </summary>
		public TC57CIM.IEC61968.Metering.PanPricingDetail PanPricingDetails;

		/// <summary>
		/// Initializes a new instance of the <see cref="PanPricing"/> class
		/// </summary>
		public PanPricing(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PanPricing

}//end namespace Metering