///////////////////////////////////////////////////////////
//  ServiceMultiplier.cs
//  Implementation of the Class ServiceMultiplier
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:24 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Multiplier applied at the usage point.
	/// </summary>
	public class ServiceMultiplier : IdentifiedObject {

		/// <summary>
		/// Kind of multiplier.
		/// </summary>
		public ServiceMultiplierKind kind;
		/// <summary>
		/// Multiplier value.
		/// </summary>
		public float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="ServiceMultiplier"/> class
		/// </summary>
		public ServiceMultiplier(){

		}

		~ServiceMultiplier(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ServiceMultiplier

}//end namespace Metering