///////////////////////////////////////////////////////////
//  SimpleEndDeviceFunction.cs
//  Implementation of the Class SimpleEndDeviceFunction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Metering {
	/// <summary>
	/// Simple end device function distinguished by 'kind'. Use this class for
	/// instances that cannot be represented by another end device function
	/// specialisations.
	/// </summary>
	public class SimpleEndDeviceFunction : EndDeviceFunction {

		/// <summary>
		/// Kind of this function.
		/// </summary>
		public EndDeviceFunctionKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="SimpleEndDeviceFunction"/> class
		/// </summary>
		public SimpleEndDeviceFunction(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end SimpleEndDeviceFunction

}//end namespace Metering