///////////////////////////////////////////////////////////
//  BillMediaKind.cs
//  Implementation of the Class BillMediaKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of bill media.
	/// </summary>
	public enum BillMediaKind : int {

		/// <summary>
		/// The paper bill media kind
		/// </summary>
		paper,
		/// <summary>
		/// The electronic bill media kind
		/// </summary>
		electronic,
		/// <summary>
		/// The other bill media kind
		/// </summary>
		other

	}//end BillMediaKind

}//end namespace InfERPSupport
