///////////////////////////////////////////////////////////
//  ErpAccountKind.cs
//  Implementation of the Class ErpAccountKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of ERP account.
	/// </summary>
	public enum ErpAccountKind : int {

		/// <summary>
		/// The normal erp account kind
		/// </summary>
		normal,
		/// <summary>
		/// The reversal erp account kind
		/// </summary>
		reversal,
		/// <summary>
		/// The statistical erp account kind
		/// </summary>
		statistical,
		/// <summary>
		/// The estimate erp account kind
		/// </summary>
		estimate

	}//end ErpAccountKind

}//end namespace InfERPSupport