///////////////////////////////////////////////////////////
//  ErpBomItemData.cs
//  Implementation of the Class ErpBomItemData
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// An individual item on a bill of materials.
	/// </summary>
	public class ErpBomItemData : ErpIdentifiedObject {

		/// <summary>
		/// The design location
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.DesignLocation DesignLocation;
		/// <summary>
		/// The erp bom
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpBOM ErpBOM;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpBomItemData"/> class
		/// </summary>
		public ErpBomItemData(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpBomItemData

}//end namespace InfERPSupport