///////////////////////////////////////////////////////////
//  ErpChartOfAccounts.cs
//  Implementation of the Class ErpChartOfAccounts
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Accounting structure of a business. Each account represents a financial aspect
	/// of a business, such as its Accounts Payable, or the value of its inventory, or
	/// its office supply expenses.
	/// </summary>
	public class ErpChartOfAccounts : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpChartOfAccounts"/> class
		/// </summary>
		public ErpChartOfAccounts(){

		}

		~ErpChartOfAccounts(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ErpChartOfAccounts

}//end namespace InfERPSupport