///////////////////////////////////////////////////////////
//  ErpCompetency.cs
//  Implementation of the Class ErpCompetency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Information that describes aptitudes of a utility employee. Unlike Skills that
	/// an ErpPerson must be certified to perform before undertaking certain type of
	/// assignments (to be able to perfrom a Craft), ErpCompetency has more to do with
	/// typical Human Resource (HR) matters such as schooling, training, etc.
	/// </summary>
	public class ErpCompetency : ErpIdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpCompetency"/> class
		/// </summary>
		public ErpCompetency(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpCompetency

}//end namespace InfERPSupport