///////////////////////////////////////////////////////////
//  ErpDocument.cs
//  Implementation of the Class ErpDocument
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Shadow class for Document, to isolate subclassing from this package. If any
	/// subclass gets normative and needs inheritance, it will inherit directly from
	/// Document.
	/// </summary>
	public class ErpDocument : Document {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpDocument"/> class
		/// </summary>
		public ErpDocument(){

		}

		~ErpDocument(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ErpDocument

}//end namespace InfERPSupport