///////////////////////////////////////////////////////////
//  ErpEngChangeOrder.cs
//  Implementation of the Class ErpEngChangeOrder
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// General Utility Engineering Change Order information.
	/// </summary>
	public class ErpEngChangeOrder : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpEngChangeOrder"/> class
		/// </summary>
		public ErpEngChangeOrder(){

		}

		~ErpEngChangeOrder(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ErpEngChangeOrder

}//end namespace InfERPSupport