///////////////////////////////////////////////////////////
//  ErpIssueInventory.cs
//  Implementation of the Class ErpIssueInventory
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Can be used to request an application to process an issue or request
	/// information about an issue.
	/// </summary>
	public class ErpIssueInventory : ErpIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status? status;
		/// <summary>
		/// The type material
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.TypeMaterial? TypeMaterial;
		/// <summary>
		/// The type asset
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.CatalogAssetType? TypeAsset;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpIssueInventory"/> class
		/// </summary>
		public ErpIssueInventory(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpIssueInventory

}//end namespace InfERPSupport
