///////////////////////////////////////////////////////////
//  ErpInvoiceKind.cs
//  Implementation of the Class ErpInvoiceKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of ERP invoice.
	/// </summary>
	public enum ErpInvoiceKind : int {

		/// <summary>
		/// The sale erp invoice kind
		/// </summary>
		sale,
		/// <summary>
		/// The purchase erp invoice kind
		/// </summary>
		purchase

	}//end ErpInvoiceKind

}//end namespace InfERPSupport
