///////////////////////////////////////////////////////////
//  ErpItemMaster.cs
//  Implementation of the Class ErpItemMaster
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Any unique purchased part for manufactured product tracked by ERP systems for a
	/// utility.
	/// Item, as used by the OAG, refers to the basic information about an item,
	/// including its attributes, cost, and locations. It does not include item
	/// quantities. Compare to the Inventory, which includes all quantities and other
	/// location-specific information.
	/// </summary>
	public class ErpItemMaster : ErpIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status? status;
		/// <summary>
		/// The asset
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset? Asset;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpItemMaster"/> class
		/// </summary>
		public ErpItemMaster(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpItemMaster

}//end namespace InfERPSupport
