///////////////////////////////////////////////////////////
//  ErpInvoiceLineItemKind.cs
//  Implementation of the Class ErpInvoiceLineItemKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Kind of invoice line item.
	/// </summary>
	public enum ErpInvoiceLineItemKind : int {

		/// <summary>
		/// The initial erp invoice line item kind
		/// </summary>
		initial,
		/// <summary>
		/// The recalculation erp invoice line item kind
		/// </summary>
		recalculation,
		/// <summary>
		/// The other erp invoice line item kind
		/// </summary>
		other

	}//end ErpInvoiceLineItemKind

}//end namespace InfERPSupport
