///////////////////////////////////////////////////////////
//  ErpInventoryCount.cs
//  Implementation of the Class ErpInventoryCount
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:08 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// This is related to Inventory physical counts organized by AssetModel. Note that
	/// a count of a type of asset can be accomplished by the association inherited by
	/// AssetModel (from Document) to Asset.
	/// It enables ERP applications to transfer an inventory count between ERP and the
	/// actual physical inventory location. This count may be a cycle count or a
	/// physical count.
	/// </summary>
	public class ErpInventoryCount : ErpIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpInventoryCount"/> class
		/// </summary>
		public ErpInventoryCount(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpInventoryCount

}//end namespace InfERPSupport