///////////////////////////////////////////////////////////
//  ErpLedgerBudget.cs
//  Implementation of the Class ErpLedgerBudget
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Information for utility Ledger Budgets. They support the transfer budget
	/// amounts between all possible source applications throughout an enterprise and a
	/// general ledger or budget application.
	/// </summary>
	public class ErpLedgerBudget : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpLedgerBudget"/> class
		/// </summary>
		public ErpLedgerBudget(){

		}

		~ErpLedgerBudget(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ErpLedgerBudget

}//end namespace InfERPSupport