///////////////////////////////////////////////////////////
//  ErpPayable.cs
//  Implementation of the Class ErpPayable
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// A transaction that represents an invoice from a supplier. A payable (or
	/// voucher) is an open item, approved and ready for payment, in the Accounts
	/// Payable ledger.
	/// </summary>
	public class ErpPayable : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpPayable"/> class
		/// </summary>
		public ErpPayable(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpPayable

}//end namespace InfERPSupport