///////////////////////////////////////////////////////////
//  ErpPurchaseOrder.cs
//  Implementation of the Class ErpPurchaseOrder
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// A document that communicates an order to purchase goods from a buyer to a
	/// supplier. The PurchaseOrder carries information to and from the buyer and
	/// supplier. It is a legally binding document once both Parties agree to the
	/// contents and the specified terms and conditions of the order.
	/// </summary>
	public class ErpPurchaseOrder : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpPurchaseOrder"/> class
		/// </summary>
		public ErpPurchaseOrder(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpPurchaseOrder

}//end namespace InfERPSupport
