///////////////////////////////////////////////////////////
//  ErpPayableLineItem.cs
//  Implementation of the Class ErpPayableLineItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:09 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Of an ErpPayable, a line item references an ErpInvoiceLineitem or other source
	/// such as credit memos.
	/// </summary>
	public class ErpPayableLineItem : ErpIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The erp payments
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPayment ErpPayments;
		/// <summary>
		/// The erp payable
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPayable ErpPayable;
		/// <summary>
		/// The erp journal entries
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpJournalEntry ErpJournalEntries;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpPayableLineItem"/> class
		/// </summary>
		public ErpPayableLineItem(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpPayableLineItem

}//end namespace InfERPSupport