///////////////////////////////////////////////////////////
//  ErpProjectAccounting.cs
//  Implementation of the Class ErpProjectAccounting
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Utility Project Accounting information, used by ERP applications to enable all
	/// relevant sub-systems that submit single sided transactions to transfer
	/// information with a Project Accounting Application. This would include, but not
	/// necessarily be limited to: Accounts Payable, Accounts Receivable, Budget, Order
	/// Management, Purchasing, Time and Labor, Travel and Expense.
	/// </summary>
	public class ErpProjectAccounting : ErpDocument {

		/// <summary>
		/// The projects
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.Project? Projects;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpProjectAccounting"/> class
		/// </summary>
		public ErpProjectAccounting(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpProjectAccounting

}//end namespace InfERPSupport
