///////////////////////////////////////////////////////////
//  ErpReceiveDelivery.cs
//  Implementation of the Class ErpReceiveDelivery
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Transaction for an Organisation receiving goods or services that may be used to
	/// indicate receipt of goods in conjunction with a purchase order. A receivable is
	/// an open (unpaid) item in the Accounts Receivable ledger.
	/// </summary>
	public class ErpReceiveDelivery : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpReceiveDelivery"/> class
		/// </summary>
		public ErpReceiveDelivery(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpReceiveDelivery

}//end namespace InfERPSupport