///////////////////////////////////////////////////////////
//  ErpRecDelvLineItem.cs
//  Implementation of the Class ErpRecDelvLineItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Of an ErpReceiveDelivery, this is an individually received good or service by
	/// the Organisation receiving goods or services. It may be used to indicate
	/// receipt of goods in conjunction with a purchase order line item.
	/// </summary>
	public class ErpRecDelvLineItem : ErpIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The erp receive delivery
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpReceiveDelivery ErpReceiveDelivery;
		/// <summary>
		/// The erp po line item
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPOLineItem ErpPOLineItem;
		/// <summary>
		/// The erp invoice line item
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpInvoiceLineItem ErpInvoiceLineItem;

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpRecDelvLineItem"/> class
		/// </summary>
		public ErpRecDelvLineItem(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpRecDelvLineItem

}//end namespace InfERPSupport