///////////////////////////////////////////////////////////
//  ErpReceivable.cs
//  Implementation of the Class ErpReceivable
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfERPSupport {
	/// <summary>
	/// Transaction representing an invoice, credit memo or debit memo to a customer.
	/// It is an open (unpaid) item in the Accounts Receivable ledger.
	/// </summary>
	public class ErpReceivable : ErpDocument {

		/// <summary>
		/// Initializes a new instance of the <see cref="ErpReceivable"/> class
		/// </summary>
		public ErpReceivable(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ErpReceivable

}//end namespace InfERPSupport