///////////////////////////////////////////////////////////
//  GateInputPin.cs
//  Implementation of the Class GateInputPin
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:57 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// Input pin for a logical gate. The condition described in the input pin will
	/// give a logical true or false. Result from measurement and calculation are
	/// converted to a true or false.
	/// </summary>
	public class GateInputPin : IdentifiedObject {

		/// <summary>
		/// If true, use the absolute value for compare..
		/// </summary>
		public bool absoluteValue;
		/// <summary>
		/// The compare operation.
		/// </summary>
		public AnalogToDigitalLogicKind aDLogicKind;
		/// <summary>
		/// The duration the compare condition need to be present before given a true. Default is 0 seconds.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? duration;
		/// <summary>
		/// Invert/negate the result of the compare.
		/// </summary>
		public bool negate;
		/// <summary>
		/// The threshold percentage that should be used for compare with the percentage
		/// change between input value and threshold value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent? thresholdPercentage;
		/// <summary>
		/// The threshold value that should be used for compare with the input value.
		/// </summary>
		public float thresholdValue;

		/// <summary>
		/// Initializes a new instance of the <see cref="GateInputPin"/> class.
		/// </summary>
		public GateInputPin(){

		}

		/// <summary>
		/// Finalizes an instance of the <see cref="GateInputPin"/> class.
		/// </summary>
		~GateInputPin(){

		}

		/// <summary>
		/// Releases resources used by the <see cref="GateInputPin"/> class.
		/// </summary>
		public override void Dispose(){

		}

	}//end GateInputPin

}//end namespace InfSIPS