///////////////////////////////////////////////////////////
//  PinMeasurement.cs
//  Implementation of the Class PinMeasurement
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// Gate input pin that is associated with a Measurement or a calculation of
	/// Measurement.
	/// </summary>
	public class PinMeasurement : GateInputPin {

		/// <summary>
		/// The Measurement that should be used in compare.
		/// </summary>
		/// <summary>
		/// The Measurement that should be used in compare.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.Measurement? Measurement;

		/// <summary>
		/// Initializes a new instance of the <see cref="PinMeasurement"/> class.
		/// </summary>
		public PinMeasurement(){

		}

		/// <summary>
		/// Finalizes an instance of the <see cref="PinMeasurement"/> class.
		/// </summary>
		~PinMeasurement(){

		}

		/// <summary>
		/// Releases resources used by the <see cref="PinMeasurement"/> class.
		/// </summary>
		public override void Dispose(){

		}

	}//end PinMeasurement

}//end namespace InfSIPS