///////////////////////////////////////////////////////////
//  ProtectiveActionAdjustment.cs
//  Implementation of the Class ProtectiveActionAdjustment
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:16 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// Protective actions on non-switching equipment. The operating condition is
	/// adjusted.
	/// </summary>
	public class ProtectiveActionAdjustment : ProtectiveAction {

		/// <summary>
		/// The adjustment is given in percent of the active value.
		/// </summary>
		/// <summary>
		/// The adjustment is given in percent of the active value.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent? byPercentage;
		/// <summary>
		/// The adjustment is given in value of the active value.
		/// </summary>
		public float byValue;
		/// <summary>
		/// Defines the kind of adjustment that should be done. With this value the correct
		/// attribute containing the value needs to be used.
		/// </summary>
		public ProtectiveActionAdjustmentKind kind;
		/// <summary>
		/// If true, the adjusted value is an reduction. Other wise it is an increase in
		/// the value.
		/// </summary>
		public bool reduce;
		/// <summary>
		/// The adjustment is given by a new active value.
		/// </summary>
		public float setValue;
		/// <summary>
		/// The operating condition to the Conducting Equipment is changed when protective
		/// action adjustment is activated.
		/// </summary>
		/// <summary>
		/// The DC conducting equipment associated with this protective action adjustment.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCConductingEquipment? DCConductingEquipment;

		/// <summary>
		/// Initializes a new instance of the <see cref="ProtectiveActionAdjustment"/> class.
		/// </summary>
		public ProtectiveActionAdjustment(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ProtectiveActionAdjustment"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ProtectiveActionAdjustment

}//end namespace InfSIPS
