///////////////////////////////////////////////////////////
//  TriggerCondition.cs
//  Implementation of the Class TriggerCondition
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:26 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// A conditions that can trigger remedial actions.
	/// </summary>
	public class TriggerCondition : IdentifiedObject {

		/// <summary>
		/// The remedial action scheme associated with this trigger condition.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfSIPS.RemedialActionScheme? RemedialActionScheme;
		/// <summary>
		/// The resulting Gate that is the condition for the Trigger.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfSIPS.Gate? GateTrigger;

		/// <summary>
		/// Initializes a new instance of the <see cref="TriggerCondition"/> class.
		/// </summary>
		public TriggerCondition(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="TriggerCondition"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end TriggerCondition

}//end namespace InfSIPS
