///////////////////////////////////////////////////////////
//  CoolingKind.cs
//  Implementation of the Class CoolingKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of cooling.
	/// </summary>
	public enum CoolingKind : int {

		/// <summary>
		/// The self cooling cooling kind
		/// </summary>
		selfCooling,
		/// <summary>
		/// The forced air cooling kind
		/// </summary>
		forcedAir,
		/// <summary>
		/// The forced oil and air cooling kind
		/// </summary>
		forcedOilAndAir,
		/// <summary>
		/// The other cooling kind
		/// </summary>
		other

	}//end CoolingKind

}//end namespace InfAssets