///////////////////////////////////////////////////////////
//  JointFillKind.cs
//  Implementation of the Class JointFillKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of fill for Joint.
	/// </summary>
	public enum JointFillKind : int {

		/// <summary>
		/// The no fill prefab joint fill kind
		/// </summary>
		noFillPrefab,
		/// <summary>
		/// The air no filling joint fill kind
		/// </summary>
		airNoFilling,
		/// <summary>
		/// The petrolatum joint fill kind
		/// </summary>
		petrolatum,
		/// <summary>
		/// The asphaltic joint fill kind
		/// </summary>
		asphaltic,
		/// <summary>
		/// The oil joint fill kind
		/// </summary>
		oil,
		/// <summary>
		/// The bluefill 254 joint fill kind
		/// </summary>
		bluefill254,
		/// <summary>
		/// The no void joint fill kind
		/// </summary>
		noVoid,
		/// <summary>
		/// The epoxy joint fill kind
		/// </summary>
		epoxy,
		/// <summary>
		/// The insoluseal joint fill kind
		/// </summary>
		insoluseal,
		/// <summary>
		/// The other joint fill kind
		/// </summary>
		other

	}//end JointFillKind

}//end namespace InfAssets
