///////////////////////////////////////////////////////////
//  JointConfigurationKind.cs
//  Implementation of the Class JointConfigurationKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of configuration for joints.
	/// </summary>
	public enum JointConfigurationKind : int {

		/// <summary>
		/// The wires 3to joint configuration kind
		/// </summary>
		wires3to1,
		/// <summary>
		/// The wires 2to joint configuration kind
		/// </summary>
		wires2to1,
		/// <summary>
		/// The wires 1to joint configuration kind
		/// </summary>
		wires1to1,
		/// <summary>
		/// The other joint configuration kind
		/// </summary>
		other

	}//end JointConfigurationKind

}//end namespace InfAssets
