///////////////////////////////////////////////////////////
//  PoleBaseKind.cs
//  Implementation of the Class PoleBaseKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:20 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of base for poles.
	/// </summary>
	public enum PoleBaseKind : int {

		/// <summary>
		/// The asphalt pole base kind
		/// </summary>
		asphalt,
		/// <summary>
		/// The cement pole base kind
		/// </summary>
		cement,
		/// <summary>
		/// The dirt pole base kind
		/// </summary>
		dirt,
		/// <summary>
		/// The unknown pole base kind
		/// </summary>
		unknown,
		/// <summary>
		/// The other pole base kind
		/// </summary>
		other

	}//end PoleBaseKind

}//end namespace InfAssets
