///////////////////////////////////////////////////////////
//  ReliabilityInfo.cs
//  Implementation of the Class ReliabilityInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Information regarding the experienced and expected reliability of a specific
	/// asset, type of asset, or asset model.
	/// </summary>
	public class ReliabilityInfo : IdentifiedObject {

		/// <summary>
		/// Momentary failure rate (temporary failures/kft-year).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent momFailureRate;
		/// <summary>
		/// Mean time to repair (MTTR - hours).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Hours mTTR;
		/// <summary>
		/// The assets
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset Assets;
		/// <summary>
		/// The specification
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.Specification Specification;

		/// <summary>
		/// Initializes a new instance of the <see cref="ReliabilityInfo"/> class
		/// </summary>
		public ReliabilityInfo(){

		}

		~ReliabilityInfo(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ReliabilityInfo

}//end namespace InfAssets