///////////////////////////////////////////////////////////
//  StreetlightLampKind.cs
//  Implementation of the Class StreetlightLampKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of lamp for the streetlight.
	/// </summary>
	public enum StreetlightLampKind : int {

		/// <summary>
		/// The high pressure sodium streetlight lamp kind
		/// </summary>
		highPressureSodium,
		/// <summary>
		/// The mercury vapor streetlight lamp kind
		/// </summary>
		mercuryVapor,
		/// <summary>
		/// The metal halide streetlight lamp kind
		/// </summary>
		metalHalide,
		/// <summary>
		/// The other streetlight lamp kind
		/// </summary>
		other

	}//end StreetlightLampKind

}//end namespace InfAssets