///////////////////////////////////////////////////////////
//  StructureMaterialKind.cs
//  Implementation of the Class StructureMaterialKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of material used for structures.
	/// </summary>
	public enum StructureMaterialKind : int {

		/// <summary>
		/// The wood structure material kind
		/// </summary>
		wood,
		/// <summary>
		/// The steel structure material kind
		/// </summary>
		steel,
		/// <summary>
		/// The concrete structure material kind
		/// </summary>
		concrete,
		/// <summary>
		/// The other structure material kind
		/// </summary>
		other

	}//end StructureMaterialKind

}//end namespace InfAssets
