///////////////////////////////////////////////////////////
//  TowerConstructionKind.cs
//  Implementation of the Class TowerConstructionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:28 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssets {
	/// <summary>
	/// Kind of tower construction.
	/// </summary>
	public enum TowerConstructionKind : int {

		/// <summary>
		/// The suspension tower construction kind
		/// </summary>
		suspension,
		/// <summary>
		/// The tension tower construction kind
		/// </summary>
		tension

	}//end TowerConstructionKind

}//end namespace InfAssets
