///////////////////////////////////////////////////////////
//  DatasetArg.cs
//  Implementation of the Class DatasetArg
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations {
	/// <summary>
	/// A model operation argument referencing a dataset instance.
	/// </summary>
	public class DatasetArg : ModelOperationArg {

		/// <summary>
		/// The type of role for this dataset role.   Should only reference role types that
		/// belong to the operation type of the associated operation.
		/// </summary>
	   /// <summary>
	   /// The type of role for this dataset role. Should only reference role types that belong to the operation type of the associated operation.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations.DatasetArgDescription? OperationDatasetArgDescription;
	   /// <summary>
	   /// Dataset referenced by this argument of a model operation.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet.InstanceSet? Dataset;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="DatasetArg"/> class.
	   /// </summary>
	   public DatasetArg(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="DatasetArg"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end DatasetArg

}//end namespace ModelOperations
