///////////////////////////////////////////////////////////
//  ModelOperationArgDescription.cs
//  Implementation of the Class ModelOperationArgDescription
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations {
	/// <summary>
	/// The type of custom operation dataset role for an operation description.
	/// </summary>
	public class ModelOperationArgDescription : IdentifiedObject {

		/// <summary>
		/// The maximum multiplicity of the instance arguments that should be supplied for
		/// a single operation.     Use -1 to indicate unlimited.
		/// </summary>
	   /// <summary>
	   /// The maximum multiplicity of the instance arguments that should be supplied for a single operation. Use -1 to indicate unlimited.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Integer? multiplicityMaximum;
	   /// <summary>
	   /// The minimum multiplicity of the instance arguments that should be supplied for a single operation. Use zero to indicate optional.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Integer? multiplicityMinimum;
	   /// <summary>
	   /// The type of operation for this type of dataset role. Operations referencing the dataset role type should only belong to operations that reference the operation type.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations.ModelOperationDescription? ModelOperationDefinition;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ModelOperationArgDescription"/> class.
	   /// </summary>
	   public ModelOperationArgDescription(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ModelOperationArgDescription"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelOperationArgDescription

}//end namespace ModelOperations