///////////////////////////////////////////////////////////
//  ModelOperation.cs
//  Implementation of the Class ModelOperation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations {
	/// <summary>
	/// An operation performed on models.
	/// </summary>
	public class ModelOperation : IdentifiedObject {

		/// <summary>
		/// Sequence number within a operation sequence, lower is first.   Normally starts
		/// with 1.
		/// </summary>
	   /// <summary>
	   /// Sequence number within an operation sequence, lower is first. Normally starts with 1.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Integer? sequenceNumber;
	   /// <summary>
	   /// The type of the model operation.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.ModelOperations.ModelOperationDescription? ModelOperationDescription;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ModelOperation"/> class.
	   /// </summary>
	   public ModelOperation(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ModelOperation"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelOperation

}//end namespace ModelOperations