///////////////////////////////////////////////////////////
//  WindTurbineType4bIEC.cs
//  Implementation of the Class WindTurbineType4bIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:33 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Wind turbine IEC type 4B.
	/// Reference: IEC 61400-27-1:2015, 5.5.5.3.
	/// </summary>
	public class WindTurbineType4bIEC : WindTurbineType4IEC {

		/// <summary>
		/// Initializes a new instance of the <see cref="WindTurbineType4bIEC"/> class
		/// </summary>
		public WindTurbineType4bIEC(){

		}

		~WindTurbineType4bIEC(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end WindTurbineType4bIEC

}//end namespace WindDynamics