///////////////////////////////////////////////////////////
//  WindTurbineType3or4Dynamics.cs
//  Implementation of the Class WindTurbineType3or4Dynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:32 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Parent class supporting relationships to wind turbines type 3 and type 4 and
	/// wind plant including their control models.
	/// </summary>
	public class WindTurbineType3or4Dynamics : DynamicsFunctionBlock {

		/// <summary>
		/// The power electronics connection associated with this wind turbine type 3 or
		/// type 4 dynamics model.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.PowerElectronicsConnection PowerElectronicsConnection;
		/// <summary>
		/// Remote input signal used by these wind turbine type 3 or type 4 models.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal RemoteInputSignal;

		/// <summary>
		/// Initializes a new instance of the <see cref="WindTurbineType3or4Dynamics"/> class
		/// </summary>
		public WindTurbineType3or4Dynamics(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindTurbineType3or4Dynamics

}//end namespace WindDynamics