///////////////////////////////////////////////////////////
//  WindGenTurbineType1bIEC.cs
//  Implementation of the Class WindGenTurbineType1bIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:31 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Wind turbine IEC type 1B.
	///
	/// Reference: IEC 61400-27-1:2015, 5.5.2.3.
	/// </summary>
	public class WindGenTurbineType1bIEC : WindTurbineType1or2IEC {

		/// <summary>
		/// Pitch control power model associated with this wind turbine type 1B model.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindPitchContPowerIEC? WindPitchContPowerIEC;

		/// <summary>
		/// Initializes a new instance of the <see cref="WindGenTurbineType1bIEC"/> class
		/// </summary>
		public WindGenTurbineType1bIEC(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindGenTurbineType1bIEC

}//end namespace WindDynamics
