///////////////////////////////////////////////////////////
//  WindTurbineType4IEC.cs
//  Implementation of the Class WindTurbineType4IEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:33 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Parent class supporting relationships to IEC wind turbines type 4 including
	/// their control models.
	/// </summary>
	public class WindTurbineType4IEC : WindTurbineType3or4IEC {

		/// <summary>
		/// Initializes a new instance of the <see cref="WindTurbineType4IEC"/> class
		/// </summary>
		public WindTurbineType4IEC(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindTurbineType4IEC

}//end namespace WindDynamics