///////////////////////////////////////////////////////////
//  WindTurbineType1or2IEC.cs
//  Implementation of the Class WindTurbineType1or2IEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:32 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Parent class supporting relationships to IEC wind turbines type 1 and type 2
	/// including their control models.
	/// Generator model for wind turbine of IEC type 1 or type 2 is a standard
	/// asynchronous generator model.
	/// Reference: IEC 61400-27-1:2015, 5.5.2 and 5.5.3.
	/// </summary>
	public class WindTurbineType1or2IEC : WindTurbineType1or2Dynamics {

		/// <summary>
		/// Initializes a new instance of the <see cref="WindTurbineType1or2IEC"/> class
		/// </summary>
		public WindTurbineType1or2IEC(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindTurbineType1or2IEC

}//end namespace WindDynamics