///////////////////////////////////////////////////////////
//  WindGenTurbineType2IEC.cs
//  Implementation of the Class WindGenTurbineType2IEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:31 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Wind turbine IEC type 2.
	/// 
	/// Reference: IEC 61400-27-1:2015, 5.5.3.
	/// </summary>
	public class WindGenTurbineType2IEC : WindTurbineType1or2IEC {

		/// <summary>
		/// Initializes a new instance of the <see cref="WindGenTurbineType2IEC"/> class
		/// </summary>
		public WindGenTurbineType2IEC(){

		}

		~WindGenTurbineType2IEC(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end WindGenTurbineType2IEC

}//end namespace WindDynamics