///////////////////////////////////////////////////////////
//  WindContQLimIEC.cs
//  Implementation of the Class WindContQLimIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:30 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Constant Q limitation model.
	/// Reference: IEC 61400-27-1:2015, 5.6.5.9.
	/// </summary>
	public class WindContQLimIEC : IdentifiedObject {

		/// <summary>
		/// Maximum reactive power (<i>q</i><i><sub>max</sub></i>) (> WindContQLimIEC.qmin).
		/// It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? qmax;
		/// <summary>
		/// Minimum reactive power (<i>q</i><i><sub>min</sub></i>) (&lt; WindContQLimIEC.qmax).
		/// It is a type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? qmin;
		/// <summary>
		/// Wind generator type 3 or type 4 model with which this constant Q limitation
		/// model is associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType3or4IEC? WindTurbineType3or4IEC;

		/// <summary>
		/// Initializes a new instance of the <see cref="WindContQLimIEC"/> class
		/// </summary>
		public WindContQLimIEC(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindContQLimIEC

}//end namespace WindDynamics
