///////////////////////////////////////////////////////////
//  WindTurbineType3IEC.cs
//  Implementation of the Class WindTurbineType3IEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:32 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// Parent class supporting relationships to IEC wind turbines type 3 including
	/// their control models.
	/// </summary>
	public class WindTurbineType3IEC : WindTurbineType3or4IEC {

		/// <summary>
		/// Initializes a new instance of the <see cref="WindTurbineType3IEC"/> class
		/// </summary>
		public WindTurbineType3IEC(){

		}

		~WindTurbineType3IEC(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end WindTurbineType3IEC

}//end namespace WindDynamics