///////////////////////////////////////////////////////////
//  WindGenType3bIEC.cs
//  Implementation of the Class WindGenType3bIEC
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:31 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics {
	/// <summary>
	/// IEC type 3B generator set model.
	/// Reference: IEC 61400-27-1:2015, 5.6.3.3.
	/// </summary>
	public class WindGenType3bIEC : WindGenType3IEC {

		/// <summary>
		/// Crowbar control mode (<i>M</i><i><sub>WTcwp</sub></i>). It is a case-dependent
		/// parameter.
		/// true = 1 in the IEC model
		/// false = 0 in the IEC model.
		/// </summary>
		public bool mwtcwp;
		/// <summary>
		/// Current generation time constant (<i>T</i><i><sub>g</sub></i>) (>= 0). It is a
		/// type-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tg;
		/// <summary>
		/// Time constant for crowbar washout filter (<i>T</i><i><sub>wo</sub></i>) (>= 0).
		/// It is a case-dependent parameter.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds two;

		/// <summary>
		/// Initializes a new instance of the <see cref="WindGenType3bIEC"/> class
		/// </summary>
		public WindGenType3bIEC(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindGenType3bIEC

}//end namespace WindDynamics