///////////////////////////////////////////////////////////
//  DiagramObjectGluePoint.cs
//  Implementation of the Class DiagramObjectGluePoint
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:48 AM
//  Original author: mcmorran
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DiagramLayout {
	/// <summary>
	/// This is used for grouping diagram object points from different diagram objects
	/// that are considered to be glued together in a diagram even if they are not at
	/// the exact same coordinates.
	/// </summary>
	public class DiagramObjectGluePoint {

		/// <summary>
		/// Initializes a new instance of the <see cref="DiagramObjectGluePoint"/> class
		/// </summary>
		public DiagramObjectGluePoint(){

		}

		~DiagramObjectGluePoint(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end DiagramObjectGluePoint

}//end namespace DiagramLayout