///////////////////////////////////////////////////////////
//  MaintenanceOrder.cs
//  Implementation of the Class MaintenanceOrder
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:14 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Work {
	public class MaintenanceOrder : WorkOrder {

		public MaintenanceOrder(){

		}

		~MaintenanceOrder(){

		}

		public override void Dispose(){

		}

	}//end MaintenanceOrder

}//end namespace Work