///////////////////////////////////////////////////////////
//  PinGate.cs
//  Implementation of the Class PinGate
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfSIPS {
	/// <summary>
	/// An output from one gate represent an input to another gate.
	/// </summary>
	public class PinGate : GateInputPin {

		public PinGate(){

		}

		~PinGate(){

		}

		public override void Dispose(){

		}

	}//end PinGate

}//end namespace InfSIPS