///////////////////////////////////////////////////////////
//  AssemblyDescription.cs
//  Implementation of the Class AssemblyDescription
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:40 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A description for how to assemble model parts for a specific purpose.
	/// </summary>
	public class AssemblyDescription : IdentifiedObject {

		/// <summary>
		/// The models that are part of the assembly descrption.
		/// </summary>
	   /// <summary>
	   /// The model specification for this assembly description.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.ModelPartSpecification? ModelSpecification;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="AssemblyDescription"/> class.
	   /// </summary>
	   public AssemblyDescription(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="AssemblyDescription"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end AssemblyDescription

}//end namespace NetworkModelFrames
