///////////////////////////////////////////////////////////
//  AssemblyManifest.cs
//  Implementation of the Class AssemblyManifest
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:40 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A collection of model parts when combined form a case or part of a case.
	/// </summary>
	public class AssemblyManifest : IdentifiedObject {

	   // ...existing code...
	   /// <summary>
	   /// The complete model to be deleted, if any, associated with this assembly manifest.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.CompleteModelToBeDeleted? m_CompleteModelToBeDeleted;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="AssemblyManifest"/> class.
	   /// </summary>
	   public AssemblyManifest(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="AssemblyManifest"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end AssemblyManifest

}//end namespace NetworkModelFrames
