///////////////////////////////////////////////////////////
//  LoadModelPartVersion.cs
//  Implementation of the Class LoadModelPartVersion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// Load a model part version.
	/// </summary>
	public class LoadModelPartVersion {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="LoadModelPartVersion"/> class.
	   /// </summary>
	   public LoadModelPartVersion(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="LoadModelPartVersion"/> class.
	   /// </summary>
	   ~LoadModelPartVersion(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="LoadModelPartVersion"/> class.
	   /// </summary>
	   public virtual void Dispose(){

		}

	}//end LoadModelPartVersion

}//end namespace NetworkModelFrames