///////////////////////////////////////////////////////////
//  ModelToBeDeleted.cs
//  Implementation of the Class ModelToBeDeleted
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A Model is a collection of Datasets.
	/// </summary>
	public class ModelToBeDeleted : IdentifiedObject {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ModelToBeDeleted"/> class.
	   /// </summary>
	   public ModelToBeDeleted(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ModelToBeDeleted"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelToBeDeleted

}//end namespace NetworkModelFrames