///////////////////////////////////////////////////////////
//  ModelAuthoritySet.cs
//  Implementation of the Class ModelAuthoritySet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A Modeling Authority Set is a group of objects in a network model where the
	/// data is supplied and maintained by the same Modeling Authority.
	/// This class is typically not included in instance data exchange as this
	/// information is tracked by other mechanisms in the exchange.
	/// </summary>
	public class ModelAuthoritySet : IdentifiedObject {

		/// <summary>
		/// Modeling Authority suppliying and maintaining the data for the objects in this
		/// Modeling Authority Set.
		/// </summary>
	   /// <summary>
	   /// The modeling authority supplying and maintaining the data for the objects in this set.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.ModelAuthority? ModelingAuthority;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ModelAuthoritySet"/> class.
	   /// </summary>
	   public ModelAuthoritySet(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ModelAuthoritySet"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelAuthoritySet

}//end namespace NetworkModelFrames
