///////////////////////////////////////////////////////////
//  ModelPartVersion.cs
//  Implementation of the Class ModelPartVersion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// This is a version of a part of a model.  New instances of this class with new
	/// identity are instantiated upon changes to the content of this class or changes
	/// to the associated data set.  Instances of this class are considered immutable.
	/// The case audit trail can reference this immutable data to exactly reproduce a
	/// case.
	/// </summary>
	public class ModelPartVersion : ModelToBeDeleted {

		/// <summary>
		/// Model specification of the modelt.
		/// </summary>
	   /// <summary>
	   /// The model specification for this model part version.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.ModelPartSpecification? ModelSpecification;
	   /// <summary>
	   /// The data set associated with this model part version.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet.DataSet? m_DataSet;
	   /// <summary>
	   /// The complete model to be deleted, if any, associated with this model part version.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.CompleteModelToBeDeleted? m_CompleteModelToBeDeleted;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ModelPartVersion"/> class.
	   /// </summary>
	   public ModelPartVersion(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ModelPartVersion"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelPartVersion

}//end namespace NetworkModelFrames
