///////////////////////////////////////////////////////////
//  NetworkBoundary.cs
//  Implementation of the Class NetworkBoundary
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:09 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A framework part that is a boundary between 2 frames.
	/// </summary>
	public class NetworkBoundary : FrameworkPart {

	   /// <summary>
	   /// The network frame associated with this boundary.
	   /// </summary>
	   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.NetworkFrame? m_NetworkFrame;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="NetworkBoundary"/> class.
	   /// </summary>
	   public NetworkBoundary(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="NetworkBoundary"/> class.
	   /// </summary>
	   ~NetworkBoundary(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="NetworkBoundary"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end NetworkBoundary

}//end namespace NetworkModelFrames