///////////////////////////////////////////////////////////
//  NetworkFrame.cs
//  Implementation of the Class NetworkFrame
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:09 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	/// <summary>
	/// A region isolated by boundaries.
	/// </summary>
	public class NetworkFrame : FrameworkPart {

	   // ...existing code...

	   /// <summary>
	   /// Initializes a new instance of the <see cref="NetworkFrame"/> class.
	   /// </summary>
	   public NetworkFrame(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="NetworkFrame"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end NetworkFrame

}//end namespace NetworkModelFrames