///////////////////////////////////////////////////////////
//  Operation.cs
//  Implementation of the Class Operation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames {
	   /// <summary>
	   /// Represents an operation in the network model frame.
	   /// </summary>
	   public class Operation {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="Operation"/> class.
	   /// </summary>
	   public Operation(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="Operation"/> class.
	   /// </summary>
	   ~Operation(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="Operation"/> class.
	   /// </summary>
	   public virtual void Dispose(){

		}

	}//end Operation

}//end namespace NetworkModelFrames