///////////////////////////////////////////////////////////
//  GovHydroIEEE0.cs
//  Implementation of the Class GovHydroIEEE0
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:59 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics {
	/// <summary>
	/// IEEE simplified hydro governor-turbine model.  Used for mechanical-hydraulic
	/// and electro-hydraulic turbine governors, with or without steam feedback.
	/// Typical values given are for mechanical-hydraulic turbine-governor.
	/// Ref<font color="#0f0f0f">erence: IEEE Transactions on Power Apparatus and
	/// Systems, November/December 1973, Volume PAS-92, Number 6, <i><u>Dynamic Models
	/// for Steam and Hydro Turbines in Power System Studies</u></i>, page 1904.
	/// </font>
	/// </summary>
	public class GovHydroIEEE0 : TurbineGovernorDynamics {

		/// <summary>
		/// Governor gain (<i>K)</i>.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? k;
		/// <summary>
		/// Base for power values (<i>MWbase</i>) (> 0).  Unit = MW.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower? mwbase;
		/// <summary>
		/// Gate maximum (<i>Pmax</i>) (&gt; GovHydroIEEE0.pmin).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? pmax;
		/// <summary>
		/// Gate minimum (<i>Pmin</i>) (&lt; GovHydroIEEE0.pmax).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? pmin;
		/// <summary>
		/// Governor lag time constant (<i>T1</i>) (>= 0).  Typical value = 0,25.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? t1;
		/// <summary>
		/// Governor lead time constant (<i>T2)</i> (>= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? t2;
		/// <summary>
		/// Gate actuator time constant (<i>T3</i>) (>= 0).  Typical value = 0,1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? t3;
		/// <summary>
		/// Water starting time (<i>T4</i>) (>= 0).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? t4;

		/// <summary>
		/// Initializes a new instance of the <see cref="GovHydroIEEE0"/> class
		/// </summary>
		public GovHydroIEEE0(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end GovHydroIEEE0

}//end namespace TurbineGovernorDynamics
