///////////////////////////////////////////////////////////
//  TurbineGovernorDynamics.cs
//  Implementation of the Class TurbineGovernorDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:27 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics {
	/// <summary>
	/// Turbine-governor function block whose behaviour is described by reference to a
	/// standard model <font color="#0f0f0f">or by definition of a user-defined model.
	/// </font>
	/// </summary>
	public class TurbineGovernorDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Asynchronous machine model with which this turbine-governor model is associated.
		/// TurbineGovernorDynamics shall have either an association to
		/// SynchronousMachineDynamics or to AsynchronousMachineDynamics.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.AsynchronousMachineDynamics.AsynchronousMachineDynamics AsynchronousMachineDynamics;

		/// <summary>
		/// Initializes a new instance of the <see cref="TurbineGovernorDynamics"/> class
		/// </summary>
		public TurbineGovernorDynamics(){

		}

		~TurbineGovernorDynamics(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end TurbineGovernorDynamics

}//end namespace TurbineGovernorDynamics