///////////////////////////////////////////////////////////
//  CCArectifierControl.cs
//  Implementation of the Class CCArectifierControl
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:42 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC {
	public class CCArectifierControl {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.CSCtype1 m_CSCtype1;

		public CCArectifierControl(){

		}

		~CCArectifierControl(){

		}

		public virtual void Dispose(){

		}

	}//end CCArectifierControl

}//end namespace CSC