///////////////////////////////////////////////////////////
//  ProvidedBilateralPoint.cs
//  Implementation of the Class ProvidedBilateralPoint
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:16 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.ICCPConfiguration {
	/// <summary>
	/// Allows declaration of ICCP points to be provided through a Bilateral Table
	/// agreement.
	/// </summary>
	public class ProvidedBilateralPoint : IdentifiedObject {

		/// <summary>
		/// Remote peer that will receive ICCP information in a Bilateral table.
		/// </summary>
		public TC57CIM.IEC61970.Base.ICCPConfiguration.BilateralExchangeActor BilateralExchangeActor;

		/// <summary>
		/// Initializes a new instance of the <see cref="ProvidedBilateralPoint"/> class
		/// </summary>
		public ProvidedBilateralPoint(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ProvidedBilateralPoint

}//end namespace ICCPConfiguration