///////////////////////////////////////////////////////////
//  Delay.cs
//  Implementation of the Class Delay
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics {
	/// <summary>
	/// All the measurements are filtered by a first lag element with a time constant
	/// TM.
	/// </summary>
	public class Delay {

		/// <summary>
		/// Time constant.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tm;
		/// <summary>
		/// The idcinvertercontrol
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.IdcInverterControl m_IdcInverterControl;
		/// <summary>
		/// The vdcol
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.VDCOL m_VDCOL;
		/// <summary>
		/// The ccainverter
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.CCAinverter m_CCAinverter;
		/// <summary>
		/// The pcontrol
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Pcontrol Pcontrol;
		/// <summary>
		/// The qregulator
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Qregulator Qregulator;
		/// <summary>
		/// The ccarectifiercontrol
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.CCArectifierControl m_CCArectifierControl;
		/// <summary>
		/// The cvoltage control
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.DCvoltageControl DCvoltageControl;
		/// <summary>
		/// The umode
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Umode Umode;
		/// <summary>
		/// The qlimiter
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Qlimiter Qlimiter;
		/// <summary>
		/// The blocking function
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.BlockingFunction BlockingFunction;
		/// <summary>
		/// The qmode
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Qmode Qmode;
		/// <summary>
		/// The fmode
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.PFmode PFmode;

		/// <summary>
		/// Initializes a new instance of the <see cref="Delay"/> class
		/// </summary>
		public Delay(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Delay

}//end namespace InfHVDCDynamics