///////////////////////////////////////////////////////////
//  HVDCLookUpTable.cs
//  Implementation of the Class HVDCLookUpTable
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics {
	/// <summary>
	/// The hvdc look up table class
	/// </summary>
	public class HVDCLookUpTable {

		/// <summary>
		/// The function kind
		/// </summary>
		public LookUpTableFunctionKind functionKind;
		/// <summary>
		/// The input
		/// </summary>
		public float input;
		/// <summary>
		/// The output
		/// </summary>
		public float output;
		/// <summary>
		/// The sequence
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer? sequence;
		/// <summary>
		/// The qregulator
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.Qregulator? Qregulator;
		/// <summary>
		/// The vdcol
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.VDCOL? m_VDCOL;

		/// <summary>
		/// Initializes a new instance of the <see cref="HVDCLookUpTable"/> class
		/// </summary>
		public HVDCLookUpTable(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end HVDCLookUpTable

}//end namespace InfHVDCDynamics
