///////////////////////////////////////////////////////////
//  LookUpTableFunctionKind.cs
//  Implementation of the Class LookUpTableFunctionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics {
	/// <summary>
	/// The look up table function kind enum
	/// </summary>
	public enum LookUpTableFunctionKind : int {

		/// <summary>
		/// The additional qcurrent look up table function kind
		/// </summary>
		additionalQcurrent,
		/// <summary>
		/// The vdcol look up table function kind
		/// </summary>
		vdcol

	}//end LookUpTableFunctionKind

}//end namespace InfHVDCDynamics