///////////////////////////////////////////////////////////
//  LookUpTableFunctionKind.cs
//  Implementation of the Class LookUpTableFunctionKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics {
	public enum LookUpTableFunctionKind : int {

		additionalQcurrent,
		vdcol

	}//end LookUpTableFunctionKind

}//end namespace InfHVDCDynamics