///////////////////////////////////////////////////////////
//  AccumulatorLimit.cs
//  Implementation of the Class AccumulatorLimit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:38 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Limit values for Accumulator measurements.
	/// </summary>
	public class AccumulatorLimit : Limit {

		/// <summary>
		/// The value to supervise against. The value is positive.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer value;

		/// <summary>
		/// Initializes a new instance of the <see cref="AccumulatorLimit"/> class
		/// </summary>
		public AccumulatorLimit(){

		}

		~AccumulatorLimit(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end AccumulatorLimit

}//end namespace Meas