///////////////////////////////////////////////////////////
//  AnalogLimit.cs
//  Implementation of the Class AnalogLimit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Limit values for Analog measurements.
	/// </summary>
	public class AnalogLimit : Limit {

		/// <summary>
		/// The value to supervise against.
		/// </summary>
		public float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="AnalogLimit"/> class
		/// </summary>
		public AnalogLimit(){

		}

		~AnalogLimit(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end AnalogLimit

}//end namespace Meas