///////////////////////////////////////////////////////////
//  AnalogLimitSet.cs
//  Implementation of the Class AnalogLimitSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// An AnalogLimitSet specifies a set of Limits that are associated with an Analog
	/// measurement.
	/// </summary>
	public class AnalogLimitSet : LimitSet {

		/// <summary>
		/// The limit values used for supervision of Measurements.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.AnalogLimit? Limits;

		/// <summary>
		/// Initializes a new instance of the <see cref="AnalogLimitSet"/> class
		/// </summary>
		public AnalogLimitSet(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AnalogLimitSet

}//end namespace Meas
