///////////////////////////////////////////////////////////
//  Analog.cs
//  Implementation of the Class Analog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Analog represents an analog Measurement.
	/// </summary>
	public class Analog : Measurement {

		/// <summary>
		/// Normal value range maximum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public float maxValue;
		/// <summary>
		/// Normal value range minimum for any of the MeasurementValue.values. Used for
		/// scaling, e.g. in bar graphs or of telemetered raw values.
		/// </summary>
		public float minValue;
		/// <summary>
		/// Normal measurement value, e.g., used for percentage calculations.
		/// </summary>
		public float normalValue;
		/// <summary>
		/// If true then this measurement is an active power, reactive power or current
		/// with the convention that a positive value measured at the Terminal means power
		/// is flowing into the related PowerSystemResource.
		/// </summary>
		public bool positiveFlowIn;
		/// <summary>
		/// The values connected to this measurement.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.AnalogValue? AnalogValues;
		/// <summary>
		/// A measurement may have zero or more limit ranges defined for it.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.AnalogLimitSet? LimitSets;

		/// <summary>
		/// Initializes a new instance of the <see cref="Analog"/> class
		/// </summary>
		public Analog(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Analog

}//end namespace Meas
