///////////////////////////////////////////////////////////
//  Command.cs
//  Implementation of the Class Command
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// A Command is a discrete control used for supervisory control.
	/// </summary>
	public class Command : Control {

		/// <summary>
		/// Normal value for Control.value e.g. used for percentage scaling.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer? normalValue;
		/// <summary>
		/// The value representing the actuator output.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer? value;
		/// <summary>
		/// The ValueAliasSet used for translation of a Control value to a name.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.ValueAliasSet? ValueAliasSet;

		/// <summary>
		/// Initializes a new instance of the <see cref="Command"/> class
		/// </summary>
		public Command(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Command

}//end namespace Meas
