///////////////////////////////////////////////////////////
//  DiscreteValue.cs
//  Implementation of the Class DiscreteValue
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:49 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// DiscreteValue represents a discrete MeasurementValue.
	/// </summary>
	public class DiscreteValue : MeasurementValue {

		/// <summary>
		/// The value to supervise.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer value;
		/// <summary>
		/// The Control variable associated with the MeasurementValue.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.Command Command;

		/// <summary>
		/// Initializes a new instance of the <see cref="DiscreteValue"/> class
		/// </summary>
		public DiscreteValue(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DiscreteValue

}//end namespace Meas