///////////////////////////////////////////////////////////
//  LimitSet.cs
//  Implementation of the Class LimitSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Specifies a set of Limits that are associated with a Measurement. A Measurement
	/// may have several LimitSets corresponding to seasonal or other changing
	/// conditions. The condition is captured in the name and description attributes.
	/// The same LimitSet may be used for several Measurements. In particular
	/// percentage limits are used this way.
	/// </summary>
	public class LimitSet : IdentifiedObject {

		/// <summary>
		/// Tells if the limit values are in percentage of normalValue or the specified
		/// Unit for Measurements and Controls.
		/// </summary>
		public bool isPercentageLimits;

		/// <summary>
		/// Initializes a new instance of the <see cref="LimitSet"/> class
		/// </summary>
		public LimitSet(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end LimitSet

}//end namespace Meas
