///////////////////////////////////////////////////////////
//  MeasurementValueSource.cs
//  Implementation of the Class MeasurementValueSource
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// MeasurementValueSource describes the alternative sources updating a
	/// MeasurementValue. User conventions for how to use the MeasurementValueSource
	/// attributes are defined in IEC 61970-301.
	/// </summary>
	public class MeasurementValueSource : IdentifiedObject {

		/// <summary>
		/// The MeasurementValues updated by the source.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.MeasurementValue? MeasurementValues;

		/// <summary>
		/// Initializes a new instance of the <see cref="MeasurementValueSource"/> class
		/// </summary>
		public MeasurementValueSource(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end MeasurementValueSource

}//end namespace Meas
