///////////////////////////////////////////////////////////
//  MeasurementValueQuality.cs
//  Implementation of the Class MeasurementValueQuality
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Meas {
	/// <summary>
	/// Measurement quality flags. Bits 0-10 are defined for substation automation in
	/// IEC 61850-7-3. Bits 11-15 are reserved for future expansion by that document.
	/// Bits 16-31 are reserved for EMS applications.
	/// </summary>
	public class MeasurementValueQuality : Quality61850 {

		/// <summary>
		/// Initializes a new instance of the <see cref="MeasurementValueQuality"/> class
		/// </summary>
		public MeasurementValueQuality(){

		}

		~MeasurementValueQuality(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end MeasurementValueQuality

}//end namespace Meas