///////////////////////////////////////////////////////////
//  StandardIndustryCode.cs
//  Implementation of the Class StandardIndustryCode
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCustomers {
	/// <summary>
	/// The Standard Industrial Classification (SIC) are the codes that identify the
	/// type of products/service an industry is involved in, and used for statutory
	/// reporting purposes. For example, in the USA these codes are located by the
	/// federal government, and then published in a book entitled "The Standard
	/// Industrial Classification Manual". The codes are arranged in a hierarchical
	/// structure.
	/// Note that Residential Service Agreements are not classified according to the
	/// SIC codes.
	/// </summary>
	public class StandardIndustryCode : Document {

		/// <summary>
		/// Standard alphanumeric code assigned to a particular product/service within an
		/// industry.
		/// </summary>
		public string? code;

		/// <summary>
		/// Initializes a new instance of the <see cref="StandardIndustryCode"/> class
		/// </summary>
		public StandardIndustryCode(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end StandardIndustryCode

}//end namespace InfCustomers
