///////////////////////////////////////////////////////////
//  SubscribePowerCurve.cs
//  Implementation of the Class SubscribePowerCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:26 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfCustomers {
	/// <summary>
	/// Price curve for specifying the cost of energy (X) at points in time (y1)
	/// according to a prcing structure, which is based on a tariff.
	/// </summary>
	public class SubscribePowerCurve : Curve {

		/// <summary>
		/// Initializes a new instance of the <see cref="SubscribePowerCurve"/> class
		/// </summary>
		public SubscribePowerCurve(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end SubscribePowerCurve

}//end namespace InfCustomers