///////////////////////////////////////////////////////////
//  Conductor.cs
//  Implementation of the Class Conductor
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Combination of conducting material with consistent electrical characteristics,
	/// building a single electrical system, used to carry current between points in
	/// the power system.
	/// </summary>
	public class Conductor : ConductingEquipment {

		/// <summary>
		/// Segment length for calculating line section capabilities.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Length? length;

		/// <summary>
		/// Initializes a new instance of the <see cref="Conductor"/> class
		/// </summary>
		public Conductor(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Conductor

}//end namespace Wires
