///////////////////////////////////////////////////////////
//  Connector.cs
//  Implementation of the Class Connector
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A conductor, or group of conductors, with negligible impedance, that serve to
	/// connect other conducting equipment within a single substation and are modelled
	/// with a single logical terminal.
	/// </summary>
	public class Connector : ConductingEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="Connector"/> class
		/// </summary>
		public Connector(){

		}

		~Connector(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end Connector

}//end namespace Wires