///////////////////////////////////////////////////////////
//  DisconnectingCircuitBreaker.cs
//  Implementation of the Class DisconnectingCircuitBreaker
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:48 AM
//  Original author: C56850
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A circuit breaking device including disconnecting function, eliminating the
	/// need for separate disconnectors.
	/// </summary>
	public class DisconnectingCircuitBreaker : Breaker {

		/// <summary>
		/// Initializes a new instance of the <see cref="DisconnectingCircuitBreaker"/> class
		/// </summary>
		public DisconnectingCircuitBreaker(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DisconnectingCircuitBreaker

}//end namespace Wires