///////////////////////////////////////////////////////////
//  GroundDisconnector.cs
//  Implementation of the Class GroundDisconnector
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:00 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A manually operated or motor operated mechanical switching device used for
	/// isolating a circuit or equipment from ground.
	/// </summary>
	public class GroundDisconnector : Switch {

		/// <summary>
		/// Initializes a new instance of the <see cref="GroundDisconnector"/> class
		/// </summary>
		public GroundDisconnector(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end GroundDisconnector

}//end namespace Wires