///////////////////////////////////////////////////////////
//  Junction.cs
//  Implementation of the Class Junction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A point where one or more conducting equipments are connected with zero
	/// resistance.
	/// </summary>
	public class Junction : Connector {

		/// <summary>
		/// Initializes a new instance of the <see cref="Junction"/> class
		/// </summary>
		public Junction(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Junction

}//end namespace Wires