///////////////////////////////////////////////////////////
//  Line.cs
//  Implementation of the Class Line
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Contains equipment beyond a substation belonging to a power transmission line.
	/// </summary>
	public class Line : EquipmentContainer {

		/// <summary>
		/// Initializes a new instance of the <see cref="Line"/> class
		/// </summary>
		public Line(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Line

}//end namespace Wires