///////////////////////////////////////////////////////////
//  NonlinearShuntCompensatorPhase.cs
//  Implementation of the Class NonlinearShuntCompensatorPhase
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A per phase non linear shunt compensator has bank or section admittance values
	/// that differ. The attributes g and b of the associated
	/// NonlinearShuntCompensatorPhasePoint describe the total conductance and
	/// admittance of a NonlinearShuntCompensatorPhasePoint at a section number
	/// specified by NonlinearShuntCompensatorPhasePoint.sectionNumber.
	/// </summary>
	public class NonlinearShuntCompensatorPhase : ShuntCompensatorPhase {

		/// <summary>
		/// All points of the non-linear shunt compensator phase.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.NonlinearShuntCompensatorPhasePoint NonlinearShuntCompensatorPhasePoints;

		/// <summary>
		/// Initializes a new instance of the <see cref="NonlinearShuntCompensatorPhase"/> class
		/// </summary>
		public NonlinearShuntCompensatorPhase(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end NonlinearShuntCompensatorPhase

}//end namespace Wires