///////////////////////////////////////////////////////////
//  PerLengthPhaseImpedance.cs
//  Implementation of the Class PerLengthPhaseImpedance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:11 AM
//  Original author: Tom
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Impedance and admittance parameters per unit length for n-wire unbalanced lines,
	/// in matrix form.
	/// </summary>
	public class PerLengthPhaseImpedance : PerLengthImpedance {

		/// <summary>
		/// Number of phase, neutral, and other wires retained. Constrains the number of
		/// matrix elements and the phase codes that can be used with this matrix.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer conductorCount;
		/// <summary>
		/// All data that belong to this conductor phase impedance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.PhaseImpedanceData PhaseImpedanceData;

		/// <summary>
		/// Initializes a new instance of the <see cref="PerLengthPhaseImpedance"/> class
		/// </summary>
		public PerLengthPhaseImpedance(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PerLengthPhaseImpedance

}//end namespace Wires