///////////////////////////////////////////////////////////
//  PerLengthLineParameter.cs
//  Implementation of the Class PerLengthLineParameter
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:11 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Common type for per-length electrical catalogues describing line parameters.
	/// </summary>
	public class PerLengthLineParameter : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="PerLengthLineParameter"/> class
		/// </summary>
		public PerLengthLineParameter(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PerLengthLineParameter

}//end namespace Wires
