///////////////////////////////////////////////////////////
//  PhaseTapChangerSymmetrical.cs
//  Implementation of the Class PhaseTapChangerSymmetrical
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Describes a symmetrical phase shifting transformer tap model in which the
	/// voltage magnitude of both sides is the same. The difference voltage magnitude
	/// is the base in an equal-sided triangle where the sides corresponds to the
	/// primary and secondary voltages. The phase angle difference corresponds to the
	/// top angle and can be expressed as twice the arctangent of half the total
	/// difference voltage.
	/// </summary>
	public class PhaseTapChangerSymmetrical : PhaseTapChangerNonLinear {

		/// <summary>
		/// Initializes a new instance of the <see cref="PhaseTapChangerSymmetrical"/> class
		/// </summary>
		public PhaseTapChangerSymmetrical(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PhaseTapChangerSymmetrical

}//end namespace Wires