///////////////////////////////////////////////////////////
//  PhaseTapChanger.cs
//  Implementation of the Class PhaseTapChanger
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A transformer phase shifting tap model that controls the phase angle difference
	/// across the power transformer and potentially the active power flow through the
	/// power transformer.  This phase tap model may also impact the voltage magnitude.
	/// 
	/// </summary>
	public class PhaseTapChanger : TapChanger {

		/// <summary>
		/// Initializes a new instance of the <see cref="PhaseTapChanger"/> class
		/// </summary>
		public PhaseTapChanger(){

		}

		~PhaseTapChanger(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end PhaseTapChanger

}//end namespace Wires