///////////////////////////////////////////////////////////
//  PhaseTapChangerTable.cs
//  Implementation of the Class PhaseTapChangerTable
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Describes a tabular curve for how the phase angle difference and impedance
	/// varies with the tap step.
	/// </summary>
	public class PhaseTapChangerTable : IdentifiedObject {

		/// <summary>
		/// The phase tap changers to which this phase tap table applies.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.PhaseTapChangerTabular? PhaseTapChangerTabular;

		/// <summary>
		/// Initializes a new instance of the <see cref="PhaseTapChangerTable"/> class
		/// </summary>
		public PhaseTapChangerTable(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PhaseTapChangerTable

}//end namespace Wires
