///////////////////////////////////////////////////////////
//  Plant.cs
//  Implementation of the Class Plant
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:13 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A Plant is a collection of equipment for purposes of generation.
	/// </summary>
	public class Plant : EquipmentContainer {

		/// <summary>
		/// Initializes a new instance of the <see cref="Plant"/> class
		/// </summary>
		public Plant(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Plant

}//end namespace Wires
