///////////////////////////////////////////////////////////
//  ProtectedSwitch.cs
//  Implementation of the Class ProtectedSwitch
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:16 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A ProtectedSwitch is a switching device that can be operated by
	/// ProtectionEquipment.
	/// </summary>
	public class ProtectedSwitch : Switch {

		/// <summary>
		/// The maximum fault current a breaking device can break safely under prescribed
		/// conditions of use.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow breakingCapacity;
		/// <summary>
		/// A breaker may have zero or more automatic reclosures after a trip occurs.
		/// </summary>
		public TC57CIM.IEC61970.Base.Protection.RecloseSequence RecloseSequences;

		/// <summary>
		/// Initializes a new instance of the <see cref="ProtectedSwitch"/> class
		/// </summary>
		public ProtectedSwitch(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ProtectedSwitch

}//end namespace Wires