///////////////////////////////////////////////////////////
//  RatioTapChangerTablePoint.cs
//  Implementation of the Class RatioTapChangerTablePoint
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:18 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Describes each tap step in the ratio tap changer tabular curve.
	/// </summary>
	public class RatioTapChangerTablePoint : TapChangerTablePoint {

		/// <summary>
		/// Table of this point.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.RatioTapChangerTable RatioTapChangerTable;

		/// <summary>
		/// Initializes a new instance of the <see cref="RatioTapChangerTablePoint"/> class
		/// </summary>
		public RatioTapChangerTablePoint(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end RatioTapChangerTablePoint

}//end namespace Wires