///////////////////////////////////////////////////////////
//  Recloser.cs
//  Implementation of the Class Recloser
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:18 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Pole-mounted fault interrupter with built-in phase and ground relays, current
	/// transformer (CT), and supplemental controls.
	/// </summary>
	public class Recloser : ProtectedSwitch {

		/// <summary>
		/// Initializes a new instance of the <see cref="Recloser"/> class
		/// </summary>
		public Recloser(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Recloser

}//end namespace Wires
