///////////////////////////////////////////////////////////
//  Sectionaliser.cs
//  Implementation of the Class Sectionaliser
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Automatic switch that will lock open to isolate a faulted section. It may, or
	/// may not, have load breaking capability. Its primary purpose is to provide fault
	/// sectionalising at locations where the fault current is either too high, or too
	/// low, for proper coordination of fuses.
	/// </summary>
	public class Sectionaliser : Switch {

		/// <summary>
		/// Initializes a new instance of the <see cref="Sectionaliser"/> class
		/// </summary>
		public Sectionaliser(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Sectionaliser

}//end namespace Wires
