///////////////////////////////////////////////////////////
//  SwitchSchedule.cs
//  Implementation of the Class SwitchSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:24 AM
//  Original author: KLH
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.LoadModel;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A schedule of switch positions.  If RegularTimePoint.value1 is 0, the switch is
	/// open.  If 1, the switch is closed.
	/// </summary>
	public class SwitchSchedule : SeasonDayTypeSchedule {

		/// <summary>
		/// Initializes a new instance of the <see cref="SwitchSchedule"/> class
		/// </summary>
		public SwitchSchedule(){

		}

		~SwitchSchedule(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end SwitchSchedule

}//end namespace Wires