///////////////////////////////////////////////////////////
//  VoltageControlZone.cs
//  Implementation of the Class VoltageControlZone
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// An area of the power system network which is defined for secondary voltage
	/// control purposes. A voltage control zone consists of a collection of
	/// substations with a designated bus bar section whose voltage will be controlled.
	///
	/// </summary>
	public class VoltageControlZone : PowerSystemResource {

		/// <summary>
		/// Initializes a new instance of the <see cref="VoltageControlZone"/> class
		/// </summary>
		public VoltageControlZone(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end VoltageControlZone

}//end namespace Wires