///////////////////////////////////////////////////////////
//  WireSegment.cs
//  Implementation of the Class WireSegment
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:33 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A two terminal and power conducting device of negligible impedance and length
	/// represented as zero impedance device that can be used to connect auxiliary
	/// equipment to its terminals.
	/// </summary>
	public class WireSegment : Conductor {

		/// <summary>
		/// Initializes a new instance of the <see cref="WireSegment"/> class
		/// </summary>
		public WireSegment(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WireSegment

}//end namespace Wires
