///////////////////////////////////////////////////////////
//  EquivalentShunt.cs
//  Implementation of the Class EquivalentShunt
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:51 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Equivalents {
	/// <summary>
	/// The class represents equivalent shunts.
	/// </summary>
	public class EquivalentShunt : EquivalentEquipment {

		/// <summary>
		/// Positive sequence shunt susceptance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Susceptance? b;
		/// <summary>
		/// Positive sequence shunt conductance.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Conductance? g;

		/// <summary>
		/// Initializes a new instance of the <see cref="EquivalentShunt"/> class
		/// </summary>
		public EquivalentShunt(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end EquivalentShunt

}//end namespace Equivalents
