///////////////////////////////////////////////////////////
//  BlockingFunction.cs
//  Implementation of the Class BlockingFunction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	/// <summary>
	/// The blocking function class
	/// </summary>
	public class BlockingFunction {

		/// <summary>
		/// The vs ctype
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1 VSCtype1;

		/// <summary>
		/// Initializes a new instance of the <see cref="BlockingFunction"/> class
		/// </summary>
		public BlockingFunction(){

		}

		~BlockingFunction(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end BlockingFunction

}//end namespace VSC