///////////////////////////////////////////////////////////
//  BlockingFunction.cs
//  Implementation of the Class BlockingFunction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	public class BlockingFunction {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1 VSCtype1;

		public BlockingFunction(){

		}

		~BlockingFunction(){

		}

		public virtual void Dispose(){

		}

	}//end BlockingFunction

}//end namespace VSC