///////////////////////////////////////////////////////////
//  PFmode.cs
//  Implementation of the Class PFmode
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	/// <summary>
	/// The fmode class
	/// </summary>
	public class PFmode {

		/// <summary>
		/// The vs ctype
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1 VSCtype1;

		/// <summary>
		/// Initializes a new instance of the <see cref="PFmode"/> class
		/// </summary>
		public PFmode(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end PFmode

}//end namespace VSC