///////////////////////////////////////////////////////////
//  Umode.cs
//  Implementation of the Class Umode
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:27 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	/// <summary>
	/// The umode class
	/// </summary>
	public class Umode {

		/// <summary>
		/// The vs ctype
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.VSCtype1? VSCtype1;

		/// <summary>
		/// Initializes a new instance of the <see cref="Umode"/> class
		/// </summary>
		public Umode(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Umode

}//end namespace VSC
