///////////////////////////////////////////////////////////
//  VSCtype1.cs
//  Implementation of the Class VSCtype1
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	/// <summary>
	/// The vs ctype class
	/// </summary>
	/// <seealso cref="VSCDynamics"/>
	public class VSCtype1 : VSCDynamics {

		/// <summary>
		/// The cvoltage control
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.DCvoltageControl? DCvoltageControl;

		/// <summary>
		/// Initializes a new instance of the <see cref="VSCtype1"/> class
		/// </summary>
		public VSCtype1(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end VSCtype1

}//end namespace VSC
