///////////////////////////////////////////////////////////
//  BusinessPlan.cs
//  Implementation of the Class BusinessPlan
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// A BusinessPlan is an organized sequence of predetermined actions required to
	/// complete a future organizational objective. It is a type of document that
	/// typically references a schedule, physical and/or logical resources (assets
	/// and/or PowerSystemResources), locations, etc.
	/// </summary>
	public class BusinessPlan : Document {

		/// <summary>
		/// Initializes a new instance of the <see cref="BusinessPlan"/> class
		/// </summary>
		public BusinessPlan(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end BusinessPlan

}//end namespace InfCommon
