///////////////////////////////////////////////////////////
//  BusinessRole.cs
//  Implementation of the Class BusinessRole
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// A business role that this organisation plays. A single organisation typically
	/// performs many functions, each one described as a role.
	/// </summary>
	public class BusinessRole : OrganisationRole {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// Classification by utility's corporate standards and practices.
		/// </summary>
		public string type;

		/// <summary>
		/// Initializes a new instance of the <see cref="BusinessRole"/> class
		/// </summary>
		public BusinessRole(){

		}

		~BusinessRole(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end BusinessRole

}//end namespace InfCommon