///////////////////////////////////////////////////////////
//  PropertyOrganisationRole.cs
//  Implementation of the Class PropertyOrganisationRole
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:21 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// Role an organisation plays with respect to property (for example, the
	/// organisation may be the owner, renter, occupier, taxiing authority, etc.).
	/// </summary>
	public class PropertyOrganisationRole : OrganisationRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="PropertyOrganisationRole"/> class
		/// </summary>
		public PropertyOrganisationRole(){

		}

		~PropertyOrganisationRole(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end PropertyOrganisationRole

}//end namespace InfCommon