///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Class Role
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:23 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// Enumeration of potential roles that might be played by one object relative to
	/// another.
	/// </summary>
	public class Role : IdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status? status;
		/// <summary>
		/// Type of role.
		/// </summary>
		public string? type;

		/// <summary>
		/// Initializes a new instance of the <see cref="Role"/> class
		/// </summary>
		public Role(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Role

}//end namespace InfCommon
