///////////////////////////////////////////////////////////
//  SkillLevelKind.cs
//  Implementation of the Class SkillLevelKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfCommon {
	/// <summary>
	/// Kind of skill level.
	/// </summary>
	public enum SkillLevelKind : int {

		/// <summary>
		/// The master skill level kind
		/// </summary>
		master,
		/// <summary>
		/// The standard skill level kind
		/// </summary>
		standard,
		/// <summary>
		/// The apprentice skill level kind
		/// </summary>
		apprentice,
		/// <summary>
		/// The other skill level kind
		/// </summary>
		other

	}//end SkillLevelKind

}//end namespace InfCommon
