///////////////////////////////////////////////////////////
//  AnnotatedProjectDependency.cs
//  Implementation of the Class AnnotatedProjectDependency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:40 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	   /// <summary>
	   /// Represents a dependency between project stages with annotation of dependency kind.
	   /// </summary>
	   public class AnnotatedProjectDependency : IdentifiedObject {

			   /// <summary>
			   /// The type of dependency.
			   /// </summary>
			   public DependencyKind? dependencyType;
			   /// <summary>
			   /// The stage this dependency depends on.
			   /// </summary>
			   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects.NetworkModelProjectStage? DependentOnStage;
			   /// <summary>
			   /// The stage that is depending on another stage.
			   /// </summary>
			   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects.NetworkModelProjectStage? DependingStage;

			   /// <summary>
			   /// Initializes a new instance of the <see cref="AnnotatedProjectDependency"/> class.
			   /// </summary>
			   public AnnotatedProjectDependency(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="AnnotatedProjectDependency"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end AnnotatedProjectDependency

}//end namespace NetworkModelProjects
