///////////////////////////////////////////////////////////
//  DependencyKind.cs
//  Implementation of the Class DependencyKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:48 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	   /// <summary>
	   /// Enumerates the types of dependencies between network model project stages.
	   /// </summary>
	   public enum DependencyKind : int {
			   /// <summary>
			   /// The projects are mutually exclusive.
			   /// </summary>
			   mutuallyExclusive,
			   /// <summary>
			   /// The project is required.
			   /// </summary>
			   required

	   }//end DependencyKind

}//end namespace NetworkModelProjects