///////////////////////////////////////////////////////////
//  NetworkModelProject.cs
//  Implementation of the Class NetworkModelProject
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:09 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	/// <summary>
	/// A grouping of network model change descriptions.  Primarily used to organize
	/// the phases of an overall project.
	/// </summary>
	public class NetworkModelProject : NetworkModelProjectComponent {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="NetworkModelProject"/> class.
	   /// </summary>
	   public NetworkModelProject(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="NetworkModelProject"/> class.
	   /// </summary>
	   ~NetworkModelProject(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="NetworkModelProject"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end NetworkModelProject

}//end namespace NetworkModelProjects