///////////////////////////////////////////////////////////
//  NetworkModelProjectStage.cs
//  Implementation of the Class NetworkModelProjectStage
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:09 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	public class NetworkModelProjectStage : NetworkModelProjectComponent2 {

		public TC57CIM.IEC61970.Base.Domain.Integer changesetVersion;
		public System.DateTime commissionedDate;
		public System.DateTime plannedCommissionedDate;
		public TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet.ChangeSet ChangeSets;

		public NetworkModelProjectStage(){

		}

		~NetworkModelProjectStage(){

		}

		public override void Dispose(){

		}

	}//end NetworkModelProjectStage

}//end namespace NetworkModelProjects