///////////////////////////////////////////////////////////
//  NetworkModelProjectComponent2.cs
//  Implementation of the Class NetworkModelProjectComponent2
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:09 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	   /// <summary>
	   /// Represents a component of a network model project with versioning and state information.
	   /// </summary>
	   public class NetworkModelProjectComponent2 : IdentifiedObject {

			   /// <summary>
			   /// The date the component was closed.
			   /// </summary>
			   public System.DateTime? closed;
			   /// <summary>
			   /// The date the component was created.
			   /// </summary>
			   public System.DateTime? created;
			   /// <summary>
			   /// The date the component was last updated.
			   /// </summary>
			   public System.DateTime? updated;
			   /// <summary>
			   /// The version of the component.
			   /// </summary>
			   public TC57CIM.IEC61970.Base.Domain.Integer? version;
			   /// <summary>
			   /// The current state of the component.
			   /// </summary>
			   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects.CurrentState? m_CurrentState;
			   /// <summary>
			   /// The parent project of this component.
			   /// </summary>
			   public TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects.NetworkModelProject2? Parent;

			   /// <summary>
			   /// Initializes a new instance of the <see cref="NetworkModelProjectComponent2"/> class.
			   /// </summary>
			   public NetworkModelProjectComponent2(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="NetworkModelProjectComponent2"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end NetworkModelProjectComponent2

}//end namespace NetworkModelProjects
