///////////////////////////////////////////////////////////
//  PowerSystemProjectLifecycleToBeDeleted.cs
//  Implementation of the Class PowerSystemProjectLifecycleToBeDeleted
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:14 AM
//  Original author: sveinols
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	/// <summary>
	/// Represent the base lifecycle of a functional model change that could be a
	/// construction of new elements.
	/// </summary>
	public class PowerSystemProjectLifecycleToBeDeleted {

		/// <summary>
		/// The date the Power System Project is in cancelled stage.
		/// </summary>
	   /// <summary>
	   /// The date the Power System Project is in cancelled stage.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Date? cancelled;
	   /// <summary>
	   /// The date Power System Project is in committed stage.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Date? committed;
	   /// <summary>
	   /// The date Power System Project is in build stage.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Date? inBuild;
	   /// <summary>
	   /// The date Power System Project is in planning stage.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Date? inPlan;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="PowerSystemProjectLifecycleToBeDeleted"/> class.
	   /// </summary>
	   public PowerSystemProjectLifecycleToBeDeleted(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="PowerSystemProjectLifecycleToBeDeleted"/> class.
	   /// </summary>
	   ~PowerSystemProjectLifecycleToBeDeleted(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="PowerSystemProjectLifecycleToBeDeleted"/> class.
	   /// </summary>
	   public virtual void Dispose(){

		}

	}//end PowerSystemProjectLifecycleToBeDeleted

}//end namespace NetworkModelProjects