///////////////////////////////////////////////////////////
//  ProjectDependency.cs
//  Implementation of the Class ProjectDependency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	/// <summary>
	/// Project A change sets should be applied before Project B during case creation.
	/// </summary>
	public class ProjectDependency : NetworkModelProjectRelationship {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ProjectDependency"/> class.
	   /// </summary>
	   public ProjectDependency(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="ProjectDependency"/> class.
	   /// </summary>
	   ~ProjectDependency(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="ProjectDependency"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end ProjectDependency

}//end namespace NetworkModelProjects