///////////////////////////////////////////////////////////
//  ProjectStatusKind.cs
//  Implementation of the Class ProjectStatusKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	   /// <summary>
	   /// Enumerates the possible statuses for a network model project.
	   /// </summary>
	   public enum ProjectStatusKind : int {
			   /// <summary>
			   /// The project is in draft status.
			   /// </summary>
			   draft,
			   /// <summary>
			   /// The project is cancelled.
			   /// </summary>
			   cancelled,
			   /// <summary>
			   /// The project is frozen.
			   /// </summary>
			   frozen,
			   /// <summary>
			   /// The project is closed.
			   /// </summary>
			   closed

	   }//end ProjectStatusKind

}//end namespace NetworkModelProjects