///////////////////////////////////////////////////////////
//  ProjectAlternative.cs
//  Implementation of the Class ProjectAlternative
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelProjects {
	/// <summary>
	/// Project B is an alternative to project A.  Project A is the primary alternative.
	///
	/// Multiple project alternatives should not be selected into a single network
	/// study case.
	/// </summary>
	public class ProjectAlternative : NetworkModelProjectRelationship {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ProjectAlternative"/> class.
	   /// </summary>
	   public ProjectAlternative(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="ProjectAlternative"/> class.
	   /// </summary>
	   ~ProjectAlternative(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="ProjectAlternative"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end ProjectAlternative

}//end namespace NetworkModelProjects