///////////////////////////////////////////////////////////
//  EquipmentLimitSeriesComponent.cs
//  Implementation of the Class EquipmentLimitSeriesComponent
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:51 AM
//  Original author: akamath
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;

namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// This represents one instance of an equipment that contributes to the calculation of an operational limit.
   /// </summary>
   public class EquipmentLimitSeriesComponent : IdentifiedObject {

	  /// <summary>
	  /// Equipment contributing toward the series limit. The reference here is to Equipment rather than a specific limit on the equipment so the grouping can be reused for multiple limits of different types on the same instance of equipment.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.Core.Equipment? Equipment;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="EquipmentLimitSeriesComponent"/> class.
	   /// </summary>
	   public EquipmentLimitSeriesComponent(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="EquipmentLimitSeriesComponent"/> class.
	   /// </summary>
	   ~EquipmentLimitSeriesComponent(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="EquipmentLimitSeriesComponent"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end EquipmentLimitSeriesComponent

}//end namespace InfOperationalLimits