///////////////////////////////////////////////////////////
//  LimitDependency.cs
//  Implementation of the Class LimitDependency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
//  Original author: akamath
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;

namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// A limit calculation model used to compute an operational limit based on external input such as temperature. These are intended to be shared among operational limits with the same calculation form that apply to a piece of equipment.
   /// </summary>
   public class LimitDependency : IdentifiedObject {

	   /// <summary>
	   /// Initializes a new instance of the <see cref="LimitDependency"/> class.
	   /// </summary>
	   public LimitDependency(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="LimitDependency"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end LimitDependency

}//end namespace InfOperationalLimits
