///////////////////////////////////////////////////////////
//  OperatonalLimitTypeScaling.cs
//  Implementation of the Class OperatonalLimitTypeScaling
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:11 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////


namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// Represents scaling between two operational limit types within the same set.
   /// </summary>
   public class OperatonalLimitTypeScaling {

	  /// <summary>
	  /// The percentage scaling of the source limit to compute the target limit. Applies to operational limits within an operational limit set when both source and target operational limit types exist.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.Domain.PerCent? scalingPercent;

	  /// <summary>
	  /// The source operational limit type.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimitType? SourceOperationalLimitType;

	  /// <summary>
	  /// The target operational limit type.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimitType? TargetOperationalLimit;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="OperatonalLimitTypeScaling"/> class.
	   /// </summary>
	   public OperatonalLimitTypeScaling(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="OperatonalLimitTypeScaling"/> class.
    /// </summary>
    public virtual void Dispose(){

		}

	}//end OperatonalLimitTypeScaling

}//end namespace InfOperationalLimits