///////////////////////////////////////////////////////////
//  ScheduledLimitValue.cs
//  Implementation of the Class ScheduledLimitValue
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;

namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// A limit that is applicable during a scheduled time period.
   /// </summary>
   public class ScheduledLimitValue : IdentifiedObject {

	  /// <summary>
	  /// The season for which the scheduled limits applies. If not specified, then applicable to any season.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.LoadModel.Season? Season;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ScheduledLimitValue"/> class.
	   /// </summary>
	   public ScheduledLimitValue(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="ScheduledLimitValue"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end ScheduledLimitValue

}//end namespace InfOperationalLimits