///////////////////////////////////////////////////////////
//  ScheduledActivePowerLimitValue.cs
//  Implementation of the Class ScheduledActivePowerLimitValue
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////


namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// A scheduled value for active power limit at a specific time.
   /// </summary>
   public class ScheduledActivePowerLimitValue : ScheduledLimitValue {

	  /// <summary>
	  /// The active power limit value for the scheduled time.
	  /// </summary>
	  public TC57CIM.IEC61970.Base.Domain.ActivePower? value;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="ScheduledActivePowerLimitValue"/> class.
	   /// </summary>
	   public ScheduledActivePowerLimitValue(){

		}

	   /// <summary>
	   /// Finalizes an instance of the <see cref="ScheduledActivePowerLimitValue"/> class.
	   /// </summary>
	   ~ScheduledActivePowerLimitValue(){

		}

	   /// <summary>
	   /// Releases resources used by the <see cref="ScheduledActivePowerLimitValue"/> class.
	   /// </summary>
	   public override void Dispose(){

		}

	}//end ScheduledActivePowerLimitValue

}//end namespace InfOperationalLimits