///////////////////////////////////////////////////////////
//  TemperatureDependentLimitPoint.cs
//  Implementation of the Class TemperatureDependentLimitPoint
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:25 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
	/// <summary>
	/// A point on a table of limit verses temperature.
	/// </summary>
	public class TemperatureDependentLimitPoint {


	   /// <summary>
	   /// The scaling of the operational limit in percent.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.PerCent? limitPercent;

	   /// <summary>
	   /// The temperature of the table point.
	   /// </summary>
	   public TC57CIM.IEC61970.Base.Domain.Temperature? temperature;


	   /// <summary>
	   /// Initializes a new instance of the <see cref="TemperatureDependentLimitPoint"/> class.
	   /// </summary>
	   public TemperatureDependentLimitPoint(){

		}


    /// <summary>
    /// Releases resources used by the <see cref="TemperatureDependentLimitPoint"/> class.
    /// </summary>
    public virtual void Dispose(){

		}

	}//end TemperatureDependentLimitPoint

}//end namespace InfOperationalLimits