///////////////////////////////////////////////////////////
//  TemperatureDependentLimitTable.cs
//  Implementation of the Class TemperatureDependentLimitTable
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:25 AM
//  Original author: akamath
///////////////////////////////////////////////////////////


namespace TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits {
   /// <summary>
   /// This is a table lookup that provides limit values corresponding to a temperature input.
   /// </summary>
   public class TemperatureDependentLimitTable : EnvironmentalDependentLimit {

	  /// <summary>
	  /// The temperature limit table point for this table.
	  /// </summary>
	  public TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits.TemperatureDependentLimitPoint? TemperatureLimitTablePoint;

	   /// <summary>
	   /// Initializes a new instance of the <see cref="TemperatureDependentLimitTable"/> class.
	   /// </summary>
	   public TemperatureDependentLimitTable(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="TemperatureDependentLimitTable"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end TemperatureDependentLimitTable

}//end namespace InfOperationalLimits