///////////////////////////////////////////////////////////
//  Sensor.cs
//  Implementation of the Class Sensor
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.AuxiliaryEquipment {
	/// <summary>
	/// This class describe devices that transform a measured quantity into signals
	/// that can be presented at displays, used in control or be recorded.
	/// </summary>
	public class Sensor : AuxiliaryEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="Sensor"/> class
		/// </summary>
		public Sensor(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Sensor

}//end namespace AuxiliaryEquipment
