///////////////////////////////////////////////////////////
//  SurgeArrester.cs
//  Implementation of the Class SurgeArrester
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.AuxiliaryEquipment {
	/// <summary>
	/// Shunt device, installed on the network, usually in the proximity of electrical
	/// equipment in order to protect the said equipment against transient voltage
	/// transients caused by lightning or switching activity.
	/// </summary>
	public class SurgeArrester : AuxiliaryEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="SurgeArrester"/> class
		/// </summary>
		public SurgeArrester(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end SurgeArrester

}//end namespace AuxiliaryEquipment
