///////////////////////////////////////////////////////////
//  WaveTrap.cs
//  Implementation of the Class WaveTrap
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:30 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.AuxiliaryEquipment {
	/// <summary>
	/// Line traps are devices that impede high frequency power line carrier signals
	/// yet present a negligible impedance at the main power frequency.
	/// </summary>
	public class WaveTrap : AuxiliaryEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="WaveTrap"/> class
		/// </summary>
		public WaveTrap(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WaveTrap

}//end namespace AuxiliaryEquipment
