///////////////////////////////////////////////////////////
//  InstanceSet.cs
//  Implementation of the Class InstanceSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet {
	/// <summary>
	/// Instance of a version of a model part.   This corresponds to a payload of
	/// instance data.
	/// </summary>
	public class InstanceSet : DataSet {

		public InstanceSet(){

		}

		~InstanceSet(){

		}

		public override void Dispose(){

		}

	}//end InstanceSet

}//end namespace GenericDataSet