///////////////////////////////////////////////////////////
//  ObjectDeletion.cs
//  Implementation of the Class ObjectDeletion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.Part303.GenericDataSet {
	/// <summary>
	/// An object is to be deleted in the context.
	/// </summary>
	public class ObjectDeletion : ChangeSetMember {

		public ObjectDeletion(){

		}

		~ObjectDeletion(){

		}

		public override void Dispose(){

		}

	}//end ObjectDeletion

}//end namespace GenericDataSet