///////////////////////////////////////////////////////////
//  HVDCDynamics.cs
//  Implementation of the Class HVDCDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics {
	/// <summary>
	/// HVDC whose behaviour is described by reference to a standard model <font
	/// color="#0f0f0f">or by definition of a user-defined model.</font>
	/// </summary>
	public class HVDCDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Initializes a new instance of the <see cref="HVDCDynamics"/> class
		/// </summary>
		public HVDCDynamics(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end HVDCDynamics

}//end namespace HVDCDynamics
