///////////////////////////////////////////////////////////
//  Joint.cs
//  Implementation of the Class Joint
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Joint connects two or more cables. It includes the portion of cable under wipes,
	/// welds, or other seals.
	/// </summary>
	public class Joint : Asset {

		/// <summary>
		/// Configuration of joint.
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.JointConfigurationKind configurationKind;
		/// <summary>
		/// Material used to fill the joint.
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.JointFillKind fillKind;
		/// <summary>
		/// The type of insulation around the joint, classified according to the utility's
		/// asset management standards and practices.
		/// </summary>
		public string insulation;

		public Joint(){

		}

		~Joint(){

		}

		public override void Dispose(){

		}

	}//end Joint

}//end namespace Assets