///////////////////////////////////////////////////////////
//  PowerSystemStabilizerDynamics.cs
//  Implementation of the Class PowerSystemStabilizerDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.PowerSystemStabilizerDynamics {
	/// <summary>
	/// Power system stabilizer function block whose behaviour is described by
	/// reference to a standard model <font color="#0f0f0f">or by definition of a user-
	/// defined model.</font>
	/// </summary>
	public class PowerSystemStabilizerDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Excitation system model with which this power system stabilizer model is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics ExcitationSystemDynamics;
		/// <summary>
		/// Remote input signal used by this power system stabilizer model.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal RemoteInputSignal;

		/// <summary>
		/// Initializes a new instance of the <see cref="PowerSystemStabilizerDynamics"/> class
		/// </summary>
		public PowerSystemStabilizerDynamics(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PowerSystemStabilizerDynamics

}//end namespace PowerSystemStabilizerDynamics