///////////////////////////////////////////////////////////
//  DERGroupDispatch.cs
//  Implementation of the Class DERGroupDispatch
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:04 AM
//  Original author: Margaret
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.DER {
	/// <summary>
	/// Specifies the capabilities of the DER Group that are to be dispatched according
	/// to a schedule.  Each dispatch identifies a DER Group and the specific
	/// monitorable parameter to be dispatched over a specific time interval.
	/// </summary>
	public class DERGroupDispatch : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="DERGroupDispatch"/> class
		/// </summary>
		public DERGroupDispatch(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DERGroupDispatch

}//end namespace DER