///////////////////////////////////////////////////////////
//  DERGroupForecast.cs
//  Implementation of the Class DERGroupForecast
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:04 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.DER {
	/// <summary>
	/// Specifies the forecasted values of the DERMonitorableParameters for a DER Group
	/// over a specific time interval.
	/// </summary>
	public class DERGroupForecast : IdentifiedObject {

		/// <summary>
		/// The timestamp for when the DER Group forecast was created
		/// </summary>
		public System.DateTime? predictionCreationDate;
		/// <summary>
		/// The DER Group for which forecasts are made.
		/// </summary>
		public TC57CIM.IEC61968.Metering.EndDeviceGroup? EndDeviceGroup;

		/// <summary>
		/// Initializes a new instance of the <see cref="DERGroupForecast"/> class
		/// </summary>
		public DERGroupForecast(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DERGroupForecast

}//end namespace DER
