///////////////////////////////////////////////////////////
//  BreakerInfo.cs
//  Implementation of the Class BreakerInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Properties of breaker assets.
	/// </summary>
	public class BreakerInfo : OldSwitchInfo {

		/// <summary>
		/// Phase trip rating.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow? phaseTrip;

		/// <summary>
		/// Initializes a new instance of the <see cref="BreakerInfo"/> class
		/// </summary>
		public BreakerInfo(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end BreakerInfo

}//end namespace InfAssetInfo
