///////////////////////////////////////////////////////////
//  CompositeSwitchKind.cs
//  Implementation of the Class CompositeSwitchKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of composite switch.
	/// </summary>
	public enum CompositeSwitchKind : int {

		/// <summary>
		/// The throw over composite switch kind
		/// </summary>
		throwOver,
		/// <summary>
		/// The esco throw over composite switch kind
		/// </summary>
		escoThrowOver,
		/// <summary>
		/// The ral composite switch kind
		/// </summary>
		ral,
		/// <summary>
		/// The gral composite switch kind
		/// </summary>
		gral,
		/// <summary>
		/// The regulator bypass composite switch kind
		/// </summary>
		regulatorBypass,
		/// <summary>
		/// The ug multi switch composite switch kind
		/// </summary>
		ugMultiSwitch,
		/// <summary>
		/// The other composite switch kind
		/// </summary>
		other

	}//end CompositeSwitchKind

}//end namespace InfAssetInfo