///////////////////////////////////////////////////////////
//  FaultIndicatorResetKind.cs
//  Implementation of the Class FaultIndicatorResetKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:11 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of resetting the fault indicators.
	/// </summary>
	public enum FaultIndicatorResetKind : int {

		/// <summary>
		/// The automatic fault indicator reset kind
		/// </summary>
		automatic,
		/// <summary>
		/// The manual fault indicator reset kind
		/// </summary>
		manual,
		/// <summary>
		/// The remote fault indicator reset kind
		/// </summary>
		remote,
		/// <summary>
		/// The other fault indicator reset kind
		/// </summary>
		other

	}//end FaultIndicatorResetKind

}//end namespace InfAssetInfo