///////////////////////////////////////////////////////////
//  FaultIndicatorInfo.cs
//  Implementation of the Class FaultIndicatorInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:11 AM
///////////////////////////////////////////////////////////

using Assets = TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Parameters of fault indicator asset.
	/// </summary>
	public class FaultIndicatorInfo : Assets.AssetInfo {

		/// <summary>
		/// Kind of reset mechanisim of this fault indicator.
		/// </summary>
		public FaultIndicatorResetKind resetKind;

		/// <summary>
		/// Initializes a new instance of the <see cref="FaultIndicatorInfo"/> class
		/// </summary>
		public FaultIndicatorInfo(){

		}

		~FaultIndicatorInfo(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end FaultIndicatorInfo

}//end namespace InfAssetInfo