///////////////////////////////////////////////////////////
//  OilPreservationKind.cs
//  Implementation of the Class OilPreservationKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of oil preservation.
	/// </summary>
	public enum OilPreservationKind : int {

		/// <summary>
		/// The free breathing oil preservation kind
		/// </summary>
		freeBreathing,
		/// <summary>
		/// The nitrogen blanket oil preservation kind
		/// </summary>
		nitrogenBlanket,
		/// <summary>
		/// The conservator oil preservation kind
		/// </summary>
		conservator,
		/// <summary>
		/// The other oil preservation kind
		/// </summary>
		other

	}//end OilPreservationKind

}//end namespace InfAssetInfo
