///////////////////////////////////////////////////////////
//  OldTransformerEndInfo.cs
//  Implementation of the Class OldTransformerEndInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61968.AssetInfo;
namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// The old transformer end info class
	/// </summary>
	/// <seealso cref="TransformerEndInfo"/>
	public class OldTransformerEndInfo : TransformerEndInfo {

		/// <summary>
		/// Overload rating for 24 hours.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ApparentPower dayOverLoadRating;
		/// <summary>
		/// Overload rating for 1 hour.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ApparentPower hourOverLoadRating;
		/// <summary>
		/// Weight of solid insultation in transformer.
		/// </summary>
		public Mass solidInsulationWeight;
		/// <summary>
		/// Type of insultation used for transformer windings.
		/// </summary>
		public WindingInsulationKind windingInsulationKind;

		/// <summary>
		/// Initializes a new instance of the <see cref="OldTransformerEndInfo"/> class
		/// </summary>
		public OldTransformerEndInfo(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OldTransformerEndInfo

}//end namespace InfAssetInfo