///////////////////////////////////////////////////////////
//  RegulationBranchKind.cs
//  Implementation of the Class RegulationBranchKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of regulation branch for shunt impedance.
	/// </summary>
	public enum RegulationBranchKind : int {

		/// <summary>
		/// The line regulation branch kind
		/// </summary>
		line,
		/// <summary>
		/// The transformer regulation branch kind
		/// </summary>
		transformer,
		/// <summary>
		/// The switch regulation branch kind
		/// </summary>
		switch_,
		/// <summary>
		/// The breaker regulation branch kind
		/// </summary>
		breaker,
		/// <summary>
		/// The recloser regulation branch kind
		/// </summary>
		recloser,
		/// <summary>
		/// The fuse regulation branch kind
		/// </summary>
		fuse,
		/// <summary>
		/// The sectionner regulation branch kind
		/// </summary>
		sectionner,
		/// <summary>
		/// The other regulation branch kind
		/// </summary>
		other

	}//end RegulationBranchKind

}//end namespace InfAssetInfo