///////////////////////////////////////////////////////////
//  ShuntImpedanceControlKind.cs
//  Implementation of the Class ShuntImpedanceControlKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of control for shunt impedance.
	/// </summary>
	public enum ShuntImpedanceControlKind : int {

		/// <summary>
		/// The fixed shunt impedance control kind
		/// </summary>
		fixed_,
		/// <summary>
		/// The local only shunt impedance control kind
		/// </summary>
		localOnly,
		/// <summary>
		/// The remote only shunt impedance control kind
		/// </summary>
		remoteOnly,
		/// <summary>
		/// The remote with local override shunt impedance control kind
		/// </summary>
		remoteWithLocalOverride

	}//end ShuntImpedanceControlKind

}//end namespace InfAssetInfo
