///////////////////////////////////////////////////////////
//  TransformerCoreKind.cs
//  Implementation of the Class TransformerCoreKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:28 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfAssetInfo {
	/// <summary>
	/// Kind of transformer construction.
	/// </summary>
	public enum TransformerCoreKind : int {

		/// <summary>
		/// The core transformer core kind
		/// </summary>
		core,
		/// <summary>
		/// The shell transformer core kind
		/// </summary>
		shell

	}//end TransformerCoreKind

}//end namespace InfAssetInfo