///////////////////////////////////////////////////////////
//  LoadBreakSwitch.cs
//  Implementation of the Class LoadBreakSwitch
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A mechanical switching device capable of making, carrying, and breaking
	/// currents under normal operating conditions.
	/// </summary>
	public class LoadBreakSwitch : ProtectedSwitch {

		public LoadBreakSwitch(){

		}

		~LoadBreakSwitch(){

		}

		public override void Dispose(){

		}

	}//end LoadBreakSwitch

}//end namespace Wires