///////////////////////////////////////////////////////////
//  DCBreaker.cs
//  Implementation of the Class DCBreaker
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// A breaker within a DC system.
	/// </summary>
	public class DCBreaker : DCSwitch {

		/// <summary>
		/// Initializes a new instance of the <see cref="DCBreaker"/> class
		/// </summary>
		public DCBreaker(){

		}

		~DCBreaker(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end DCBreaker

}//end namespace DC