///////////////////////////////////////////////////////////
//  DCBusbar.cs
//  Implementation of the Class DCBusbar
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// A busbar within a DC system.
	/// </summary>
	public class DCBusbar : DCConductingEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="DCBusbar"/> class
		/// </summary>
		public DCBusbar(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DCBusbar

}//end namespace DC