///////////////////////////////////////////////////////////
//  DCChopper.cs
//  Implementation of the Class DCChopper
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// Low resistance equipment used in the internal DC circuit to balance voltages.
	/// It has typically positive and negative pole terminals and a ground.
	/// </summary>
	public class DCChopper : DCConductingEquipment {

		/// <summary>
		/// Initializes a new instance of the <see cref="DCChopper"/> class
		/// </summary>
		public DCChopper(){

		}

		~DCChopper(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end DCChopper

}//end namespace DC