///////////////////////////////////////////////////////////
//  DCDisconnector.cs
//  Implementation of the Class DCDisconnector
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// A disconnector within a DC system.
	/// </summary>
	public class DCDisconnector : DCSwitch {

		public DCDisconnector(){

		}

		~DCDisconnector(){

		}

		public override void Dispose(){

		}

	}//end DCDisconnector

}//end namespace DC