///////////////////////////////////////////////////////////
//  DCEquipmentContainer.cs
//  Implementation of the Class DCEquipmentContainer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// A modelling construct to provide a root class for containment of DC as well as
	/// AC equipment. The class differ from the EquipmentContaner for AC in that it may
	/// also contain DCNode-s. Hence it can contain both AC and DC equipment.
	/// </summary>
	public class DCEquipmentContainer : EquipmentContainer {

		/// <summary>
		/// The topological nodes which belong to this connectivity node container.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCTopologicalNode? DCTopologicalNode;

		/// <summary>
		/// Initializes a new instance of the <see cref="DCEquipmentContainer"/> class
		/// </summary>
		public DCEquipmentContainer(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DCEquipmentContainer

}//end namespace DC
