///////////////////////////////////////////////////////////
//  DCLine.cs
//  Implementation of the Class DCLine
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// Overhead lines and/or cables connecting two or more HVDC substations.
	/// </summary>
	public class DCLine : DCEquipmentContainer {

		/// <summary>
		/// The SubGeographicalRegion containing the DC line.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.SubGeographicalRegion Region;

		/// <summary>
		/// Initializes a new instance of the <see cref="DCLine"/> class
		/// </summary>
		public DCLine(){

		}

		~DCLine(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end DCLine

}//end namespace DC