///////////////////////////////////////////////////////////
//  DCTerminal.cs
//  Implementation of the Class DCTerminal
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// An electrical connection point to generic DC conducting equipment.
	/// </summary>
	public class DCTerminal : DCBaseTerminal {

		/// <summary>
		/// Initializes a new instance of the <see cref="DCTerminal"/> class
		/// </summary>
		public DCTerminal(){

		}

		~DCTerminal(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end DCTerminal

}//end namespace DC