///////////////////////////////////////////////////////////
//  DCTopologicalNode.cs
//  Implementation of the Class DCTopologicalNode
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// DC bus.
	/// </summary>
	public class DCTopologicalNode : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="DCTopologicalNode"/> class
		/// </summary>
		public DCTopologicalNode(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DCTopologicalNode

}//end namespace DC