///////////////////////////////////////////////////////////
//  VsCapabilityCurve.cs
//  Implementation of the Class VsCapabilityCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.DC {
	/// <summary>
	/// The P-Q capability curve for a voltage source converter, with P on X-axis and
	/// Qmin and Qmax on Y1-axis and Y2-axis.
	/// </summary>
	public class VsCapabilityCurve : Curve {

		/// <summary>
		/// Initializes a new instance of the <see cref="VsCapabilityCurve"/> class
		/// </summary>
		public VsCapabilityCurve(){

		}

		~VsCapabilityCurve(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end VsCapabilityCurve

}//end namespace DC