///////////////////////////////////////////////////////////
//  ModelFrameType.cs
//  Implementation of the Class ModelFrameType
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfPart303.NetworkModelFrames.unused {
	/// <summary>
	/// Examples would be "Boundary" or "Region" type of frame.
	/// </summary>
	public class ModelFrameType : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="ModelFrameType"/> class
		/// </summary>
		public ModelFrameType(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ModelFrameType

}//end namespace unused
