///////////////////////////////////////////////////////////
//  VoltageAdjusterDynamics.cs
//  Implementation of the Class VoltageAdjusterDynamics
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.VoltageAdjusterDynamics {
	/// <summary>
	/// Voltage adjuster function block whose behaviour is described by reference to a
	/// standard model <font color="#0f0f0f">or by definition of a user-defined model.
	/// </font>
	/// </summary>
	public class VoltageAdjusterDynamics : DynamicsFunctionBlock {

		/// <summary>
		/// Power factor or VAr controller type 1 model with which this voltage adjuster is
		/// associated.
		/// </summary>
		public TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType1Dynamics.PFVArControllerType1Dynamics? PFVArControllerType1Dynamics;

		/// <summary>
		/// Initializes a new instance of the <see cref="VoltageAdjusterDynamics"/> class
		/// </summary>
		public VoltageAdjusterDynamics(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end VoltageAdjusterDynamics

}//end namespace VoltageAdjusterDynamics
