///////////////////////////////////////////////////////////
//  ClampAction.cs
//  Implementation of the Class ClampAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Action on Clamp as a switching step
	/// </summary>
	public class ClampAction : SwitchingAction {

		/// <summary>
		/// Switching action to perform
		/// </summary>
		public TempEquipActionKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="ClampAction"/> class
		/// </summary>
		public ClampAction(){

		}

		~ClampAction(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ClampAction

}//end namespace Operations