///////////////////////////////////////////////////////////
//  ControlAction.cs
//  Implementation of the Class ControlAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Control executed as a switching step.
	/// </summary>
	public class ControlAction : SwitchingAction {

		/// <summary>
		/// The analog value used for the analog control, the raise/lower control and the
		/// set point control
		/// </summary>
		public float analogValue;
		/// <summary>
		/// The integer value used for the command or the accumulator reset.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer? discreteValue;
		/// <summary>
		/// The control that the control action is performed on.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.Control? Control;

		/// <summary>
		/// Initializes a new instance of the <see cref="ControlAction"/> class
		/// </summary>
		public ControlAction(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ControlAction

}//end namespace Operations
