///////////////////////////////////////////////////////////
//  OperationalUpdatedRating.cs
//  Implementation of the Class OperationalUpdatedRating
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Lowered capability because of deterioration or inadequacy (sometimes referred
	/// to as derating or partial outage) or other kind of operational rating change.
	/// </summary>
	public class OperationalUpdatedRating : OperationalRestriction {

		/// <summary>
		/// Type of operational updated rating, e.g. a derate, a rerate or a return to
		/// normal.
		/// </summary>
		public string changeType;
		/// <summary>
		/// Planned equipment outage with this updated rating.
		/// </summary>
		public TC57CIM.IEC61968.Operations.PlannedOutage PlannedOutage;

		/// <summary>
		/// Initializes a new instance of the <see cref="OperationalUpdatedRating"/> class
		/// </summary>
		public OperationalUpdatedRating(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OperationalUpdatedRating

}//end namespace Operations