///////////////////////////////////////////////////////////
//  PlannedOutageNotification.cs
//  Implementation of the Class PlannedOutageNotification
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:20 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// This class will be used to generate call ahead lists for customers who will be
	/// affected by a planned outage.
	/// </summary>
	public class PlannedOutageNotification : Document {

		/// <summary>
		/// The Usage Point that is specified in the planned outage notification.
		/// </summary>
		public TC57CIM.IEC61968.Metering.UsagePoint UsagePoint;
		/// <summary>
		/// The customer that receives the notification
		/// </summary>
		public TC57CIM.IEC61968.Customers.Customer Customer;
		/// <summary>
		/// The switching plan that contains the planned outage notification.
		/// </summary>
		public TC57CIM.IEC61968.Operations.SwitchingPlan SwitchingPlan;

		/// <summary>
		/// Initializes a new instance of the <see cref="PlannedOutageNotification"/> class
		/// </summary>
		public PlannedOutageNotification(){

		}

		~PlannedOutageNotification(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end PlannedOutageNotification

}//end namespace Operations