///////////////////////////////////////////////////////////
//  ShuntCompensatorAction.cs
//  Implementation of the Class ShuntCompensatorAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:24 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// The shunt compensator action class
	/// </summary>
	/// <seealso cref="SwitchingAction"/>
	public class ShuntCompensatorAction : SwitchingAction {

		/// <summary>
		/// Switching action to perform
		/// </summary>
		public TempEquipActionKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="ShuntCompensatorAction"/> class
		/// </summary>
		public ShuntCompensatorAction(){

		}

		~ShuntCompensatorAction(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ShuntCompensatorAction

}//end namespace Operations