///////////////////////////////////////////////////////////
//  SwitchingEvent.cs
//  Implementation of the Class SwitchingEvent
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:26 AM
//  Original author: Tim Duval
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Event indicating the completion (success or fail) of any switching action
	/// (jumper action, cut action, tag action, etc).  The switching action may or may
	/// not be a consequential event in response to a request to complete the action.
	/// </summary>
	public class SwitchingEvent : ActivityRecord {

		/// <summary>
		/// Initializes a new instance of the <see cref="SwitchingEvent"/> class
		/// </summary>
		public SwitchingEvent(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end SwitchingEvent

}//end namespace Operations
