///////////////////////////////////////////////////////////
//  VerificationAction.cs
//  Implementation of the Class VerificationAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:31 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Operations {
	/// <summary>
	/// Verification of a switch position or other condition as a switching step
	/// </summary>
	public class VerificationAction : SwitchingAction {

		/// <summary>
		/// freeform description of the condition to be verified
		/// </summary>
		public string verificationCondition;
		/// <summary>
		/// The power system resource that the verification action is performed on
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.PowerSystemResource PowerSystemResource;

		/// <summary>
		/// Initializes a new instance of the <see cref="VerificationAction"/> class
		/// </summary>
		public VerificationAction(){

		}

		~VerificationAction(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end VerificationAction

}//end namespace Operations