///////////////////////////////////////////////////////////
//  PFVArType1IEEEVArController.cs
//  Implementation of the Class PFVArType1IEEEVArController
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:12 AM
//  Original author: pcha006
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType1Dynamics {
	/// <summary>
	/// IEEE VAR controller type 1 which operates by moving the voltage reference
	/// directly.
	/// Reference: IEEE 421.5-2005, 11.3.
	/// </summary>
	public class PFVArType1IEEEVArController : PFVArControllerType1Dynamics {

		/// <summary>
		/// Var controller time delay (<i>T</i><i><sub>VARC</sub></i>) (>= 0).  Typical
		/// value = 5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds tvarc;
		/// <summary>
		/// Synchronous machine power factor (<i>V</i><i><sub>VAR</sub></i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vvar;
		/// <summary>
		/// Var controller deadband (<i>V</i><i><sub>VARC_BW</sub></i>).  Typical value = 0,
		/// 02.
		/// </summary>
		public float vvarcbw;
		/// <summary>
		/// Var controller reference (<i>V</i><i><sub>VARREF</sub></i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vvarref;
		/// <summary>
		/// Maximum machine terminal voltage needed for pf/VAr controller to be enabled
		/// (<i>V</i><i><sub>VTMAX</sub></i>) (> PVFArType1IEEEVArController.vvtmin).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vvtmax;
		/// <summary>
		/// Minimum machine terminal voltage needed to enable pf/var controller
		/// (<i>V</i><i><sub>VTMIN</sub></i>) (< PVFArType1IEEEVArController.vvtmax).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU vvtmin;

		/// <summary>
		/// Initializes a new instance of the <see cref="PFVArType1IEEEVArController"/> class
		/// </summary>
		public PFVArType1IEEEVArController(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PFVArType1IEEEVArController

}//end namespace PFVArControllerType1Dynamics