///////////////////////////////////////////////////////////
//  BasicIntervalSchedule.cs
//  Implementation of the Class BasicIntervalSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// Schedule of values at points in time.
	/// </summary>
	public class BasicIntervalSchedule : IdentifiedObject {

		/// <summary>
		/// The time for the first time point.  The value can be a time of day, not a
		/// specific date.
		/// </summary>
		public System.DateTime startTime;
		/// <summary>
		/// Multiplier for value1.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.UnitMultiplier value1Multiplier;
		/// <summary>
		/// Value1 units of measure.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.UnitSymbol value1Unit;
		/// <summary>
		/// Multiplier for value2.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.UnitMultiplier value2Multiplier;
		/// <summary>
		/// Value2 units of measure.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.UnitSymbol value2Unit;

		/// <summary>
		/// Initializes a new instance of the <see cref="BasicIntervalSchedule"/> class
		/// </summary>
		public BasicIntervalSchedule(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end BasicIntervalSchedule

}//end namespace Core