///////////////////////////////////////////////////////////
//  ConductingEquipment.cs
//  Implementation of the Class ConductingEquipment
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// The parts of the AC power system that are designed to carry current or that are
	/// conductively connected through terminals.
	/// </summary>
	public class ConductingEquipment : Equipment {

		/// <summary>
		/// The operating condition to the Conducting Equipment is changed when protective
		/// action adjustment is activated. For ShuntCompensator or other conducting
		/// equipment that operates on discrete values (integer), the values given in float
		/// will be rounded.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveActionAdjustment ProtectiveActionAdjustment;

		/// <summary>
		/// Initializes a new instance of the <see cref="ConductingEquipment"/> class
		/// </summary>
		public ConductingEquipment(){

		}

		~ConductingEquipment(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ConductingEquipment

}//end namespace Core