///////////////////////////////////////////////////////////
//  GeographicalRegion.cs
//  Implementation of the Class GeographicalRegion
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:57 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// A geographical region of a power system network model.
	/// </summary>
	public class GeographicalRegion : IdentifiedObject {

		/// <summary>
		/// All sub-geographical regions within this geographical region.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.SubGeographicalRegion Regions;

		/// <summary>
		/// Initializes a new instance of the <see cref="GeographicalRegion"/> class
		/// </summary>
		public GeographicalRegion(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end GeographicalRegion

}//end namespace Core