///////////////////////////////////////////////////////////
//  OperatingParticipant.cs
//  Implementation of the Class OperatingParticipant
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// An operator of multiple power system resource objects. Note multple operating
	/// participants may operate the same power system resource object.   This can be
	/// used for modeling jointly owned units where each owner operates as a
	/// contractual share.
	/// </summary>
	public class OperatingParticipant : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="OperatingParticipant"/> class
		/// </summary>
		public OperatingParticipant(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OperatingParticipant

}//end namespace Core
