///////////////////////////////////////////////////////////
//  Substation.cs
//  Implementation of the Class Substation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Core {
	/// <summary>
	/// A collection of equipment for purposes other than generation or utilization,
	/// through which electric energy in bulk is passed for the purposes of switching
	/// or modifying its characteristics.
	/// </summary>
	public class Substation : EquipmentContainer {

		/// <summary>
		/// The voltage levels within this substation.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.VoltageLevel VoltageLevels;
		/// <summary>
		/// Bays contained in the substation.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.Bay Bays;
		/// <summary>
		/// The DC converter unit belonging of the substation.
		/// </summary>
		public TC57CIM.IEC61970.Base.DC.DCConverterUnit DCConverterUnit;
		/// <summary>
		/// The normal energized feeders of the substation. Also used for naming purposes.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.Feeder NormalEnergizedFeeder;

		/// <summary>
		/// Initializes a new instance of the <see cref="Substation"/> class
		/// </summary>
		public Substation(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Substation

}//end namespace Core