///////////////////////////////////////////////////////////
//  TroubleSymptomsPoleKind.cs
//  Implementation of the Class TroubleSymptomsPoleKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of values that define the Pole problem.
	/// </summary>
	public enum TroubleSymptomsPoleKind : int {

		ok,
		down,
		leaning,
		hit,
		other

	}//end TroubleSymptomsPoleKind

}//end namespace Customers