///////////////////////////////////////////////////////////
//  AnalyticScore.cs
//  Implementation of the Class AnalyticScore
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:56 AM
//  Original author: Gowri
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// An indicative scoring by an analytic that can be used to characterize the
	/// health of or the risk associated with one or more assets.  The analytic score
	/// reflects the results of an execution of an analytic against an asset or group
	/// of assets.
	/// </summary>
	public class AnalyticScore : IdentifiedObject {

		/// <summary>
		/// Timestamp of when the score was calculated.
		/// </summary>
		public System.DateTime? calculationDateTime;
		/// <summary>
		/// Date-time for when the score applies.
		/// </summary>
		public System.DateTime? effectiveDateTime;
		/// <summary>
		/// Asset health score value.
		/// </summary>
		public float value;
		/// <summary>
		/// Asset to which this analytic score applies.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset? Asset;

		/// <summary>
		/// Initializes a new instance of the <see cref="AnalyticScore"/> class
		/// </summary>
		public AnalyticScore(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AnalyticScore

}//end namespace Assets
