///////////////////////////////////////////////////////////
//  AssetTestSampleTaker.cs
//  Implementation of the Class AssetTestSampleTaker
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Identity of person/organization that took sample.
	/// </summary>
	public class AssetTestSampleTaker : AssetOrganisationRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetTestSampleTaker"/> class
		/// </summary>
		public AssetTestSampleTaker(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AssetTestSampleTaker

}//end namespace Assets
