///////////////////////////////////////////////////////////
//  AssetTestLab.cs
//  Implementation of the Class AssetTestLab
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Test lab that performs various types of testing related to assets.
	/// </summary>
	public class AssetTestLab : AssetOrganisationRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetTestLab"/> class
		/// </summary>
		public AssetTestLab(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AssetTestLab

}//end namespace Assets