///////////////////////////////////////////////////////////
//  AssetContainer.cs
//  Implementation of the Class AssetContainer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:56 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Asset that is aggregation of other assets such as conductors, transformers,
	/// switchgear, land, fences, buildings, equipment, vehicles, etc.
	/// </summary>
	public class AssetContainer : Asset {

		/// <summary>
		/// All seals applied to this asset container.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Seal Seals;

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetContainer"/> class
		/// </summary>
		public AssetContainer(){

		}

		~AssetContainer(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end AssetContainer

}//end namespace Assets