///////////////////////////////////////////////////////////
//  AssetUser.cs
//  Implementation of the Class AssetUser
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Organisation that is a user of the asset.
	/// </summary>
	public class AssetUser : AssetOrganisationRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetUser"/> class
		/// </summary>
		public AssetUser(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AssetUser

}//end namespace Assets
