///////////////////////////////////////////////////////////
//  AssetFunction.cs
//  Implementation of the Class AssetFunction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:57 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Function performed by an asset.
	/// </summary>
	public class AssetFunction : IdentifiedObject {

		/// <summary>
		/// Configuration specified for this function.
		/// </summary>
		public string? configID;
		/// <summary>
		/// Firmware version.
		/// </summary>
		public string? firmwareID;
		/// <summary>
		/// Hardware version.
		/// </summary>
		public string? hardwareID;
		/// <summary>
		/// Password needed to access this function.
		/// </summary>
		public string? password;
		/// <summary>
		/// Name of program.
		/// </summary>
		public string? programID;

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetFunction"/> class
		/// </summary>
		public AssetFunction(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AssetFunction

}//end namespace Assets
