///////////////////////////////////////////////////////////
//  CIGREStandard.cs
//  Implementation of the Class CIGREStandard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Standard published by CIGRE (Council on Large Electric Systems).
	/// </summary>
	public class CIGREStandard {

		/// <summary>
		/// Edition of CIGRE standard.
		/// </summary>
		public CIGREStandardEditionKind standardEdition;
		/// <summary>
		/// CIGRE standard number.
		/// </summary>
		public CIGREStandardKind standardNumber;

		/// <summary>
		/// Initializes a new instance of the <see cref="CIGREStandard"/> class
		/// </summary>
		public CIGREStandard(){

		}

		~CIGREStandard(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end CIGREStandard

}//end namespace Assets