///////////////////////////////////////////////////////////
//  DeploymentDate.cs
//  Implementation of the Class DeploymentDate
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:04 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Dates for deployment events of an asset.  May have multiple deployment type
	/// dates for this device and a compound type allows a query to return multiple
	/// dates.
	/// </summary>
	public class DeploymentDate {

		/// <summary>
		/// Date and time asset most recently put in service.
		/// </summary>
		public System.DateTime? inServiceDate;
		/// <summary>
		/// Date and time asset most recently installed.
		/// </summary>
		public System.DateTime? installedDate;
		/// <summary>
		/// Date and time of asset deployment transition to not yet installed.
		/// </summary>
		public System.DateTime? notYetInstalledDate;
		/// <summary>
		/// Date and time asset most recently taken out of service.
		/// </summary>
		public System.DateTime? outOfServiceDate;
		/// <summary>
		/// Date and time asset most recently removed.
		/// </summary>
		public System.DateTime? removedDate;

		/// <summary>
		/// Initializes a new instance of the <see cref="DeploymentDate"/> class
		/// </summary>
		public DeploymentDate(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end DeploymentDate

}//end namespace Assets
