///////////////////////////////////////////////////////////
//  DuctBank.cs
//  Implementation of the Class DuctBank
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:06 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// A duct contains individual wires in the layout as specified with associated
	/// wire spacing instances; number of them gives the number of conductors in this
	/// duct.
	/// </summary>
	public class DuctBank : AssetContainer {

		/// <summary>
		/// Number of circuits in duct bank. Refer to associations between a duct
		/// (ConductorAsset) and an ACLineSegment to understand which circuits are in which
		/// ducts.
		/// </summary>
		public System.Int32 circuitCount;

		/// <summary>
		/// Initializes a new instance of the <see cref="DuctBank"/> class
		/// </summary>
		public DuctBank(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DuctBank

}//end namespace Assets