///////////////////////////////////////////////////////////
//  HealthScore.cs
//  Implementation of the Class HealthScore
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
//  Original author: Gowri
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Score that is indicative of the health of one or more assets.
	/// </summary>
	public class HealthScore : AggregateScore {

		/// <summary>
		/// Risk score with which this health score is associated.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.RiskScore? AssetRiskScore;

		/// <summary>
		/// Initializes a new instance of the <see cref="HealthScore"/> class
		/// </summary>
		public HealthScore(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end HealthScore

}//end namespace Assets
