///////////////////////////////////////////////////////////
//  IEEEStandard.cs
//  Implementation of the Class IEEEStandard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Standard published by IEEE (Institute of Electrical and Electronics Engineers).
	///
	/// </summary>
	public class IEEEStandard {

		/// <summary>
		/// Edition of IEEE standard.
		/// </summary>
		//public IEEEStandardEditionKind standardEdition;
		/// <summary>
		/// IEEE standard number.
		/// </summary>
		//public IEEEStandardKind standardNumber;

		public IEEEStandard(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end IEEEStandard

}//end namespace Assets