///////////////////////////////////////////////////////////
//  InterrupterUnit.cs
//  Implementation of the Class InterrupterUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Breaker interrupter.
	/// Some interrupters have one fixed and one moving contact, some have 2 fixed
	/// contacts, some 2 moving contacts. An interrupter will have relationships with 2
	/// bushings and those relationships may be any combination of the FixedContact and
	/// MovingContact associations.
	/// </summary>
	public class InterrupterUnit : Asset {

		/// <summary>
		/// Bushing(s) to which the moving contact(s) of this interrupter is(are) attached.
		/// Some interrupters have one fixed and one moving contact, some have 2 fixed
		/// contacts, some 2 moving contacts. An interrupter will have relationships with 2
		/// bushings and those relationships may be any combination of the FixedContact and
		/// MovingContact associations.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Bushing Bushing;

		/// <summary>
		/// Initializes a new instance of the <see cref="InterrupterUnit"/> class
		/// </summary>
		public InterrupterUnit(){

		}

		~InterrupterUnit(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end InterrupterUnit

}//end namespace Assets