///////////////////////////////////////////////////////////
//  ISOStandardEditionKind.cs
//  Implementation of the Enumeration ISOStandardEditionKind
//  Generated by GitHub Copilot
//  Created on:      23-Jul-2025
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
    /// <summary>
    /// Enumeration of ISO standard edition kinds.
    /// </summary>
    public enum ISOStandardEditionKind {
        /// <summary>
        /// Other edition not explicitly defined.
        /// </summary>
        other,
        /// <summary>
        /// First edition.
        /// </summary>
        edition1,
        /// <summary>
        /// Second edition.
        /// </summary>
        edition2,
        /// <summary>
        /// Third edition.
        /// </summary>
        edition3,
        /// <summary>
        /// Fourth edition.
        /// </summary>
        edition4,
        /// <summary>
        /// Fifth edition.
        /// </summary>
        edition5,
        /// <summary>
        /// 2015 edition.
        /// </summary>
        edition2015,
        /// <summary>
        /// 2018 edition.
        /// </summary>
        edition2018,
        /// <summary>
        /// 2022 edition.
        /// </summary>
        edition2022
    }
}
