///////////////////////////////////////////////////////////
//  ISOStandard.cs
//  Implementation of the Class ISOStandard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Standard published by ISO (International Organization for Standardization).
	/// </summary>
	public class ISOStandard {

		/// <summary>
		/// Edition of ISO standard.
		/// </summary>
		public ISOStandardEditionKind standardEdition;
		/// <summary>
		/// ISO standard number.
		/// </summary>
		public ISOStandardKind standardNumber;

		/// <summary>
		/// Constructor for ISOStandard.
		/// </summary>
		public ISOStandard(){
			standardEdition = ISOStandardEditionKind.other;
			standardNumber = ISOStandardKind.other;
		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end ISOStandard

}//end namespace Assets
