///////////////////////////////////////////////////////////
//  LaborelecStandard.cs
//  Implementation of the Class LaborelecStandard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:13 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Standard published by Laborelec.
	/// </summary>
	public class LaborelecStandard {

		/// <summary>
		/// Edition of Laborelec standard.
		/// </summary>
		public LaborelecStandardEditionKind standardEdition;
		/// <summary>
		/// Laborelec standard number.
		/// </summary>
		public LaborelecStandardKind standardNumber;

		/// <summary>
		/// Initializes a new instance of the <see cref="LaborelecStandard"/> class
		/// </summary>
		public LaborelecStandard(){

		}

		~LaborelecStandard(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end LaborelecStandard

}//end namespace Assets