///////////////////////////////////////////////////////////
//  Maintainer.cs
//  Implementation of the Class Maintainer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:14 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Organisation that maintains assets.
	/// </summary>
	public class Maintainer : AssetOrganisationRole {

		public Maintainer(){

		}

		~Maintainer(){

		}

		public override void Dispose(){

		}

	}//end Maintainer

}//end namespace Assets