///////////////////////////////////////////////////////////
//  Manufacturer.cs
//  Implementation of the Class Manufacturer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:15 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Organisation that manufactures asset products.
	/// </summary>
	public class Manufacturer : OrganisationRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="Manufacturer"/> class
		/// </summary>
		public Manufacturer(){

		}

		~Manufacturer(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end Manufacturer

}//end namespace Assets