///////////////////////////////////////////////////////////
//  ProcedureDataSet.cs
//  Implementation of the Class ProcedureDataSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:21 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// A data set recorded each time a procedure is executed. Observed results are
	/// captured in associated measurement values and/or values for properties relevant
	/// to the type of procedure performed.
	/// </summary>
	public class ProcedureDataSet : Document {

		/// <summary>
		/// Date and time procedure was completed.
		/// </summary>
		public System.DateTime completedDateTime;
		/// <summary>
		/// Work task that created this procedure data set.
		/// </summary>
		public TC57CIM.IEC61968.Work.WorkTask WorkTask;
		/// <summary>
		/// The transformer observations
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfAssets.TransformerObservation TransformerObservations;
		/// <summary>
		/// Measurement value related to this procedure data set.
		/// </summary>
		public TC57CIM.IEC61970.Base.Meas.MeasurementValue MeasurementValue;
		/// <summary>
		/// Asset to which this procedure data set applies.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Asset Asset;

		/// <summary>
		/// Initializes a new instance of the <see cref="ProcedureDataSet"/> class
		/// </summary>
		public ProcedureDataSet(){

		}

		~ProcedureDataSet(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ProcedureDataSet

}//end namespace Assets