///////////////////////////////////////////////////////////
//  Specimen.cs
//  Implementation of the Class Specimen
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Sample or specimen of a material (fluid or solid).
	/// </summary>
	public class Specimen : IdentifiedObject {

		/// <summary>
		/// Operating ambient temperature (in �C).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Temperature? ambientTemperatureAtSampling;
		/// <summary>
		/// Operating ambient humidity (in percent).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent? humidityAtSampling;
		/// <summary>
		/// Identifier of specimen used in inspection or test.
		/// </summary>
		public string? specimenID;
		/// <summary>
		/// Date and time sample specimen taken.
		/// </summary>
		public System.DateTime? specimenSampleDateTime;
		/// <summary>
		/// Date and time the specimen was received by the lab.
		/// </summary>
		public System.DateTime? specimenToLabDateTime;
		/// <summary>
		/// Test sampler taker who gathered this specimen.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.AssetTestSampleTaker? AssetTestSampleTaker;

		/// <summary>
		/// Initializes a new instance of the <see cref="Specimen"/> class
		/// </summary>
		public Specimen(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Specimen

}//end namespace Assets
