///////////////////////////////////////////////////////////
//  UKMinistryOfDefenceStandard.cs
//  Implementation of the Class UKMinistryOfDefenceStandard
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:30 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// Standard published by United Kingdom Ministry of Defence.
	/// </summary>
	public class UKMinistryOfDefenceStandard {

		/// <summary>
		/// Edition of UK Ministry of Defence standard.
		/// </summary>
		public UKMinistryOfDefenceStandardEditionKind standardEdition;
		/// <summary>
		/// UK Ministry of Defence standard number.
		/// </summary>
		public UKMinistryofDefenceStandardKind standardNumber;

		/// <summary>
		/// Initializes a new instance of the <see cref="UKMinistryOfDefenceStandard"/> class
		/// </summary>
		public UKMinistryOfDefenceStandard(){

		}

		~UKMinistryOfDefenceStandard(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end UKMinistryOfDefenceStandard

}//end namespace Assets