///////////////////////////////////////////////////////////
//  WEPStandardKind.cs
//  Implementation of the Class WEPStandardKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:31 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo.Assets {
	/// <summary>
	/// List of WEP standards.
	/// </summary>
	public enum WEPStandardKind : int {

		/// <summary>
		/// Westinghouse Engineering Procedure 12,1254E.
		/// </summary>
		WE_12, 
		/// <summary>
		/// The we 1254e wep standard kind
		/// </summary>
		WE_1254E

	}//end WEPStandardKind

}//end namespace Assets