///////////////////////////////////////////////////////////
//  GenUnitOpCostCurve.cs
//  Implementation of the Class GenUnitOpCostCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:57 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between unit operating cost (Y-axis) and unit output active power
	/// (X-axis). The operating cost curve for thermal units is derived from heat input
	/// and fuel costs. The operating cost curve for hydro units is derived from water
	/// flow rates and equivalent water costs.
	/// </summary>
	public class GenUnitOpCostCurve : Curve {

		/// <summary>
		/// Flag is set to true when output is expressed in net active power.
		/// </summary>
		public bool isNetGrossP;

		/// <summary>
		/// Initializes a new instance of the <see cref="GenUnitOpCostCurve"/> class
		/// </summary>
		public GenUnitOpCostCurve(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end GenUnitOpCostCurve

}//end namespace Production