///////////////////////////////////////////////////////////
//  HydroGeneratingEfficiencyCurve.cs
//  Implementation of the Class HydroGeneratingEfficiencyCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between unit efficiency as percentage and unit output active power
	/// for a given net head in meters. The relationship between efficiency, discharge,
	/// head, and power output is expressed as follows:   E =KP/HQ
	/// where:  E is the efficiency, as a percentage; P is the active power; H is the
	/// height; Q is the discharge, volume/time unit; K is a constant.
	/// For example, a curve instance for a given net head could show efficiency (Y-
	/// axis) versus active power output (X-axis) or versus discharge on the X-axis.
	/// </summary>
	public class HydroGeneratingEfficiencyCurve : Curve {

		/// <summary>
		/// Initializes a new instance of the <see cref="HydroGeneratingEfficiencyCurve"/> class
		/// </summary>
		public HydroGeneratingEfficiencyCurve(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end HydroGeneratingEfficiencyCurve

}//end namespace Production