///////////////////////////////////////////////////////////
//  IncrementalHeatRateCurve.cs
//  Implementation of the Class IncrementalHeatRateCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:04 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between unit incremental heat rate in (delta energy/time) per
	/// (delta active power) and unit output in active power. The IHR curve represents
	/// the slope of the HeatInputCurve. Note that the "incremental heat rate" and the
	/// "heat rate" have the same engineering units.
	/// </summary>
	public class IncrementalHeatRateCurve : Curve {

		/// <summary>
		/// Flag is set to true when output is expressed in net active power.
		/// </summary>
		public bool isNetGrossP;

		/// <summary>
		/// Initializes a new instance of the <see cref="IncrementalHeatRateCurve"/> class
		/// </summary>
		public IncrementalHeatRateCurve(){

		}

		~IncrementalHeatRateCurve(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end IncrementalHeatRateCurve

}//end namespace Production