///////////////////////////////////////////////////////////
//  LevelVsVolumeCurve.cs
//  Implementation of the Class LevelVsVolumeCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between reservoir volume and reservoir level. The  volume is at
	/// the Y-axis and the reservoir level at the X-axis.
	/// </summary>
	public class LevelVsVolumeCurve : Curve {

		/// <summary>
		/// Initializes a new instance of the <see cref="LevelVsVolumeCurve"/> class
		/// </summary>
		public LevelVsVolumeCurve(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end LevelVsVolumeCurve

}//end namespace Production