///////////////////////////////////////////////////////////
//  PowerElectronicsWindUnit.cs
//  Implementation of the Class PowerElectronicsWindUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:14 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// A wind generating unit that connects to the AC network with power electronics
	/// rather than rotating machines or an aggregation of such units.
	/// </summary>
	public class PowerElectronicsWindUnit : PowerElectronicsUnit {

		/// <summary>
		/// Initializes a new instance of the <see cref="PowerElectronicsWindUnit"/> class
		/// </summary>
		public PowerElectronicsWindUnit(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PowerElectronicsWindUnit

}//end namespace Production
