///////////////////////////////////////////////////////////
//  StartMainFuelCurve.cs
//  Implementation of the Class StartMainFuelCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:22 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// The quantity of main fuel (Y-axis) used to restart and repay the auxiliary
	/// power consumed versus the number of hours (X-axis) the unit was off line.
	/// </summary>
	public class StartMainFuelCurve : Curve {

		/// <summary>
		/// Type of main fuel.
		/// </summary>
		public FuelType mainFuelType;

		/// <summary>
		/// Initializes a new instance of the <see cref="StartMainFuelCurve"/> class
		/// </summary>
		public StartMainFuelCurve(){

		}

		~StartMainFuelCurve(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end StartMainFuelCurve

}//end namespace Production