///////////////////////////////////////////////////////////
//  TailbayLossCurve.cs
//  Implementation of the Class TailbayLossCurve
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:24 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// Relationship between tailbay head loss height (Y-axis) and the total discharge
	/// into the power station's tailbay volume per time unit (X-axis) . There could be
	/// more than one curve depending on the level of the tailbay reservoir or river
	/// level.
	/// </summary>
	public class TailbayLossCurve : Curve {

		/// <summary>
		/// Initializes a new instance of the <see cref="TailbayLossCurve"/> class
		/// </summary>
		public TailbayLossCurve(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end TailbayLossCurve

}//end namespace Production
