///////////////////////////////////////////////////////////
//  WindGeneratingUnit.cs
//  Implementation of the Class WindGeneratingUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:31 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Generation.Production {
	/// <summary>
	/// A wind driven generating unit, connected to the grid by means of a rotating
	/// machine.  May be used to represent a single turbine or an aggregation.
	/// </summary>
	public class WindGeneratingUnit : GeneratingUnit {

		/// <summary>
		/// The kind of wind generating unit.
		/// </summary>
		public WindGenUnitKind windGenUnitType;

		/// <summary>
		/// Initializes a new instance of the <see cref="WindGeneratingUnit"/> class
		/// </summary>
		public WindGeneratingUnit(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WindGeneratingUnit

}//end namespace Production