///////////////////////////////////////////////////////////
//  Displacement.cs
//  Implementation of the Class Displacement
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:49 AM
//  Original author: LOO
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Unit of displacement relative to a reference position, hence can be negative.
	/// </summary>
	public class Displacement {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.m;
		public Float value;

		public Displacement(){

		}

		~Displacement(){

		}

		public virtual void Dispose(){

		}

	}//end Displacement

}//end namespace Domain