///////////////////////////////////////////////////////////
//  RotationSpeed.cs
//  Implementation of the Class RotationSpeed
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Number of revolutions per second.
	/// </summary>
	public class RotationSpeed {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.Hz;
		public Float value;

		public RotationSpeed(){

		}

		~RotationSpeed(){

		}

		public virtual void Dispose(){

		}

	}//end RotationSpeed

}//end namespace Domain