///////////////////////////////////////////////////////////
//  ExcAVR5.cs
//  Implementation of the Class ExcAVR5
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:52 AM
//  Original author: pcha006
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics {
	/// <summary>
	/// Manual excitation control with field circuit resistance. This model can be used
	/// as a very simple representation of manual voltage control.
	/// </summary>
	public class ExcAVR5 : ExcitationSystemDynamics {

		/// <summary>
		/// Gain (<i>Ka</i>).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU ka;
		/// <summary>
		/// Effective output resistance (<i>Rex</i>). <i>Rex</i> represents the effective
		/// output resistance seen by the excitation system.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU rex;
		/// <summary>
		/// Time constant (<i>Ta</i>) (>= 0).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds ta;

		/// <summary>
		/// Constructor for ExcAVR5.
		/// </summary>
		public ExcAVR5(){

		}

		/// <summary>
		/// Destructor for ExcAVR5.
		/// </summary>
		~ExcAVR5(){

		}

		/// <summary>
		/// Dispose method for ExcAVR5.
		/// </summary>
		public override void Dispose(){

		}

	}//end ExcAVR5

}//end namespace ExcitationSystemDynamics