///////////////////////////////////////////////////////////
//  ExcSEXS.cs
//  Implementation of the Class ExcSEXS
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:55 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics {
	/// <summary>
	/// Simplified excitation system.
	/// </summary>
	public class ExcSEXS : ExcitationSystemDynamics {

		/// <summary>
		/// Field voltage clipping maximum limit (<i>Efdmax</i>) (&gt; ExcSEXS.efdmin).
		/// Typical value = 5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? efdmax;
		/// <summary>
		/// Field voltage clipping minimum limit (<i>Efdmin</i>) (&lt; ExcSEXS.efdmax).
		/// Typical value = -5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? efdmin;
		/// <summary>
		/// Maximum field voltage output (<i>Emax</i>) (&gt; ExcSEXS.emin).  Typical value = 5.
		///
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? emax;
		/// <summary>
		/// Minimum field voltage output (<i>Emin</i>) (&lt; ExcSEXS.emax).  Typical value = -
		/// 5.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? emin;
		/// <summary>
		/// Gain (<i>K</i>) (> 0).  Typical value = 100.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? k;
		/// <summary>
		/// PI controller gain (<i>Kc</i>) (> 0 if ExcSEXS.tc > 0).  Typical value = 0,08.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PU? kc;
		/// <summary>
		/// Gain reduction ratio of lag-lead element (<i>[Ta / Tb]</i>).  Typical value = 0,
		/// 1.
		/// </summary>
		public float tatb;
		/// <summary>
		/// Denominator time constant of lag-lead block (<i>Tb</i>) (>= 0).  Typical value
		/// = 10.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? tb;
		/// <summary>
		/// PI controller phase lead time constant (<i>Tc</i>) (>= 0).  Typical value = 0.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? tc;
		/// <summary>
		/// Time constant of gain block (<i>Te</i>) (> 0).  Typical value = 0,05.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Seconds? te;

		/// <summary>
		/// Constructor for ExcSEXS.
		/// </summary>
		public ExcSEXS(){

		}

    /// <summary>
    /// Dispose method for ExcSEXS.
    /// </summary>
    public override void Dispose(){

		}

	}//end ExcSEXS

}//end namespace ExcitationSystemDynamics
