///////////////////////////////////////////////////////////
//  VDCOL.cs
//  Implementation of the Class VDCOL
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:28 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC {
	public class VDCOL {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.CSC.IdcInverterControl m_IdcInverterControl;

		public VDCOL(){

		}

		~VDCOL(){

		}

		public virtual void Dispose(){

		}

	}//end VDCOL

}//end namespace CSC