///////////////////////////////////////////////////////////
//  BlockDispatchOrder.cs
//  Implementation of the Class BlockDispatchOrder
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.EnergyArea {
	public class BlockDispatchOrder : IdentifiedObject {

		public TC57CIM.IEC61970.Base.Domain.ActivePower p;
		public TC57CIM.IEC61970.Base.Domain.Integer sequence;
		public TC57CIM.IEC61970.InfIEC61970.EnergyArea.BlockDispatchComponent m_BlockDispatchComponent;

		public BlockDispatchOrder(){

		}

		~BlockDispatchOrder(){

		}

		public override void Dispose(){

		}

	}//end BlockDispatchOrder

}//end namespace EnergyArea