///////////////////////////////////////////////////////////
//  BlockDispatchInstruction.cs
//  Implementation of the Class BlockDispatchInstruction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:41 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.EnergyArea {
	/// <summary>
	/// Represents a block dispatch instruction in the energy area.
	/// </summary>
	public class BlockDispatchInstruction : IdentifiedObject {

		/// <summary>
		/// The block dispatch order associated with this instruction.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.EnergyArea.BlockDispatchOrder? m_BlockDispatchOrder;
		/// <summary>
		/// The energy group associated with this instruction.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyGroup? m_EnergyGroup;

		/// <summary>
		/// Initializes a new instance of the <see cref="BlockDispatchInstruction"/> class.
		/// </summary>
		public BlockDispatchInstruction(){

		}

		/// <summary>
		/// Finalizes an instance of the <see cref="BlockDispatchInstruction"/> class.
		/// </summary>
		~BlockDispatchInstruction(){

		}

		/// <summary>
		/// Releases resources used by the <see cref="BlockDispatchInstruction"/> class.
		/// </summary>
		public override void Dispose(){

		}

	}//end BlockDispatchInstruction

}//end namespace EnergyArea