///////////////////////////////////////////////////////////
//  EnergyTypeKind.cs
//  Implementation of the Class EnergyTypeKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:50 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.EnergyArea {
	/// <summary>
	/// Specifies the kind of energy type for an energy area component.
	/// </summary>
	public enum EnergyTypeKind : int {

		/// <summary>
		/// Photovoltaic park.
		/// </summary>
		PVpark,
		/// <summary>
		/// Wind park.
		/// </summary>
		WindPark,
		/// <summary>
		/// Consumer load.
		/// </summary>
		ConsumerLoad,
		/// <summary>
		/// Industrial load.
		/// </summary>
		IndustrialLoad,
		/// <summary>
		/// Other type of energy.
		/// </summary>
		Other

	}//end EnergyTypeKind

}//end namespace EnergyArea