///////////////////////////////////////////////////////////
//  ProportionalDistributionComponent.cs
//  Implementation of the Class ProportionalDistributionComponent
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.InfIEC61970.EnergyArea {
	/// <summary>
	/// Represents a proportional distribution component in the energy area.
	/// </summary>
	public class ProportionalDistributionComponent : EnergyComponent {

		/// <summary>
		/// The distribution factor for proportional distribution.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower? distributionFactor;

		/// <summary>
		/// Initializes a new instance of the <see cref="ProportionalDistributionComponent"/> class.
		/// </summary>
		public ProportionalDistributionComponent(){

		}

		/// <summary>
		/// Finalizes an instance of the <see cref="ProportionalDistributionComponent"/> class.
		/// </summary>
		~ProportionalDistributionComponent(){

		}

		/// <summary>
		/// Releases resources used by the <see cref="ProportionalDistributionComponent"/> class.
		/// </summary>
		public override void Dispose(){

		}

	}//end ProportionalDistributionComponent

}//end namespace EnergyArea