///////////////////////////////////////////////////////////
//  DrumBoiler.cs
//  Implementation of the Class DrumBoiler
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:49 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// Drum boiler.
	/// </summary>
	public class DrumBoiler : FossilSteamSupply {

		/// <summary>
		/// Rating of drum boiler in steam units.
		/// </summary>
		public float drumBoilerRating;

		public DrumBoiler(){

		}

		~DrumBoiler(){

		}

		public override void Dispose(){

		}

	}//end DrumBoiler

}//end namespace GenerationTrainingSimulation