///////////////////////////////////////////////////////////
//  PrimeMover.cs
//  Implementation of the Class PrimeMover
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:15 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// The machine used to develop mechanical energy used to drive a generator.
	/// </summary>
	public class PrimeMover : PowerSystemResource {

		/// <summary>
		/// Rating of prime mover.
		/// </summary>
		public float primeMoverRating;
		/// <summary>
		/// Synchronous machines this Prime mover drives.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.SynchronousMachine SynchronousMachines;

		/// <summary>
		/// Initializes a new instance of the <see cref="PrimeMover"/> class
		/// </summary>
		public PrimeMover(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PrimeMover

}//end namespace GenerationTrainingSimulation