///////////////////////////////////////////////////////////
//  Supercritical.cs
//  Implementation of the Class Supercritical
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:23 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// Once-through supercritical boiler.
	/// </summary>
	public class Supercritical : FossilSteamSupply {

		/// <summary>
		/// Initializes a new instance of the <see cref="Supercritical"/> class
		/// </summary>
		public Supercritical(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Supercritical

}//end namespace GenerationTrainingSimulation
