///////////////////////////////////////////////////////////
//  ActivePowerPerFrequency.cs
//  Implementation of the Class ActivePowerPerFrequency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Active power variation with frequency.
	/// </summary>
	public class ActivePowerPerFrequency {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The pers
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.WPers;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="ActivePowerPerFrequency"/> class
		/// </summary>
		public ActivePowerPerFrequency(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end ActivePowerPerFrequency

}//end namespace Domain
