///////////////////////////////////////////////////////////
//  ActivePowerPerCurrentFlow.cs
//  Implementation of the Class ActivePowerPerCurrentFlow
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Active power variation with current flow.
	/// </summary>
	public class ActivePowerPerCurrentFlow {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The per
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.WPerA;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="ActivePowerPerCurrentFlow"/> class
		/// </summary>
		public ActivePowerPerCurrentFlow(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end ActivePowerPerCurrentFlow

}//end namespace Domain