///////////////////////////////////////////////////////////
//  AngleRadians.cs
//  Implementation of the Class AngleRadians
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Phase angle in radians.
	/// </summary>
	public class AngleRadians {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.rad;
		public Float value;

		public AngleRadians(){

		}

		~AngleRadians(){

		}

		public virtual void Dispose(){

		}

	}//end AngleRadians

}//end namespace Domain