///////////////////////////////////////////////////////////
//  Area.cs
//  Implementation of the Class Area
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:40 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Area.
	/// </summary>
	public class Area {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.m2;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Area"/> class
		/// </summary>
		public Area(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Area

}//end namespace Domain