///////////////////////////////////////////////////////////
//  Conductance.cs
//  Implementation of the Class Conductance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Factor by which voltage must be multiplied to give corresponding power lost
	/// from a circuit. Real part of admittance.
	/// </summary>
	public class Conductance {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The 
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.S;
		/// <summary>
		/// The value
		/// </summary>
		public System.Single value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Conductance"/> class
		/// </summary>
		public Conductance(){

		}

		~Conductance(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Conductance

}//end namespace Domain