///////////////////////////////////////////////////////////
//  CostPerHeatUnit.cs
//  Implementation of the Class CostPerHeatUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Cost, in units of currency, per quantity of heat generated.
	/// </summary>
	public class CostPerHeatUnit {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The unit
		/// </summary>
		public Currency unit;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="CostPerHeatUnit"/> class
		/// </summary>
		public CostPerHeatUnit(){

		}

		~CostPerHeatUnit(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end CostPerHeatUnit

}//end namespace Domain