///////////////////////////////////////////////////////////
//  CostPerVolume.cs
//  Implementation of the Class CostPerVolume
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
//  Original author: SELAOST1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Cost per unit volume.
	/// </summary>
	public class CostPerVolume {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The unit
		/// </summary>
		public Currency unit;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="CostPerVolume"/> class
		/// </summary>
		public CostPerVolume(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end CostPerVolume

}//end namespace Domain