///////////////////////////////////////////////////////////
//  CostRate.cs
//  Implementation of the Class CostRate
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Cost, in units of currency, per elapsed time.
	/// </summary>
	public class CostRate {

		public UnitMultiplier multiplier;
		public Currency unit;
		public Float value;

		public CostRate(){

		}

		~CostRate(){

		}

		public virtual void Dispose(){

		}

	}//end CostRate

}//end namespace Domain