///////////////////////////////////////////////////////////
//  CostPerEnergyUnit.cs
//  Implementation of the Class CostPerEnergyUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:44 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Cost, in units of currency, per quantity of electrical energy generated.
	/// </summary>
	public class CostPerEnergyUnit {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The unit
		/// </summary>
		public Currency unit;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="CostPerEnergyUnit"/> class
		/// </summary>
		public CostPerEnergyUnit(){

		}

		~CostPerEnergyUnit(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end CostPerEnergyUnit

}//end namespace Domain