///////////////////////////////////////////////////////////
//  Damping.cs
//  Implementation of the Class Damping
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:46 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Per-unit active power variation with frequency referenced on the system
	/// apparent power base. Typical values are in the range 1,0 - 2,0.
	/// </summary>
	public class Damping {

		/// <summary>
		/// The multiplier
		/// </summary>
		public static readonly UnitMultiplier multiplier;
		/// <summary>
		/// The one per hz
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.onePerHz;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Damping"/> class
		/// </summary>
		public Damping(){

		}

		~Damping(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Damping

}//end namespace Domain