///////////////////////////////////////////////////////////
//  Decimal.cs
//  Implementation of the Class Decimal
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: kdemaree
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Decimal is the base-10 notational system for representing real numbers.
	/// </summary>
	public class Decimal {

		/// <summary>
		/// Initializes a new instance of the <see cref="Decimal"/> class
		/// </summary>
		public Decimal(){

		}

		~Decimal(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Decimal

}//end namespace Domain