///////////////////////////////////////////////////////////
//  DecimalQuantity.cs
//  Implementation of the Class DecimalQuantity
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:47 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Quantity with decimal value and associated unit or currency information.
	/// </summary>
	public class DecimalQuantity {

		/// <summary>
		/// Currency of this quantity.
		/// </summary>
		public Currency currency;
		/// <summary>
		/// Unit multiplier of this quantity.
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// Unit of this quantity.
		/// </summary>
		public UnitSymbol unit;
		/// <summary>
		/// Value of this quantity.
		/// </summary>
		public Decimal value;

		/// <summary>
		/// Initializes a new instance of the <see cref="DecimalQuantity"/> class
		/// </summary>
		public DecimalQuantity(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end DecimalQuantity

}//end namespace Domain