///////////////////////////////////////////////////////////
//  Emission.cs
//  Implementation of the Class Emission
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:49 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Quantity of emission per fuel heat content.
	/// </summary>
	public class Emission {

		/// <summary>
		/// The none
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		/// <summary>
		/// The kg per
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.kgPerJ;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Emission"/> class
		/// </summary>
		public Emission(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Emission

}//end namespace Domain
