///////////////////////////////////////////////////////////
//  FloatQuantity.cs
//  Implementation of the Class FloatQuantity
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:56 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Quantity with float value and associated unit information.
	/// </summary>
	public class FloatQuantity {

		/// <summary>
		/// Unit multiplier of this quantity.
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// Unit of this quantity.
		/// </summary>
		public UnitSymbol unit;
		/// <summary>
		/// Value of this quantity.
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="FloatQuantity"/> class
		/// </summary>
		public FloatQuantity(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end FloatQuantity

}//end namespace Domain
