///////////////////////////////////////////////////////////
//  Hours.cs
//  Implementation of the Class Hours
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:01 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Time specified in hours.
	/// </summary>
	public class Hours {

		/// <summary>
		/// The none
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		/// <summary>
		/// The 
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.h;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Hours"/> class
		/// </summary>
		public Hours(){

		}

		~Hours(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Hours

}//end namespace Domain