///////////////////////////////////////////////////////////
//  InductancePerLength.cs
//  Implementation of the Class InductancePerLength
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Inductance per unit of length.
	/// </summary>
	public class InductancePerLength {

		/// <summary>
		/// The none
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		/// <summary>
		/// The perm
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.HPerm;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="InductancePerLength"/> class
		/// </summary>
		public InductancePerLength(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end InductancePerLength

}//end namespace Domain