///////////////////////////////////////////////////////////
//  IntegerQuantity.cs
//  Implementation of the Class IntegerQuantity
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Quantity with integer value and associated unit information.
	/// </summary>
	public class IntegerQuantity {

		/// <summary>
		/// Unit multiplier of this quantity.
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// Unit of this quantity.
		/// </summary>
		public UnitSymbol unit;
		/// <summary>
		/// Value of this quantity.
		/// </summary>
		public Integer value;

		/// <summary>
		/// Initializes a new instance of the <see cref="IntegerQuantity"/> class
		/// </summary>
		public IntegerQuantity(){

		}

		~IntegerQuantity(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end IntegerQuantity

}//end namespace Domain