///////////////////////////////////////////////////////////
//  Integer.cs
//  Implementation of the Class Integer
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// An integer number. The range is unspecified and not limited.
	/// </summary>
	public class Integer {

		/// <summary>
		/// Initializes a new instance of the <see cref="Integer"/> class
		/// </summary>
		public Integer(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Integer

}//end namespace Domain