///////////////////////////////////////////////////////////
//  KiloActivePower.cs
//  Implementation of the Class KiloActivePower
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Active power in kilowatts.
	/// </summary>
	public class KiloActivePower {

		/// <summary>
		/// The
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.k;
		/// <summary>
		/// The
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.W;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="KiloActivePower"/> class
		/// </summary>
		public KiloActivePower(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end KiloActivePower

}//end namespace Domain
