///////////////////////////////////////////////////////////
//  Minutes.cs
//  Implementation of the Class Minutes
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:07 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Time in minutes.
	/// </summary>
	public class Minutes {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.min;
		public Float value;

		public Minutes(){

		}

		~Minutes(){

		}

		public virtual void Dispose(){

		}

	}//end Minutes

}//end namespace Domain