///////////////////////////////////////////////////////////
//  MonthDay.cs
//  Implementation of the Class MonthDay
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:08 AM
//  Original author: selaost1
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// MonthDay format as "--mm-dd", which conforms with XSD data type gMonthDay.
	/// </summary>
	public class MonthDay {

		/// <summary>
		/// Initializes a new instance of the <see cref="MonthDay"/> class
		/// </summary>
		public MonthDay(){

		}

		~MonthDay(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end MonthDay

}//end namespace Domain