///////////////////////////////////////////////////////////
//  ReactivePower.cs
//  Implementation of the Class ReactivePower
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:18 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Product of RMS value of the voltage and the RMS value of the quadrature
	/// component of the current.
	/// </summary>
	public class ReactivePower {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The ar
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.VAr;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="ReactivePower"/> class
		/// </summary>
		public ReactivePower(){

		}

		~ReactivePower(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end ReactivePower

}//end namespace Domain