///////////////////////////////////////////////////////////
//  Resistance.cs
//  Implementation of the Class Resistance
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Resistance (real part of impedance).
	/// </summary>
	public class Resistance {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The ohm
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.ohm;
		/// <summary>
		/// The value
		/// </summary>
		public System.Single value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Resistance"/> class
		/// </summary>
		public Resistance(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Resistance

}//end namespace Domain