///////////////////////////////////////////////////////////
//  RotationSpeed.cs
//  Implementation of the Class RotationSpeed
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:20 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Number of revolutions per second.
	/// </summary>
	public class RotationSpeed {

		/// <summary>
		/// The none
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		/// <summary>
		/// The hz
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.Hz;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="RotationSpeed"/> class
		/// </summary>
		public RotationSpeed(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end RotationSpeed

}//end namespace Domain
