///////////////////////////////////////////////////////////
//  Seconds.cs
//  Implementation of the Class Seconds
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Time, in seconds.
	/// </summary>
	public class Seconds {

		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		public static readonly UnitSymbol unit = UnitSymbol.s;
		/// <summary>
		/// Time, in seconds
		/// </summary>
		public Float value;

		public Seconds(){

		}

		~Seconds(){

		}

		public virtual void Dispose(){

		}

	}//end Seconds

}//end namespace Domain