///////////////////////////////////////////////////////////
//  Speed.cs
//  Implementation of the Class Speed
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Distance per unit of time.
	/// </summary>
	public class Speed {

		/// <summary>
		/// The none
		/// </summary>
		public static readonly UnitMultiplier multiplier = UnitMultiplier.none;
		/// <summary>
		/// The pers
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.mPers;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Speed"/> class
		/// </summary>
		public Speed(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Speed

}//end namespace Domain