///////////////////////////////////////////////////////////
//  TimeInterval.cs
//  Implementation of the Class TimeInterval
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:26 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Interval between two times.
	/// </summary>
	public class TimeInterval {

		/// <summary>
		/// End time of this interval.
		/// </summary>
		public Time end;
		/// <summary>
		/// Start time of this interval.
		/// </summary>
		public Time start;

		/// <summary>
		/// Initializes a new instance of the <see cref="TimeInterval"/> class
		/// </summary>
		public TimeInterval(){

		}

		~TimeInterval(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end TimeInterval

}//end namespace Domain