///////////////////////////////////////////////////////////
//  VoltagePerReactivePower.cs
//  Implementation of the Class VoltagePerReactivePower
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Voltage variation with reactive power.
	/// </summary>
	public class VoltagePerReactivePower {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The per ar
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.VPerVAr;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="VoltagePerReactivePower"/> class
		/// </summary>
		public VoltagePerReactivePower(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end VoltagePerReactivePower

}//end namespace Domain
