///////////////////////////////////////////////////////////
//  Voltage.cs
//  Implementation of the Class Voltage
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:28 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Electrical voltage, can be both AC and DC.
	/// </summary>
	public class Voltage {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The 
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.V;
		/// <summary>
		/// The value
		/// </summary>
		public System.Single value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Voltage"/> class
		/// </summary>
		public Voltage(){

		}

		~Voltage(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Voltage

}//end namespace Domain