///////////////////////////////////////////////////////////
//  Volume.cs
//  Implementation of the Class Volume
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Volume.
	/// </summary>
	public class Volume {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The 
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.m3;
		/// <summary>
		/// The value
		/// </summary>
		public Float value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Volume"/> class
		/// </summary>
		public Volume(){

		}

		~Volume(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public virtual void Dispose(){

		}

	}//end Volume

}//end namespace Domain