///////////////////////////////////////////////////////////
//  WaterLevel.cs
//  Implementation of the Class WaterLevel
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:30 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Domain {
	/// <summary>
	/// Reservoir water level referred to a given datum such as mean sea level.
	/// </summary>
	public class WaterLevel {

		/// <summary>
		/// The multiplier
		/// </summary>
		public UnitMultiplier multiplier;
		/// <summary>
		/// The
		/// </summary>
		public static readonly UnitSymbol unit = UnitSymbol.m;
		/// <summary>
		/// The value
		/// </summary>
		public Float? value;

		/// <summary>
		/// Initializes a new instance of the <see cref="WaterLevel"/> class
		/// </summary>
		public WaterLevel(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end WaterLevel

}//end namespace Domain
