///////////////////////////////////////////////////////////
//  LocationGrant.cs
//  Implementation of the Class LocationGrant
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:14 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfLocations {
	/// <summary>
	/// A grant provides a right, as defined by type, for a parcel of land. Note that
	/// the association to Location, Asset, Organisation, etc. for the Grant is
	/// inherited from Agreement, a type of Document.
	/// </summary>
	public class LocationGrant : Agreement {

		/// <summary>
		/// Property related information that describes the Grant's land parcel. For
		/// example, it may be a deed book number, deed book page number, and parcel number.
		/// 
		/// </summary>
		public string propertyData;

		/// <summary>
		/// Initializes a new instance of the <see cref="LocationGrant"/> class
		/// </summary>
		public LocationGrant(){

		}

		~LocationGrant(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end LocationGrant

}//end namespace InfLocations