///////////////////////////////////////////////////////////
//  RedLine.cs
//  Implementation of the Class RedLine
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.InfIEC61968.InfLocations {
	/// <summary>
	/// This class is used for handling the accompanying annotations, time stamp,
	/// author, etc. of designs, drawings and maps. A red line can be associated with
	/// any Location object.
	/// </summary>
	public class RedLine : IdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;

		/// <summary>
		/// Initializes a new instance of the <see cref="RedLine"/> class
		/// </summary>
		public RedLine(){

		}

		~RedLine(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end RedLine

}//end namespace InfLocations