///////////////////////////////////////////////////////////
//  ZoneKind.cs
//  Implementation of the Class ZoneKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfLocations {
	/// <summary>
	/// Kind of zone.
	/// </summary>
	public enum ZoneKind : int {

		/// <summary>
		/// The electrical network zone kind
		/// </summary>
		electricalNetwork,
		/// <summary>
		/// The special restriction land zone kind
		/// </summary>
		specialRestrictionLand,
		/// <summary>
		/// The weather zone zone kind
		/// </summary>
		weatherZone,
		/// <summary>
		/// The other zone kind
		/// </summary>
		other

	}//end ZoneKind

}//end namespace InfLocations