///////////////////////////////////////////////////////////
//  Zone.cs
//  Implementation of the Class Zone
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.InfIEC61968.InfLocations {
	/// <summary>
	/// Area divided off from other areas. It may be part of the electrical network, a
	/// land area where special restrictions apply, weather areas, etc. For weather, it
	/// is an area where a set of relatively homogenous weather measurements apply.
	/// </summary>
	public class Zone : Location {

		/// <summary>
		/// Kind of this zone.
		/// </summary>
		public ZoneKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="Zone"/> class
		/// </summary>
		public Zone(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Zone

}//end namespace InfLocations