///////////////////////////////////////////////////////////
//  Appointment.cs
//  Implementation of the Class Appointment
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:56 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Domain;
using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Meeting time and location.
	/// </summary>
	public class Appointment : IdentifiedObject {

		/// <summary>
		/// True if requested to call customer when someone is about to arrive at their
		/// premises.
		/// </summary>
		public bool callAhead;
		/// <summary>
		/// Date and time reserved for appointment.
		/// </summary>
		public DateTimeInterval meetingInterval;
		/// <summary>
		/// All works for this appointment.
		/// </summary>
		public TC57CIM.IEC61968.Work.Work Works;

		/// <summary>
		/// Initializes a new instance of the <see cref="Appointment"/> class
		/// </summary>
		public Appointment(){

		}

		~Appointment(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end Appointment

}//end namespace Common