///////////////////////////////////////////////////////////
//  CrewType.cs
//  Implementation of the Class CrewType
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Custom description of the type of crew. This may be used to determine the type
	/// of work the crew can be assigned to. Examples include repair, tree trimming,
	/// switching, etc.
	/// </summary>
	public class CrewType : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="CrewType"/> class
		/// </summary>
		public CrewType(){

		}

		~CrewType(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end CrewType

}//end namespace Common