///////////////////////////////////////////////////////////
//  ExtensionItem.cs
//  Implementation of the Class ExtensionItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:10 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Specifies the extensions list items
	/// </summary>
	public class ExtensionItem {

		/// <summary>
		/// the name of the extension
		/// </summary>
		public string? extName;
		/// <summary>
		/// The type of the extension
		/// </summary>
		public string? extType;
		/// <summary>
		/// the value of the extension
		/// </summary>
		public string? extValue;

		/// <summary>
		/// Initializes a new instance of the <see cref="ExtensionItem"/> class
		/// </summary>
		public ExtensionItem(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end ExtensionItem

}//end namespace Common
