///////////////////////////////////////////////////////////
//  Operator.cs
//  Implementation of the Class Operator
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Control room operator.
	/// </summary>
	public class Operator : OperationPersonRole {

		/// <summary>
		/// Initializes a new instance of the <see cref="Operator"/> class
		/// </summary>
		public Operator(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Operator

}//end namespace Common
