///////////////////////////////////////////////////////////
//  ParentOrganization.cs
//  Implementation of the Class ParentOrganization
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:19 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// The parent organization class
	/// </summary>
	/// <seealso cref="Organisation"/>
	public class ParentOrganization : Organisation {

		/// <summary>
		/// Initializes a new instance of the <see cref="ParentOrganization"/> class
		/// </summary>
		public ParentOrganization(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ParentOrganization

}//end namespace Common