///////////////////////////////////////////////////////////
//  Priority.cs
//  Implementation of the Class Priority
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:21 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Priority definition.
	/// </summary>
	public class Priority {

		/// <summary>
		/// Justification for 'rank'.
		/// </summary>
		public string justification;
		/// <summary>
		/// Priority level; lower number means high priority inside the same 'type'.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer rank;
		/// <summary>
		/// Type describing 'rank'; e.g., high, emergency, etc.
		/// </summary>
		public string type;

		/// <summary>
		/// Initializes a new instance of the <see cref="Priority"/> class
		/// </summary>
		public Priority(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Priority

}//end namespace Common