///////////////////////////////////////////////////////////
//  Status.cs
//  Implementation of the Class Status
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:25 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	/// <summary>
	/// Current status information relevant to an entity.
	/// </summary>
	public class Status {

		/// <summary>
		/// Date and time for which status 'value' applies.
		/// </summary>
		public System.DateTime dateTime;
		/// <summary>
		/// Reason code or explanation for why an object went to the current status 'value'.
		///
		/// </summary>
		public string reason;
		/// <summary>
		/// Pertinent information regarding the current 'value', as free form text.
		/// </summary>
		public string remark;
		/// <summary>
		/// Status value at 'dateTime'; prior status changes may have been kept in
		/// instances of activity records associated with the object to which this status
		/// applies.
		/// </summary>
		public string value;

		/// <summary>
		/// Initializes a new instance of the <see cref="Status"/> class
		/// </summary>
		public Status(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end Status

}//end namespace Common