///////////////////////////////////////////////////////////
//  MaintenanceOrder.cs
//  Implementation of the Class MaintenanceOrder
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:14 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// The maintenance order class
	/// </summary>
	/// <seealso cref="WorkOrder"/>
	public class MaintenanceOrder : WorkOrder {

		/// <summary>
		/// Initializes a new instance of the <see cref="MaintenanceOrder"/> class
		/// </summary>
		public MaintenanceOrder(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end MaintenanceOrder

}//end namespace Work