///////////////////////////////////////////////////////////
//  WorkRequest.cs
//  Implementation of the Class WorkRequest
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:33 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Document used to plan or initiate work
	/// </summary>
	public class WorkRequest : Document {

		/// <summary>
		/// Initializes a new instance of the <see cref="WorkRequest"/> class
		/// </summary>
		public WorkRequest(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WorkRequest

}//end namespace Work
