///////////////////////////////////////////////////////////
//  WorkActivityRecord.cs
//  Implementation of the Class WorkActivityRecord
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:32 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Common;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Records information about the status of work or work task at a point in time.
	/// </summary>
	public class WorkActivityRecord : ActivityRecord {

		/// <summary>
		/// Estimated percentage of completion of this individual work task or overall work
		/// order.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.PerCent? percentComplete;

		/// <summary>
		/// Initializes a new instance of the <see cref="WorkActivityRecord"/> class
		/// </summary>
		public WorkActivityRecord(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WorkActivityRecord

}//end namespace Work
