///////////////////////////////////////////////////////////
//  WorkAsset.cs
//  Implementation of the Class WorkAsset
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:32 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.AssetInfo.Assets;
namespace TC57CIM.IEC61968.Work {
	/// <summary>
	/// Asset used to perform work.
	/// </summary>
	public class WorkAsset : Asset {

		/// <summary>
		/// Crew using this work asset.
		/// </summary>
		public TC57CIM.IEC61968.Common.Crew Crew;

		/// <summary>
		/// Initializes a new instance of the <see cref="WorkAsset"/> class
		/// </summary>
		public WorkAsset(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end WorkAsset

}//end namespace Work