///////////////////////////////////////////////////////////
//  VSCtype1.cs
//  Implementation of the Class VSCtype1
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:29 AM
//  Original author: civanov
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Dynamics.StandardModels.HVDCDynamics;
namespace TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC {
	public class VSCtype1 : VSCDynamics {

		public TC57CIM.IEC61970.Dynamics.StandardModels.InfHVDCDynamics.VSC.DCvoltageControl DCvoltageControl;

		public VSCtype1(){

		}

		~VSCtype1(){

		}

		public override void Dispose(){

		}

	}//end VSCtype1

}//end namespace VSC