///////////////////////////////////////////////////////////
//  ParentOrganization.cs
//  Implementation of the Class ParentOrganization
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:19 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Common {
	public class ParentOrganization : Organisation {

		public ParentOrganization(){

		}

		~ParentOrganization(){

		}

		public override void Dispose(){

		}

	}//end ParentOrganization

}//end namespace Common