///////////////////////////////////////////////////////////
//  ConformLoadSchedule.cs
//  Implementation of the Class ConformLoadSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:43 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// A curve of load  versus time (X-axis) showing the active power values (Y1-axis)
	/// and reactive power (Y2-axis) for each unit of the period covered. This curve
	/// represents a typical pattern of load over the time period for a given day type
	/// and season.
	/// </summary>
	public class ConformLoadSchedule : SeasonDayTypeSchedule {

		/// <summary>
		/// Initializes a new instance of the <see cref="ConformLoadSchedule"/> class
		/// </summary>
		public ConformLoadSchedule(){

		}

		~ConformLoadSchedule(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ConformLoadSchedule

}//end namespace LoadModel