///////////////////////////////////////////////////////////
//  LoadArea.cs
//  Implementation of the Class LoadArea
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// The class is the root or first level in a hierarchical structure for grouping
	/// of loads for the purpose of load flow load scaling.
	/// </summary>
	public class LoadArea : EnergyArea {

		/// <summary>
		/// The SubLoadAreas in the LoadArea.
		/// </summary>
		public TC57CIM.IEC61970.Base.LoadModel.SubLoadArea SubLoadAreas;

		/// <summary>
		/// Initializes a new instance of the <see cref="LoadArea"/> class
		/// </summary>
		public LoadArea(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end LoadArea

}//end namespace LoadModel