///////////////////////////////////////////////////////////
//  LoadGroup.cs
//  Implementation of the Class LoadGroup
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:06 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// The class is the third level in a hierarchical structure for grouping of loads
	/// for the purpose of load flow load scaling.
	/// </summary>
	public class LoadGroup : IdentifiedObject {

		/// <summary>
		/// Initializes a new instance of the <see cref="LoadGroup"/> class
		/// </summary>
		public LoadGroup(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end LoadGroup

}//end namespace LoadModel