///////////////////////////////////////////////////////////
//  NonConformLoadGroup.cs
//  Implementation of the Class NonConformLoadGroup
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// Loads that do not follow a daily and seasonal load variation pattern.
	/// </summary>
	public class NonConformLoadGroup : LoadGroup {

		/// <summary>
		/// Conform loads assigned to this ConformLoadGroup.
		/// </summary>
		public TC57CIM.IEC61970.Base.LoadModel.NonConformLoad? EnergyConsumers;
		/// <summary>
		/// The NonConformLoadSchedules in the NonConformLoadGroup.
		/// </summary>
		public TC57CIM.IEC61970.Base.LoadModel.NonConformLoadSchedule? NonConformLoadSchedules;

		/// <summary>
		/// Initializes a new instance of the <see cref="NonConformLoadGroup"/> class
		/// </summary>
		public NonConformLoadGroup(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end NonConformLoadGroup

}//end namespace LoadModel
