///////////////////////////////////////////////////////////
//  NonConformLoad.cs
//  Implementation of the Class NonConformLoad
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Wires;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// NonConformLoad represents loads that do not follow a daily load change pattern
	/// and whose changes are not correlated with the daily load change pattern.
	/// </summary>
	public class NonConformLoad : EnergyConsumer {

		/// <summary>
		/// Initializes a new instance of the <see cref="NonConformLoad"/> class
		/// </summary>
		public NonConformLoad(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end NonConformLoad

}//end namespace LoadModel
