///////////////////////////////////////////////////////////
//  SeasonDayTypeSchedule.cs
//  Implementation of the Class SeasonDayTypeSchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:21 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// A time schedule covering a 24 hour period, with curve data for a specific type
	/// of season and day.
	/// </summary>
	public class SeasonDayTypeSchedule : RegularIntervalSchedule {

		/// <summary>
		/// Initializes a new instance of the <see cref="SeasonDayTypeSchedule"/> class
		/// </summary>
		public SeasonDayTypeSchedule(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end SeasonDayTypeSchedule

}//end namespace LoadModel