///////////////////////////////////////////////////////////
//  StationSupply.cs
//  Implementation of the Class StationSupply
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:22 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Wires;
namespace TC57CIM.IEC61970.Base.LoadModel {
	/// <summary>
	/// Station supply with load derived from the station output.
	/// </summary>
	public class StationSupply : EnergyConsumer {

		/// <summary>
		/// Initializes a new instance of the <see cref="StationSupply"/> class
		/// </summary>
		public StationSupply(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end StationSupply

}//end namespace LoadModel