///////////////////////////////////////////////////////////
//  ActivePowerLimit.cs
//  Implementation of the Class ActivePowerLimit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:39 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.OperationalLimits {
	/// <summary>
	/// Limit on active power flow.
	/// </summary>
	public class ActivePowerLimit : OperationalLimit {

		/// <summary>
		/// The normal value of active power limit. The attribute shall be a positive value
		/// or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower normalValue;
		/// <summary>
		/// Value of active power limit. The attribute shall be a positive value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ActivePower value;

		/// <summary>
		/// Initializes a new instance of the <see cref="ActivePowerLimit"/> class
		/// </summary>
		public ActivePowerLimit(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ActivePowerLimit

}//end namespace OperationalLimits