///////////////////////////////////////////////////////////
//  CurrentLimit.cs
//  Implementation of the Class CurrentLimit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:45 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.OperationalLimits {
	/// <summary>
	/// Operational limit on current.
	/// </summary>
	public class CurrentLimit : OperationalLimit {

		/// <summary>
		/// The normal value for limit on current flow. The attribute shall be a positive
		/// value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow normalValue;
		/// <summary>
		/// Limit on current flow. The attribute shall be a positive value or zero.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow value;

		/// <summary>
		/// Initializes a new instance of the <see cref="CurrentLimit"/> class
		/// </summary>
		public CurrentLimit(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end CurrentLimit

}//end namespace OperationalLimits