///////////////////////////////////////////////////////////
//  OperationalLimitSet.cs
//  Implementation of the Class OperationalLimitSet
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:10 AM
//  Original author: kdd
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.Base.OperationalLimits {
	/// <summary>
	/// A set of limits associated with equipment.  Sets of limits might apply to a
	/// specific temperature, or season for example. A set of limits may contain
	/// different severities of limit levels that would apply to the same equipment.
	/// The set may contain limits of different types such as apparent power and
	/// current limits or high and low voltage limits  that are logically applied
	/// together as a set.
	/// </summary>
	public class OperationalLimitSet : IdentifiedObject {

		/// <summary>
		/// Values of equipment limits.
		/// </summary>
		public TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimit? OperationalLimitValue;
		/// <summary>
		/// The equipment to which the limit set applies.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.Equipment? Equipment;
		/// <summary>
		/// The terminal where the operational limit set apply.
		/// </summary>
		public TC57CIM.IEC61970.Base.Core.ACDCTerminal? Terminal;

		/// <summary>
		/// Initializes a new instance of the <see cref="OperationalLimitSet"/> class
		/// </summary>
		public OperationalLimitSet(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OperationalLimitSet

}//end namespace OperationalLimits
