///////////////////////////////////////////////////////////
//  UnavailablitySchedule.cs
//  Implementation of the Class UnavailablitySchedule
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:27 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans {
	/// <summary>
	/// A schedule of unavailability for one or more specified equipment that need to
	/// follow the same scheduling periods.
	/// </summary>
	public class UnavailablitySchedule : IdentifiedObject {

		/// <summary>
		/// The availability plan associated with this unavailability schedule.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans.AvailablityPlan? m_AvailablityPlan;

		/// <summary>
		/// Initializes a new instance of the <see cref="UnavailablitySchedule"/> class.
		/// </summary>
		public UnavailablitySchedule(){

		}

		/// <summary>
		/// Finalizes an instance of the <see cref="UnavailablitySchedule"/> class.
		/// </summary>
		~UnavailablitySchedule(){

		}

		/// <summary>
		/// Releases resources used by the <see cref="UnavailablitySchedule"/> class.
		/// </summary>
		public override void Dispose(){

		}

	}//end UnavailablitySchedule

}//end namespace InfAvailabilityPlans