///////////////////////////////////////////////////////////
//  UnavailabilityScheduleDependency.cs
//  Implementation of the Class UnavailabilityScheduleDependency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:27 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans {
	/// <summary>
	/// Represents a dependency between unavailability schedules.
	/// </summary>
	public class UnavailabilityScheduleDependency : IdentifiedObject {

		/// <summary>
		/// The schedule that is impacted by this dependency.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans.UnavailablitySchedule? UnavailabilityScheduleImpacts;
		/// <summary>
		/// The schedule that this dependency depends on.
		/// </summary>
		public TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans.UnavailablitySchedule? UnavailabilityScheduleDependsOn;

		/// <summary>
		/// Initializes a new instance of the <see cref="UnavailabilityScheduleDependency"/> class.
		/// </summary>
		public UnavailabilityScheduleDependency(){

		}

    /// <summary>
    /// Releases resources used by the <see cref="UnavailabilityScheduleDependency"/> class.
    /// </summary>
    public override void Dispose(){

		}

	}//end UnavailabilityScheduleDependency

}//end namespace InfAvailabilityPlans
