///////////////////////////////////////////////////////////
//  UnavailabilityScheduleDependency.cs
//  Implementation of the Class UnavailabilityScheduleDependency
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:27 AM
//  Original author: 222206
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Core;
namespace TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans {
	public class UnavailabilityScheduleDependency : IdentifiedObject {

		public TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans.UnavailablitySchedule UnavailabilityScheduleImpacts;
		public TC57CIM.IEC61970.InfIEC61970.InfAvailabilityPlans.UnavailablitySchedule UnavailabilityScheduleDependsOn;

		public UnavailabilityScheduleDependency(){

		}

		~UnavailabilityScheduleDependency(){

		}

		public override void Dispose(){

		}

	}//end UnavailabilityScheduleDependency

}//end namespace InfAvailabilityPlans