///////////////////////////////////////////////////////////
//  ConcentricNeutralCableInfo.cs
//  Implementation of the Class ConcentricNeutralCableInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: Tom
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Concentric neutral cable data.
	/// </summary>
	public class ConcentricNeutralCableInfo : CableInfo {

		/// <summary>
		/// Diameter over the concentric neutral strands.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Length? diameterOverNeutral;
		/// <summary>
		/// Number of concentric neutral strands.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer? neutralStrandCount;
		/// <summary>
		/// Geometric mean radius of the neutral strand.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Length? neutralStrandGmr;
		/// <summary>
		/// Outside radius of the neutral strand.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Length? neutralStrandRadius;
		/// <summary>
		/// DC resistance per unit length of the neutral strand at 20 �C.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.ResistancePerLength? neutralStrandRDC20;

		/// <summary>
		/// Initializes a new instance of the <see cref="ConcentricNeutralCableInfo"/> class
		/// </summary>
		public ConcentricNeutralCableInfo(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end ConcentricNeutralCableInfo

}//end namespace AssetInfo
