///////////////////////////////////////////////////////////
//  OperatingMechanismInfo.cs
//  Implementation of the Class OperatingMechanismInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:18 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Breaker operating mechanism datasheet information.
	/// </summary>
	public class OperatingMechanismInfo : Assets.AssetInfo {

		/// <summary>
		/// Close current (nominal).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow closeAmps;
		/// <summary>
		/// Close voltage in volts DC.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage closeVoltage;
		/// <summary>
		/// Kind of breaker operating mechanism.
		/// </summary>
		public OperatingMechanismKind mechanismKind;
		/// <summary>
		/// Rated motor run current in amps.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow motorRunCurrent;
		/// <summary>
		/// Rated motor start current in amps.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow motorStartCurrent;
		/// <summary>
		/// Nominal motor voltage in volts DC.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage motorVoltage;
		/// <summary>
		/// Trip current (nominal).
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.CurrentFlow tripAmps;
		/// <summary>
		/// Trip voltage in volts DC.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Voltage tripVoltage;

		/// <summary>
		/// Initializes a new instance of the <see cref="OperatingMechanismInfo"/> class
		/// </summary>
		public OperatingMechanismInfo(){

		}

		~OperatingMechanismInfo(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end OperatingMechanismInfo

}//end namespace AssetInfo