///////////////////////////////////////////////////////////
//  OverheadWireInfo.cs
//  Implementation of the Class OverheadWireInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:19 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Overhead wire data.
	/// </summary>
	public class OverheadWireInfo : WireInfo {

		/// <summary>
		/// Initializes a new instance of the <see cref="OverheadWireInfo"/> class
		/// </summary>
		public OverheadWireInfo(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OverheadWireInfo

}//end namespace AssetInfo