///////////////////////////////////////////////////////////
//  TransformerTankInfo.cs
//  Implementation of the Class TransformerTankInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Set of transformer tank data, from an equipment library.
	/// </summary>
	public class TransformerTankInfo : Assets.AssetInfo {

		/// <summary>
		/// Data for all the ends described by this transformer tank data.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.TransformerEndInfo TransformerEndInfos;
		/// <summary>
		/// Power transformer data that this tank description is part of.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.PowerTransformerInfo PowerTransformerInfo;

		/// <summary>
		/// Initializes a new instance of the <see cref="TransformerTankInfo"/> class
		/// </summary>
		public TransformerTankInfo(){

		}

		~TransformerTankInfo(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end TransformerTankInfo

}//end namespace AssetInfo