///////////////////////////////////////////////////////////
//  WirePhaseInfo.cs
//  Implementation of the Class WirePhaseInfo
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:32 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetInfo {
	/// <summary>
	/// Information on a wire carrying a single phase.
	/// </summary>
	public class WirePhaseInfo {

		/// <summary>
		/// Phase information.
		/// </summary>
		public TC57CIM.IEC61970.Base.Wires.SinglePhaseKind? phaseInfo;
		/// <summary>
		/// Wire assembly information using this wire phase information.
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.WireAssemblyInfo? WireAssemblyInfo;

		/// <summary>
		/// Initializes a new instance of the <see cref="WirePhaseInfo"/> class
		/// </summary>
		public WirePhaseInfo(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public virtual void Dispose(){

		}

	}//end WirePhaseInfo

}//end namespace AssetInfo
