///////////////////////////////////////////////////////////
//  Assignment.cs
//  Implementation of the Class Assignment
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Base.Domain;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// An assignment is given to an ErpPerson, Crew, Organisation, Equipment Item,
	/// Tool, etc. and may be used to perform Work, WorkTasks, Procedures, etc.
	/// TimeSchedules may be set up directly for Assignments or indirectly via the
	/// associated WorkTask. Note that these associations are all inherited through the
	/// recursive relationship on Document.
	/// </summary>
	public class Assignment : WorkDocument {

		/// <summary>
		/// Period between the assignment becoming effective and its expiration.
		/// </summary>
		public DateTimeInterval? effectivePeriod;

		/// <summary>
		/// Initializes a new instance of the <see cref="Assignment"/> class
		/// </summary>
		public Assignment(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Assignment

}//end namespace InfWork
