///////////////////////////////////////////////////////////
//  BusinessCase.cs
//  Implementation of the Class BusinessCase
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:59 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Business justification for capital expenditures, usually addressing operations
	/// and maintenance costs as well.
	/// </summary>
	public class BusinessCase : WorkDocument {

		/// <summary>
		/// A codified representation of the business case (i.e., codes for highway
		/// relocation, replace substation transformers, etc.).
		/// </summary>
		public string? corporateCode;
		/// <summary>
		/// The projects
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.Project? Projects;
		/// <summary>
		/// The works
		/// </summary>
		public TC57CIM.IEC61968.Work.Work? Works;

		/// <summary>
		/// Initializes a new instance of the <see cref="BusinessCase"/> class
		/// </summary>
		public BusinessCase(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end BusinessCase

}//end namespace InfWork
