///////////////////////////////////////////////////////////
//  CompatibleUnit.cs
//  Implementation of the Class CompatibleUnit
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:01 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A pre-planned job model containing labor, material, and accounting requirements
	/// for standardized job planning.
	/// </summary>
	public class CompatibleUnit : WorkDocument {

		/// <summary>
		/// Estimated total cost for perfoming CU.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money? estCost;
		/// <summary>
		/// The quantity, unit of measure, and multiplier at the CU level that applies to
		/// the materials.
		/// </summary>
		public string? quantity;
		/// <summary>
		/// The generic asset model
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.CatalogAssetType? GenericAssetModel;
		/// <summary>
		/// The cu group
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CUGroup? CUGroup;
		/// <summary>
		/// The procedures
		/// </summary>
		public TC57CIM.IEC61968.AssetInfo.Assets.Procedure? Procedures;
		/// <summary>
		/// The design location us
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.DesignLocationCU? DesignLocationCUs;

		/// <summary>
		/// Initializes a new instance of the <see cref="CompatibleUnit"/> class
		/// </summary>
		public CompatibleUnit(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end CompatibleUnit

}//end namespace InfWork
