///////////////////////////////////////////////////////////
//  ConditionFactor.cs
//  Implementation of the Class ConditionFactor
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// This is to specify the various condition factors for a design that may alter
	/// the cost estimate or the allocation.
	/// </summary>
	public class ConditionFactor : WorkIdentifiedObject {

		/// <summary>
		/// The actual value of the condition factor, such as labor flat fee or percentage.
		/// 
		/// </summary>
		public string cfValue;
		/// <summary>
		/// Kind of this condition factor.
		/// </summary>
		public ConditionFactorKind kind;
		public TC57CIM.IEC61968.Common.Status status;

		public ConditionFactor(){

		}

		~ConditionFactor(){

		}

		public override void Dispose(){

		}

	}//end ConditionFactor

}//end namespace InfWork