///////////////////////////////////////////////////////////
//  ConditionFactorKind.cs
//  Implementation of the Class ConditionFactorKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:02 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Kind of condition factor.
	/// </summary>
	public enum ConditionFactorKind : int {

		/// <summary>
		/// The labor condition factor kind
		/// </summary>
		labor,
		/// <summary>
		/// The account allocation condition factor kind
		/// </summary>
		accountAllocation,
		/// <summary>
		/// The material condition factor kind
		/// </summary>
		material,
		/// <summary>
		/// The travel condition factor kind
		/// </summary>
		travel,
		/// <summary>
		/// The other condition factor kind
		/// </summary>
		other

	}//end ConditionFactorKind

}//end namespace InfWork
