///////////////////////////////////////////////////////////
//  CUAllowableAction.cs
//  Implementation of the Class CUAllowableAction
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Allowed actions: Install, Remove, Transfer, Abandon, etc.
	/// </summary>
	public class CUAllowableAction : WorkIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The compatible units
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CompatibleUnit CompatibleUnits;

		/// <summary>
		/// Initializes a new instance of the <see cref="CUAllowableAction"/> class
		/// </summary>
		public CUAllowableAction(){

		}

		~CUAllowableAction(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end CUAllowableAction

}//end namespace InfWork