///////////////////////////////////////////////////////////
//  CUContractorItem.cs
//  Implementation of the Class CUContractorItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Compatible unit contractor item.
	/// </summary>
	public class CUContractorItem : WorkIdentifiedObject {

		/// <summary>
		/// Activity code identifies a specific and distinguishable unit of work.
		/// </summary>
		public string activityCode;
		/// <summary>
		/// The amount that a given contractor will charge for performing this unit of work.
		/// 
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money bidAmount;
		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The compatible units
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CompatibleUnit CompatibleUnits;

		/// <summary>
		/// Initializes a new instance of the <see cref="CUContractorItem"/> class
		/// </summary>
		public CUContractorItem(){

		}

		~CUContractorItem(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end CUContractorItem

}//end namespace InfWork