///////////////////////////////////////////////////////////
//  CUGroup.cs
//  Implementation of the Class CUGroup
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:03 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A Compatible Unit Group identifies a set of compatible units which may be
	/// jointly utilized for estimating and designating jobs.
	/// </summary>
	public class CUGroup : WorkIdentifiedObject {

		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The child cu groups
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CUGroup ChildCUGroups;

		/// <summary>
		/// Initializes a new instance of the <see cref="CUGroup"/> class
		/// </summary>
		public CUGroup(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end CUGroup

}//end namespace InfWork