///////////////////////////////////////////////////////////
//  Design.cs
//  Implementation of the Class Design
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A design for consideration by customers, potential customers, or internal work.
	///
	/// Note that the Version of design is the revision attribute that is inherited
	/// from Document.
	/// </summary>
	public class Design : WorkDocument {

		/// <summary>
		/// Estimated cost (not price) of design.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money? costEstimate;
		/// <summary>
		/// Kind of this design.
		/// </summary>
		public DesignKind kind;
		/// <summary>
		/// Price to customer for implementing design.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money? price;
		/// <summary>
		/// The erp bo ms
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpBOM? ErpBOMs;
		/// <summary>
		/// The work cost details
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.WorkCostDetail? WorkCostDetails;
		/// <summary>
		/// The work tasks
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.OldWorkTask? WorkTasks;
		/// <summary>
		/// The work
		/// </summary>
		public TC57CIM.IEC61968.Work.Work? Work;
		/// <summary>
		/// The condition factors
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.ConditionFactor? ConditionFactors;

		/// <summary>
		/// Initializes a new instance of the <see cref="Design"/> class
		/// </summary>
		public Design(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Design

}//end namespace InfWork
