///////////////////////////////////////////////////////////
//  DesignLocationCU.cs
//  Implementation of the Class DesignLocationCU
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Compatible unit at a given design location.
	/// </summary>
	public class DesignLocationCU : WorkIdentifiedObject {

		/// <summary>
		/// A code that helps direct accounting (capital, expense, or accounting treatment).
		///
		/// </summary>
		public string? cuAccount;
		/// <summary>
		/// A code that instructs the crew what action to perform.
		/// </summary>
		public WorkActionKind cuAction;
		/// <summary>
		/// The quantity of the CU being assigned to this location.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.IntegerQuantity? cuQuantity;
		/// <summary>
		/// As the same CU can be used for different purposes and accounting purposes,
		/// usage must be specified. Examples include: distribution, transmission,
		/// substation.
		/// </summary>
		public string? cuUsage;
		/// <summary>
		/// Year when a CU that represents an asset is removed.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Date? removalDate;
		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status? status;
		/// <summary>
		/// True if associated electrical equipment is intended to be energized while work
		/// is being performed.
		/// </summary>
		public bool toBeEnergised;
		/// <summary>
		/// The cu groups
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.CUGroup? CUGroups;
		/// <summary>
		/// The designs
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.Design? Designs;
		/// <summary>
		/// The condition factors
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.ConditionFactor? ConditionFactors;
		/// <summary>
		/// The work tasks
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.OldWorkTask? WorkTasks;

		/// <summary>
		/// Initializes a new instance of the <see cref="DesignLocationCU"/> class
		/// </summary>
		public DesignLocationCU(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end DesignLocationCU

}//end namespace InfWork
