///////////////////////////////////////////////////////////
//  DesignKind.cs
//  Implementation of the Class DesignKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:05 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Kind of design.
	/// </summary>
	public enum DesignKind : int {

		/// <summary>
		/// The estimated design kind
		/// </summary>
		estimated,
		/// <summary>
		/// The as built design kind
		/// </summary>
		asBuilt,
		/// <summary>
		/// The other design kind
		/// </summary>
		other

	}//end DesignKind

}//end namespace InfWork