///////////////////////////////////////////////////////////
//  NonStandardItem.cs
//  Implementation of the Class NonStandardItem
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:16 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// This document provides information for non-standard items like customer
	/// contributions (e.g., customer digs trench), vouchers (e.g., credit), and
	/// contractor bids.
	/// </summary>
	public class NonStandardItem : WorkDocument {

		/// <summary>
		/// The projected cost for this item.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money? amount;

		/// <summary>
		/// Initializes a new instance of the <see cref="NonStandardItem"/> class
		/// </summary>
		public NonStandardItem(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end NonStandardItem

}//end namespace InfWork
