///////////////////////////////////////////////////////////
//  OldWorkTask.cs
//  Implementation of the Class OldWorkTask
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Work;
namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A set of tasks is required to implement a design.
	/// </summary>
	public class OldWorkTask : WorkTask {

		/// <summary>
		/// The contractor items
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.ContractorItem ContractorItems;
		/// <summary>
		/// The qualification requirements
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.QualificationRequirement QualificationRequirements;
		/// <summary>
		/// The usages
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.Usage Usages;
		/// <summary>
		/// The misc cost items
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.MiscCostItem MiscCostItems;
		/// <summary>
		/// The overhead cost
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.OverheadCost OverheadCost;
		/// <summary>
		/// The labor items
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.LaborItem LaborItems;

		/// <summary>
		/// Initializes a new instance of the <see cref="OldWorkTask"/> class
		/// </summary>
		public OldWorkTask(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OldWorkTask

}//end namespace InfWork