///////////////////////////////////////////////////////////
//  OneCallRequest.cs
//  Implementation of the Class OneCallRequest
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// A request for other utilities to mark their underground facilities prior to
	/// commencement of construction and/or maintenance.
	/// </summary>
	public class OneCallRequest : WorkDocument {

		/// <summary>
		/// True if explosives have been or are planned to be used.
		/// </summary>
		public bool explosivesUsed;
		/// <summary>
		/// True if work location has been marked, for example for a dig area.
		/// </summary>
		public bool markedIndicator;
		/// <summary>
		/// Instructions for marking a dig area, if applicable.
		/// </summary>
		public string markingInstruction;

		/// <summary>
		/// Initializes a new instance of the <see cref="OneCallRequest"/> class
		/// </summary>
		public OneCallRequest(){

		}

		~OneCallRequest(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end OneCallRequest

}//end namespace InfWork