///////////////////////////////////////////////////////////
//  OverheadCost.cs
//  Implementation of the Class OverheadCost
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:19 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Overhead cost applied to work order.
	/// </summary>
	public class OverheadCost : WorkIdentifiedObject {

		/// <summary>
		/// Overhead code.
		/// </summary>
		public string code;
		/// <summary>
		/// The overhead cost to be applied.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Money cost;
		/// <summary>
		/// The status
		/// </summary>
		public TC57CIM.IEC61968.Common.Status status;
		/// <summary>
		/// The work cost details
		/// </summary>
		public TC57CIM.IEC61968.InfIEC61968.InfWork.WorkCostDetail WorkCostDetails;

		/// <summary>
		/// Initializes a new instance of the <see cref="OverheadCost"/> class
		/// </summary>
		public OverheadCost(){

		}

		~OverheadCost(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end OverheadCost

}//end namespace InfWork