///////////////////////////////////////////////////////////
//  Regulation.cs
//  Implementation of the Class Regulation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:22 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.InfIEC61968.InfWork {
	/// <summary>
	/// Special requirements and/or regulations may pertain to certain types of assets
	/// or work. For example, fire protection and scaffolding.
	/// </summary>
	public class Regulation : WorkDocument {

		/// <summary>
		/// External reference to regulation, if applicable.
		/// </summary>
		public string referenceNumber;

		/// <summary>
		/// Initializes a new instance of the <see cref="Regulation"/> class
		/// </summary>
		public Regulation(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end Regulation

}//end namespace InfWork