///////////////////////////////////////////////////////////
//  AssetTemperaturePressureAnalog.cs
//  Implementation of the Class AssetTemperaturePressureAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:32:58 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Temperature or pressure type of asset analog.
	/// </summary>
	public class AssetTemperaturePressureAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing temperature or pressure related to an asset.
		/// </summary>
		public AssetTemperaturePressureAnalogKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="AssetTemperaturePressureAnalog"/> class
		/// </summary>
		public AssetTemperaturePressureAnalog(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end AssetTemperaturePressureAnalog

}//end namespace AssetMeas