///////////////////////////////////////////////////////////
//  InspectionAnalog.cs
//  Implementation of the Class InspectionAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Asset inspection type of analog.
	/// </summary>
	public class InspectionAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing inspection result.
		/// </summary>
		public InspectionAnalogKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="InspectionAnalog"/> class
		/// </summary>
		public InspectionAnalog(){

		}

		~InspectionAnalog(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end InspectionAnalog

}//end namespace AssetMeas