///////////////////////////////////////////////////////////
//  InspectionDiscrete.cs
//  Implementation of the Class InspectionDiscrete
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:12 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Asset inspection type of discrete.
	/// </summary>
	public class InspectionDiscrete : AssetDiscrete {

		/// <summary>
		/// Kind of discrete representing inspection result.
		/// </summary>
		public InspectionDiscreteKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="InspectionDiscrete"/> class
		/// </summary>
		public InspectionDiscrete(){

		}

		~InspectionDiscrete(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end InspectionDiscrete

}//end namespace AssetMeas