///////////////////////////////////////////////////////////
//  OilAnalysisFluidAnalog.cs
//  Implementation of the Class OilAnalysisFluidAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:16 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Asset oil analysis fluid test type of analog.
	/// .
	/// </summary>
	public class OilAnalysisFluidAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing oil fluid test analysis result.
		/// </summary>
		public OilAnalysisFluidAnalogKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="OilAnalysisFluidAnalog"/> class
		/// </summary>
		public OilAnalysisFluidAnalog(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OilAnalysisFluidAnalog

}//end namespace AssetMeas
