///////////////////////////////////////////////////////////
//  OilAnalysisParticleAnalog.cs
//  Implementation of the Class OilAnalysisParticleAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:16 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Asset oil analysis particle type of analog.
	/// </summary>
	public class OilAnalysisParticleAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing oil particulate analysis result.
		/// </summary>
		public OilAnalysisParticleAnalogKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="OilAnalysisParticleAnalog"/> class
		/// </summary>
		public OilAnalysisParticleAnalog(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end OilAnalysisParticleAnalog

}//end namespace AssetMeas