///////////////////////////////////////////////////////////
//  OilAnalysisPCBAnalog.cs
//  Implementation of the Class OilAnalysisPCBAnalog
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:17 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Asset oil analysis PCB type of analog.
	/// </summary>
	public class OilAnalysisPCBAnalog : AssetAnalog {

		/// <summary>
		/// Kind of analog representing oil PCB analysis result.
		/// </summary>
		public OilAnalysisPCBAnalogKind kind;

		/// <summary>
		/// Initializes a new instance of the <see cref="OilAnalysisPCBAnalog"/> class
		/// </summary>
		public OilAnalysisPCBAnalog(){

		}

		~OilAnalysisPCBAnalog(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end OilAnalysisPCBAnalog

}//end namespace AssetMeas