///////////////////////////////////////////////////////////
//  PeriodicStatisticalCalculation.cs
//  Implementation of the Class PeriodicStatisticalCalculation
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:20 AM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.AssetMeas {
	/// <summary>
	/// Description of period for which calculation is performed.
	/// </summary>
	public class PeriodicStatisticalCalculation : StatisticalCalculation {

		/// <summary>
		/// Number of units (of calculationIntervalUnit) in the calculation interval.
		/// </summary>
		public TC57CIM.IEC61970.Base.Domain.Integer calculationIntervalMagnitude;
		/// <summary>
		/// Unit in which calculation interval is defined.
		/// </summary>
		public CalculationIntervalUnitKind calculationIntervalUnit;

		/// <summary>
		/// Initializes a new instance of the <see cref="PeriodicStatisticalCalculation"/> class
		/// </summary>
		public PeriodicStatisticalCalculation(){

		}

    /// <summary>
    /// Disposes this instance
    /// </summary>
    public override void Dispose(){

		}

	}//end PeriodicStatisticalCalculation

}//end namespace AssetMeas