///////////////////////////////////////////////////////////
//  ExcitationSystemUserDefined.cs
//  Implementation of the Class ExcitationSystemUserDefined
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:04:54 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics;
namespace TC57CIM.IEC61970.Dynamics.UserDefinedModels {
	/// <summary>
	/// Excitation system function block whose dynamic behaviour is described by
	/// a user-defined model.
	/// </summary>
	public class ExcitationSystemUserDefined : ExcitationSystemDynamics {

		/// <summary>
		/// Behaviour is based on a proprietary model as opposed to a detailed model.
		/// true = user-defined model is proprietary with behaviour mutually understood by
		/// sending and receiving applications and parameters passed as general attributes
		/// false = user-defined model is explicitly defined in terms of control blocks and
		/// their input and output signals.
		/// </summary>
		public bool proprietary;

		/// <summary>
		/// Constructor for ExcitationSystemUserDefined.
		/// </summary>
		public ExcitationSystemUserDefined(){

		}

    /// <summary>
    /// Dispose method for ExcitationSystemUserDefined.
    /// </summary>
    public override void Dispose(){

		}

	}//end ExcitationSystemUserDefined

}//end namespace UserDefinedModels
