///////////////////////////////////////////////////////////
//  OverexcitationLimiterUserDefined.cs
//  Implementation of the Class OverexcitationLimiterUserDefined
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:11 AM
//  Original author: ppbr003
///////////////////////////////////////////////////////////

using TC57CIM.IEC61970.Dynamics.StandardModels.OverexcitationLimiterDynamics;
namespace TC57CIM.IEC61970.Dynamics.UserDefinedModels {
	/// <summary>
	/// Overexcitation limiter system function block whose dynamic behaviour is
	/// described by a user-defined model.
	/// </summary>
	public class OverexcitationLimiterUserDefined : OverexcitationLimiterDynamics {

		/// <summary>
		/// Behaviour is based on a proprietary model as opposed to a detailed model.
		/// true = user-defined model is proprietary with behaviour mutually understood by
		/// sending and receiving applications and parameters passed as general attributes
		/// false = user-defined model is explicitly defined in terms of control blocks and
		/// their input and output signals.
		/// </summary>
		public bool proprietary;

		/// <summary>
		/// Constructor for OverexcitationLimiterUserDefined.
		/// </summary>
		public OverexcitationLimiterUserDefined(){

		}

		/// <summary>
		/// Destructor for OverexcitationLimiterUserDefined.
		/// </summary>
		~OverexcitationLimiterUserDefined(){

		}

		/// <summary>
		/// Dispose method for OverexcitationLimiterUserDefined.
		/// </summary>
		public override void Dispose(){

		}

	}//end OverexcitationLimiterUserDefined

}//end namespace UserDefinedModels