///////////////////////////////////////////////////////////
//  ServiceRequest.cs
//  Implementation of the Class ServiceRequest
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:24 AM
//  Original author: marga
///////////////////////////////////////////////////////////

using TC57CIM.IEC61968.Work;
namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The service request class
	/// </summary>
	/// <seealso cref="WorkRequest"/>
	public class ServiceRequest : WorkRequest {

		/// <summary>
		/// The appointment requested
		/// </summary>
		public bool appointmentRequested;
		/// <summary>
		/// The kind
		/// </summary>
		public ServiceRequestKind kind;
		/// <summary>
		/// The service kind
		/// </summary>
		public ServiceKind serviceKind;
		/// <summary>
		/// The size or quantity requested by the customer; for example, 200 AMPS for
		/// electrical service, 50 MBits per second for internet service, etc.
		/// </summary>
		public string serviceSize;
		/// <summary>
		/// All work time schedules associated with a service request
		/// </summary>
		public TC57CIM.IEC61968.Work.WorkTimeSchedule WorkTimeSchedule;
		/// <summary>
		/// The service location for the serivce request
		/// </summary>
		public TC57CIM.IEC61968.Customers.ServiceLocation ServiceLocation;
		/// <summary>
		/// The customer making the service request
		/// </summary>
		public TC57CIM.IEC61968.Customers.Customer Customer;

		/// <summary>
		/// Initializes a new instance of the <see cref="ServiceRequest"/> class
		/// </summary>
		public ServiceRequest(){

		}

		~ServiceRequest(){

		}

		/// <summary>
		/// Disposes this instance
		/// </summary>
		public override void Dispose(){

		}

	}//end ServiceRequest

}//end namespace Customers