///////////////////////////////////////////////////////////
//  TroubleSymptomsWireKind.cs
//  Implementation of the Class TroubleSymptomsWireKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of items that define the wire problem.
	/// </summary>
	public enum TroubleSymptomsWireKind : int {

		/// <summary>
		/// The service down trouble symptoms wire kind
		/// </summary>
		serviceDown,
		/// <summary>
		/// The wire down trouble symptoms wire kind
		/// </summary>
		wireDown,
		/// <summary>
		/// The wireburning trouble symptoms wire kind
		/// </summary>
		wireburning,
		/// <summary>
		/// The other trouble symptoms wire kind
		/// </summary>
		other,
		/// <summary>
		/// The ok trouble symptoms wire kind
		/// </summary>
		ok,
		/// <summary>
		/// The dig in trouble symptoms wire kind
		/// </summary>
		digIn

	}//end TroubleSymptomsWireKind

}//end namespace Customers