///////////////////////////////////////////////////////////
//  TroubleSymptomsPoleKind.cs
//  Implementation of the Class TroubleSymptomsPoleKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of values that define the Pole problem.
	/// </summary>
	public enum TroubleSymptomsPoleKind : int {

		/// <summary>
		/// The ok trouble symptoms pole kind
		/// </summary>
		ok,
		/// <summary>
		/// The down trouble symptoms pole kind
		/// </summary>
		down,
		/// <summary>
		/// The leaning trouble symptoms pole kind
		/// </summary>
		leaning,
		/// <summary>
		/// The hit trouble symptoms pole kind
		/// </summary>
		hit,
		/// <summary>
		/// The other trouble symptoms pole kind
		/// </summary>
		other

	}//end TroubleSymptomsPoleKind

}//end namespace Customers