///////////////////////////////////////////////////////////
//  TroubleSymptomsTransformerKind.cs
//  Implementation of the Class TroubleSymptomsTransformerKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of items that define the transformer problem.
	/// </summary>
	public enum TroubleSymptomsTransformerKind : int {

		/// <summary>
		/// The ok trouble symptoms transformer kind
		/// </summary>
		ok,
		/// <summary>
		/// The burning trouble symptoms transformer kind
		/// </summary>
		burning,
		/// <summary>
		/// The other trouble symptoms transformer kind
		/// </summary>
		other

	}//end TroubleSymptomsTransformerKind

}//end namespace Customers