///////////////////////////////////////////////////////////
//  TroubleSymptomsLightKind.cs
//  Implementation of the Class TroubleSymptomsLightKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The list of values that define the light problem.
	/// </summary>
	public enum TroubleSymptomsLightKind : int {

		/// <summary>
		/// The ok trouble symptoms light kind
		/// </summary>
		ok,
		/// <summary>
		/// The all out trouble symptoms light kind
		/// </summary>
		allOut,
		/// <summary>
		/// The part out trouble symptoms light kind
		/// </summary>
		partOut,
		/// <summary>
		/// The flickering trouble symptoms light kind
		/// </summary>
		flickering,
		/// <summary>
		/// The dim trouble symptoms light kind
		/// </summary>
		dim,
		/// <summary>
		/// The other trouble symptoms light kind
		/// </summary>
		other

	}//end TroubleSymptomsLightKind

}//end namespace Customers