///////////////////////////////////////////////////////////
//  TroubleSymptomsExtentKind.cs
//  Implementation of the Class TroubleSymptomsExtentKind
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:33:29 AM
//  Original author: marga
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61968.Customers {
	/// <summary>
	/// The enumerated values that define the extent of the problem.
	/// </summary>
	public enum TroubleSymptomsExtentKind : int {

		/// <summary>
		/// The single customer trouble symptoms extent kind
		/// </summary>
		singleCustomer,
		/// <summary>
		/// The ok trouble symptoms extent kind
		/// </summary>
		ok,
		/// <summary>
		/// The neighbour trouble symptoms extent kind
		/// </summary>
		neighbour,
		/// <summary>
		/// The other trouble symptoms extent kind
		/// </summary>
		other,
		/// <summary>
		/// The entire neighbourhood trouble symptoms extent kind
		/// </summary>
		entireNeighbourhood

	}//end TroubleSymptomsExtentKind

}//end namespace Customers
