///////////////////////////////////////////////////////////
//  Subcritical.cs
//  Implementation of the Class Subcritical
//  Generated by Enterprise Architect
//  Created on:      15-Jun-2024 10:05:22 AM
///////////////////////////////////////////////////////////

namespace TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation {
	/// <summary>
	/// Once-through subcritical boiler.
	/// </summary>
	public class Subcritical : FossilSteamSupply {

		public Subcritical(){

		}

		~Subcritical(){

		}

		public override void Dispose(){

		}

	}//end Subcritical

}//end namespace GenerationTrainingSimulation